In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

# Imports

In [2]:
main_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/main_gdf.parquet")
tailings_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/tailings_gdf.parquet")
cmmi_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/cmmi_gdf.parquet")
min_can_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/min_can_gdf.parquet")
ctrace_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/ctrace_gdf.parquet")
conflict_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/conflict_gdf.parquet")
ghg_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/ghg_gdf.parquet")
npri_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/pollutant_gdf.parquet")
climate_category_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/climate_category_gdf.parquet")
weather_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/weather_gdf.parquet")
peatland_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/peatland_gdf.parquet")
prioritization_area_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/prioritization_area_gdf.parquet")
population_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/population_gdf.parquet")
water_risk_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/water_risk_gdf.parquet")
land_cover_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/land_cover_gdf.parquet")
npv_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/npv_gdf.parquet")
indigenous_can_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/indigenous_can_gdf.parquet")
wpda_gdf_polygons = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/wpda_gdf_polygons.parquet")
tang_canada_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/tang_canada_gdf.parquet")
li_canada_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/li_canada_gdf.parquet")

In [3]:
bth_df = pd.read_excel(r'data/Sources/Greffe_2024/BtH_mapped_sites.xlsx')

In [27]:
# From manually collected data
production_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Production')
tech_attributes_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Technical_attributes')
reserves_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Reserves')
technosphere_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='NRJ_mat')
env_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Env')
waste_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Waste')                       
intensity_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Intensity')
archetypes_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Archetype')

In [28]:
from db_creation_function import assign_row_id_to_collected_data

In [29]:
# We need to assign row_ids to the manually collected data
production_df = assign_row_id_to_collected_data(production_df, 
                  facility_id_col='main_id',
                  prefix='PROD',
                  year_col='year'           
                  )

tech_attributes_df = assign_row_id_to_collected_data(tech_attributes_df, 
                  facility_id_col='main_id',
                  prefix='TA',
                  year_col='year'           
                  )
reserves_df = assign_row_id_to_collected_data(reserves_df, 
                  facility_id_col='main_id',
                  prefix='RES',
                  year_col='year'           
                  )

technosphere_df = assign_row_id_to_collected_data(technosphere_df, 
                  facility_id_col='main_id',
                  prefix='TECH',
                  year_col='year'           
                  )

env_df = assign_row_id_to_collected_data(env_df, 
                  facility_id_col='main_id',
                  prefix='ENV',
                  year_col='year'           
                  )

waste_df = assign_row_id_to_collected_data(waste_df, 
                  facility_id_col='main_id',
                  prefix='WASTE',
                  year_col='year'           
                  )

intensity_df = assign_row_id_to_collected_data(intensity_df, 
                  facility_id_col='main_id',
                  prefix='INT',
                  year_col='year'           
                  )

archetypes_df = assign_row_id_to_collected_data(archetypes_df, 
                  facility_id_col='main_id',
                  prefix='ARCH',
                  )

# Create auxiliary tables

## Source table

In [8]:
# For the main table
source_map = {
    "project": "https://open.canada.ca/data/en/dataset/22b2db8a-dc12-47f2-9737-99d3da921751",
    "mining": "https://open.canada.ca/data/en/dataset/000183ed-8864-42f0-ae43-c4313a860720",
    "manufacturing": "https://open.canada.ca/data/en/dataset/000183ed-8864-42f0-ae43-c4313a860720"
}
main_gdf["source_id"] = main_gdf["facility_type"].map(source_map)
main_gdf

,main_id,facility_name,facility_group_name,facility_group_id,reported_company,company_name_folder,company_id,longitude,latitude,geometry,...,province,status,activity_status,development_stage,facility_type,mining_processing_type,commodity_group,primary_commodity,commodities,source_id
0,QC-MAIN-5801b453,Abcourt-Barvue,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.679010,48.521540,POINT (-77.67901 48.52154),...,Quebec,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, silver",https://open.canada.ca/data/en/dataset/22b2db8...
1,QC-MAIN-d29e0839,Sleeping Giant,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.974340,49.132590,POINT (-77.97434 49.13259),...,Quebec,active_facility,None,None,mining,Concentrator,Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...
2,QC-MAIN-f1ff4920,Akasaba West,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-77.580000,48.040000,POINT (-77.58000 48.04000),...,Quebec,project_facility,Active,Advanced project,project,None,None,Gold,"Gold, copper",https://open.canada.ca/data/en/dataset/22b2db8...
3,NU-MAIN-4ea8ac9d,Amaruq,Meadowbank complex,GRP-0a2c0d69,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-96.697000,65.415000,POINT (-96.69700 65.41500),...,Nunavut,active_facility,None,None,mining,"Open-pit, underground",Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...
4,QC-MAIN-e7e6a960,Canadian Malartic,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-78.130824,48.122223,POINT (-78.13082 48.12222),...,Quebec,active_facility,None,None,mining,"Open-pit, concentrator",Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,None,None,Wesdome Gold Mines Ltd.,Wesdome Gold Mines Ltd,CMP-3d2c4955,-85.452500,48.110280,POINT (-85.45250 48.11028),...,Ontario,active_facility,None,None,mining,Open-pit,Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...
266,BC-MAIN-feb13c30,Record Ridge,None,None,West High Yield Resources Ltd.,West High Yield Resources Ltd,CMP-1023f9c0,-117.884000,49.082000,POINT (-117.88400 49.08200),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Magnesium,Magnesium,https://open.canada.ca/data/en/dataset/22b2db8...
267,YT-MAIN-5e0d8b48,Casino,None,None,Western Copper and Gold Corporation,Western Copper and Gold Corporation,CMP-2dac9896,-138.833330,62.733330,POINT (-138.83333 62.73333),...,Yukon,project_facility,Active,Advanced project,project,None,None,Copper,"Copper, gold, molybdenum, silver",https://open.canada.ca/data/en/dataset/22b2db8...
268,ON-MAIN-12c68d49,Eagle's Nest,None,None,Wyloo,Wyloo,CMP-65b36728,-86.303800,52.742020,POINT (-86.30380 52.74202),...,Ontario,project_facility,Active,Advanced project,project,None,None,Nickel,"Nickel, copper, gold, platinum, palladium",https://open.canada.ca/data/en/dataset/22b2db8...
269,BC-MAIN-891d3cb5,Akie,None,None,ZincX Resources Corp.,ZincX Resources Corp,CMP-3416049b,-124.865990,57.380880,POINT (-124.86599 57.38088),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, lead, silver",https://open.canada.ca/data/en/dataset/22b2db8...

In [9]:
# For the datasets
tailings_gdf["source_id"] = 'https://tailing.grida.no/'
min_can_gdf["source_id"] = '10.1038/s41597-024-03116-3'
ctrace_gdf["source_id"] = 'Jolleys, M. et al (2024). Mineral Extraction sector: Mining and Quarrying Emissions from Copper, Iron, Bauxite, Rock and Sand, Hypervine, UK, Climate TRACE Emissions Inventory'
conflict_gdf["source_id"] = 'http://journals.librarypublishing.arizona.edu/jpe/article/id/1932/'
ghg_gdf["source_id"] = 'https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions/large-facilities.html'
npri_gdf["source_id"] = 'https://www.canada.ca/en/environment-climate-change/services/national-pollutant-release-inventory/tools-resources-data/exploredata.html' 
prioritization_area_gdf['source_id'] = 'https://doi.org/10.5281/zenodo.5006332'
climate_category_gdf['source_id'] = 'https://doi.org/10.1038/s41597-023-02549-6'
weather_gdf['source_id'] = 'https://climate-scenarios.canada.ca/?page=CanDCS6-indices'
peatland_gdf['source_id'] = 'https://greifswaldmoor.de/global-peatland-database-en.html'
population_gdf['source_id'] = 'https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F40-C41DA8332CFE' 
water_risk_gdf['source_id'] = 'https://www.wri.org/data/aqueduct-global-maps-40-data'
land_cover_gdf['source_id'] = 'https://doi.org/10.5067/MODIS/MCD12Q1.061 + https://doi.org/10.5281/zenodo.7254221'
npv_gdf['source_id'] = 'https://doi.org/10.7717/peerj.5457'
indigenous_can_gdf['source_id'] = 'http://www.landmarkmap.org'
wpda_gdf_polygons['source_id'] = 'https://www.protectedplanet.net'
tang_canada_gdf['source_id'] = 'https://doi.org/10.1038/s43247-023-00805-6'
#maus_canada_gdf['source_id'] = 'https://doi.org/10.1038/s41597-022-01547-4'
li_canada_gdf['source_id'] = 'https://www.nature.com/articles/s41597-025-05296-y'
bth_df['source_id'] = 'https://pubs.acs.org/doi/10.1021/acs.est.4c05293'

In [30]:
from db_creation_function import add_source_id_to_collected_data

In [31]:
production_df = add_source_id_to_collected_data(production_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

tech_attributes_df = add_source_id_to_collected_data(tech_attributes_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

reserves_df = add_source_id_to_collected_data(reserves_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

technosphere_df = add_source_id_to_collected_data(technosphere_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

env_df = add_source_id_to_collected_data(env_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

waste_df = add_source_id_to_collected_data(waste_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

intensity_df = add_source_id_to_collected_data(intensity_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

archetypes_df = add_source_id_to_collected_data(archetypes_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

In [12]:
from db_creation_function import create_source_table_from_datasets

In [13]:
dataset_dict = {
    "Global Tailings Portal": tailings_gdf,
    "A Comprehensive Historical and Geolocalized Database of Mining Activities in Canada": min_can_gdf,
    "ClimateTRACE mineral extraction sector": ctrace_gdf,
    "Environmental Justice Atlas": conflict_gdf,
    "GHG from large facilities": ghg_gdf,
    "National Pollutant Inventory Report (NPRI)": npri_gdf,
    "Areas of global importance for conserving terrestrial biodiversity, carbon and water": prioritization_area_gdf,
    "High-Resolution (1 km) Koppen-Geiger Maps for 1901–2099 Based on Constrained CMIP6 Projections": climate_category_gdf,
    "CMIP6 statistically downscaled climate indices (CanDCS-M6)": weather_gdf,
    "Global Peatland Database": peatland_gdf,
    "Global Human Settlement Layer (GHSL)": population_gdf,
    "Aqueduct 4.0": water_risk_gdf,
    "Modis Land Cover and ESA World Cover": land_cover_gdf,
    "Potential Natural Vegetation (NPV)": npv_gdf,
    "Indigenous Peoples’ and Local Community Lands and Territories": indigenous_can_gdf,
    "World Database on Protected Areas (WDPA)": wpda_gdf_polygons,
    "Global Mining Footprint Mapped from High-Resolution Satellite Imagery": tang_canada_gdf,
    "Machine learning-enhanced monitoring of global copper mining areas": li_canada_gdf,
    "Byproduct-to-Host Ratios for Assessing the Accessibility of Mineral Resources": bth_df,
}

manual_dfs = [production_df, tech_attributes_df, reserves_df, technosphere_df, env_df, waste_df, intensity_df, archetypes_df] 

source_table = create_source_table_from_datasets(dataset_dict, manual_dfs)

In [14]:
source_table

,source_id,source_provenance,source_name
0,https://tailing.grida.no/,dataset,Global Tailings Portal
18,https://pubs.acs.org/doi/10.1021/acs.est.4c05293,dataset,Byproduct-to-Host Ratios for Assessing the Acc...
17,https://www.nature.com/articles/s41597-025-052...,dataset,Machine learning-enhanced monitoring of global...
16,https://doi.org/10.1038/s43247-023-00805-6,dataset,Global Mining Footprint Mapped from High-Resol...
15,https://www.protectedplanet.net,dataset,World Database on Protected Areas (WDPA)
...,...,...,...
98,SRC_BarrickGoldCorporation_Reserves_2024,report,Reserves_2024
99,SRC_BurgundyDiamondMines_2024-Annual-Mineral-R...,report,2024-Annual-Mineral-Resouces-and-Ore-Reserves-...
100,SRC_CamecoCorporation_Reserves_2024,report,Reserves_2024
86,SRC_NewmontCorporation_Operating_statistics_2025,report,Operating_statistics_2025
268,SRC_IAMGOLDCorporation_nan,report,nan

In [14]:
source_table.to_csv(r'database/CSV/sources_table.csv', index=False)

## Substance table

In [15]:
# Get unique substance name and cas number in a new df
npri_substance_df = npri_gdf[['substance_name_npri', 'cas_number']].drop_duplicates().copy()

In [16]:
# Add a type column = 'Group of substances' if the cas_number starts with 'NA' and = 'Substance' if not 
npri_substance_df = npri_substance_df.assign(
    type=lambda x: np.where(x['cas_number'].str.startswith('NA'), 'Group of substances', 'Substance')
)

In [17]:
npri_substance_df.rename(columns={
    'substance_name_npri': 'substance_name',
    'cas_number': 'substance_id',
    'type': 'substance_type'
}, inplace=True)

In [18]:
# Reorganize the columns
npri_substance_df = npri_substance_df[['substance_id', 'substance_type', 'substance_name']].copy()

In [19]:
npri_substance_df

     substance_id       substance_type                substance_name
0         NA - 16  Group of substances               Ammonia (total)
1         NA - 02  Group of substances   Arsenic (and its compounds)
2        630-08-0            Substance               Carbon monoxide
3         NA - 04  Group of substances  Chromium (and its compounds)
4         NA - 05  Group of substances    Cobalt (and its compounds)
...           ...                  ...                           ...
6661     189-64-0            Substance            Dibenzo[a,h]pyrene
7179      71-43-2            Substance       Speciated VOC - Benzene
7677    1332-21-4            Substance  Asbestos (friable form only)
7900    7681-49-4            Substance               Sodium fluoride
8210      NA - 46  Group of substances             Azo disperse dyes

[104 rows x 3 columns]

In [20]:
env_substance_df = env_df[['substance_type', 'substance_name', 'cas_number']].drop_duplicates().copy()

In [21]:
env_substance_df = env_substance_df.dropna(how='all').copy()

In [22]:
env_substance_df.rename(columns={'cas_number': 'substance_id'}, inplace=True)

In [23]:
# Reorganize the columns
env_substance_df = env_substance_df[['substance_id', 'substance_type', 'substance_name']].copy()

In [24]:
# Put the two dataframes together
substance_table = pd.concat([npri_substance_df, env_substance_df], ignore_index=True).drop_duplicates().reset_index(drop=True)

In [25]:
substance_table

         substance_id       substance_type                substance_name
0             NA - 16  Group of substances               Ammonia (total)
1             NA - 02  Group of substances   Arsenic (and its compounds)
2            630-08-0            Substance               Carbon monoxide
3             NA - 04  Group of substances  Chromium (and its compounds)
4             NA - 05  Group of substances    Cobalt (and its compounds)
..                ...                  ...                           ...
120  NA - Particulate  Group of substances                   Particulate
121           NA - 02            Substance                       Arsenic
122           NA - 12  Group of substances                      Selenium
123          NA - NOx  Group of substances           NOx (excluding NO2)
124        10102-44-0            Substance                           NO2

[125 rows x 3 columns]

In [26]:
# For CTrace and GHG datasets, put the substance_id as 'NA - GHG'
ctrace_gdf['substance_id'] = 'NA - GHG'
ghg_gdf['substance_id'] = 'NA - GHG'

In [27]:
substance_table.to_csv(r'database/CSV/substances_table_new.csv', index=False)

## Compartment table

In [28]:
npri_gdf['emission_type'] = npri_gdf['emission_type'].replace({
    'Air Emissions / Émissions à l\'air': 'Air',
    'Water Releases / Rejets à l\'eau': 'Water',
    'Land Releases /  Rejets au sol': 'Land',
    'On-Site Disposal / Élimination sur le site': 'On-Site Disposal',
    'Off-Site Disposal / Élimination hors site': 'Off-Site Disposal',
    'Transfers for Treatment / Transferts pour traitement': 'Transfers for Treatment',
    'Transfers for Recycling / Transferts pour recyclage': 'Transfers for Recycling',
})

In [29]:
npri_gdf['emission_subtype'] = npri_gdf['emission_subtype'].replace({
    'Receiving Waterbody (French)': 'Waterbody',
    'Receiving Waterbody (English)': 'Waterbody',})

In [30]:
# Differentiate between biosphere and technosphere compartments
biosphere = ["Air", "Water", 'Land']
technosphere = ['On-Site Disposal', 'Off-Site Disposal', 'Transfers for Treatment', 'Transfers for Recycling']
                            
pollutant_npri_gdf = npri_gdf[npri_gdf['emission_type'].isin(biosphere)].copy()
waste_npri_gdf = npri_gdf[npri_gdf['emission_type'].isin(technosphere)].copy()

In [31]:
pollutant_npri_gdf.rename(columns={
    'emission_type': 'compartment_name',
    'emission_subtype': 'release_pathway'
}, inplace=True)

In [32]:
# Get unique substance name and cas number in a new df
npri_compartment_df = pollutant_npri_gdf[['compartment_name']].drop_duplicates().copy().reset_index(drop=True)

In [33]:
env_compartment_df = env_df[['compartment_name']].drop_duplicates().copy().reset_index(drop=True)

In [34]:
compartment_table = pd.concat([npri_compartment_df, env_compartment_df], ignore_index=True).drop_duplicates().reset_index(drop=True)

In [35]:
compartment_table

  compartment_name
0              Air
1            Water
2             Land

In [36]:
import hashlib
import pandas as pd

def assign_deterministic_id(df, prefix, columns, id_column):
    """
    Assign deterministic IDs based on one or more string columns.

    Parameters:
        df (pd.DataFrame): The DataFrame to modify.
        prefix (str): Prefix for the ID (e.g., 'CMP').
        columns (list): List of column names to combine and hash.
        id_column (str): Name of the new ID column.

    Returns:
        pd.DataFrame: Updated DataFrame with the new ID column.
    """
    def generate_id(row):
        key = '|'.join(str(row[col]).strip().lower() for col in columns)
        return f"{prefix}{hashlib.md5(key.encode()).hexdigest()[:8]}"
    
    df[id_column] = df.apply(generate_id, axis=1)
    return df

In [37]:
compartment_table = assign_deterministic_id(
    compartment_table,
    prefix="comp",
    columns=["compartment_name"],
    id_column="compartment_id"
)

In [38]:
compartment_table

  compartment_name compartment_id
0              Air   comp3c458811
1            Water   comp9460370b
2             Land   comp87cf962b

In [39]:
compartment_table.to_csv(r'database/CSV/compartments_table_new_new.csv', index=False)

### Assign compartment_id to the relevant datasets

In [40]:
pollutant_npri_gdf = pollutant_npri_gdf.merge(
    compartment_table[['compartment_id', 'compartment_name']],
    how='left',
    on=['compartment_name']
)

In [41]:
env_df = env_df.merge(
    compartment_table[['compartment_id', 'compartment_name']],
    how='left',
    on=['compartment_name']
)

In [42]:
# For CTrace and GHG datasets, we assign the compartment_id corresponding to 'Air' and 'Unspecified' pathway
# For land occupation datasets, we will assign the compartment_id corresponding to 'Land' and 'Unspecified' pathway
ctrace_gdf['compartment_id'] = 'comp3c458811'
ghg_gdf['compartment_id'] = 'comp3c458811'
li_canada_gdf['compartment_id']= 'comp87cf962b'
tang_canada_gdf['compartment_id'] = 'comp87cf962b'

# Matching

## Point to point matching

In [43]:
from matching_functions import match_facilities, one_to_many_relationships

### CMMI

In [ ]:
cmmi_gdf

In [ ]:
# Drop all columns finishing with PPM or PPB + 'SAMPLE_TYP' and 'SAMPLING_M' columns 
cmmi_gdf = cmmi_gdf.loc[:, ~cmmi_gdf.columns.str.endswith(('PPM', 'PPB', 'SAMPLE_TYP', 'EARTH_MAT0', 'EARTH_MAT1', 'SAMPLING_M'))].copy()

In [ ]:
# + drop duplicate rows
cmmi_gdf = cmmi_gdf.drop_duplicates().copy()

In [ ]:
cmmi_gdf

In [ ]:
cmmi_gdf.to_csv(r'cmmi_gdf.csv', index=False)

In [ ]:
lt_main_cmmi = match_facilities(main_gdf, cmmi_gdf,
                     id_col1='main_id', id_col2='DEPOSIT_UI',
                     name_col1='facility_name', name_col2='DEPOSIT_NA'
                     )

In [ ]:
lt_main_cmmi

In [ ]:
lt_main_cmmi.to_csv(r'lt_main_cmmi.csv', index=False)

In [ ]:
matches_main_cmmi = one_to_many_relationships(
    lt_main_cmmi,
    id_main_col='main_id',
    id_sat_col='DEPOSIT_UI',
    distance_threshold_m=2000,
    similarity_threshold=80,
    similarity_metric="token_set"  
)

In [ ]:
matches_main_cmmi

### MinCan

In [44]:
# Let's keep only Active mines
min_can_gdf = min_can_gdf[min_can_gdf['mine_status'] == 'Active'].copy()

Some mines in MinCan dataset have very slightly different name (e.g. LaRonde - Zone 5 and LaRonde), the same name but one without town (e.g. Detour Lake) or several companies for the same mines.

In [45]:
# min_can_id = ON-MINCAN-6316d452 = Detour Lake = 2013 - open
# min_can_id = ON-MINCAN-7b832414 = Detour Lake = 1983 - open
# min_can_id = QC-MINCAN-775312a1 = LaRonde - Zone 5 = 2018 - open
# min_can_id = QC-MINCAN-8321e85e = LaRonde = 1988 - open

In [46]:
# We delete the duplicates, aligned with information from MDO for Detour Lake and LaRonde
min_can_gdf = min_can_gdf[~min_can_gdf['mincan_id'].isin(['ON-MINCAN-6316d452', 'QC-MINCAN-775312a1'])].copy()

In [47]:
min_can_gdf

,mincan_id,namemine,town,province,latitude,longitude,commodityall,information,mine_status,geometry,operation_periods,source_id
7,ON-MINCAN-ccf2bf99,Haley,Haley,Ontario,45.598880,-76.751710,Magnesium,None,Active,POINT (-76.75171 45.59888),1942–open,10.1038/s41597-024-03116-3
13,NB-MINCAN-63ccd128,Stratmat (Halfmile),None,New Brunswick,47.305278,-66.320000,"Zinc, Lead, Copper, Gold, Silver",indigenous participation,Active,POINT (-66.32000 47.30528),1951–open,10.1038/s41597-024-03116-3
18,ON-MINCAN-9abb16ea,Calcite Division,Perth,Ontario,45.149689,-76.498756,Calcium Carbonate,None,Active,POINT (-76.49876 45.14969),1962–open,10.1038/s41597-024-03116-3
23,QC-MINCAN-06b1f129,Parent Mica Deposit,Suzor,Quebec,47.938412,-74.634602,Mica,"Changed name in Lacana Mines Inc. ""In late 198...",Active,POINT (-74.63460 47.93841),1976–open,10.1038/s41597-024-03116-3
24,QC-MINCAN-227d3d18,Charlevoix,Charlevoix (Saint-Urbain),Quebec,47.749900,-70.696711,Silica,None,Active,POINT (-70.69671 47.74990),1977–open,10.1038/s41597-024-03116-3
...,...,...,...,...,...,...,...,...,...,...,...,...
923,BC-MINCAN-d8cf3b3a,None,Fort Langley,British Columbia,49.189659,-122.660599,Lime,None,Active,POINT (-122.66060 49.18966),1991–open,10.1038/s41597-024-03116-3
924,AB-MINCAN-bab4efd2,None,Exshaw,Alberta,51.071389,-115.135199,Lime,None,Active,POINT (-115.13520 51.07139),1991–open,10.1038/s41597-024-03116-3
927,SK-MINCAN-2aefa179,None,Hudson Bay,Saskatchewan,52.985830,-101.744038,Silica,small scale /// Lower Cretaceous Mannville Gro...,Active,POINT (-101.74404 52.98583),1993–open,10.1038/s41597-024-03116-3
935,NT-MINCAN-ea720725,Panda (Ekati Project),Lac de Gras,Northwest Territories,64.716667,-110.608333,Diamond,Brief closure between 2020 and 2021,Active,POINT (-110.60833 64.71667),1997–open,10.1038/s41597-024-03116-3
936,QC-MINCAN-8f0f7e05,Ardorbec,Danville,Quebec,45.748462,-71.961305,Magnesium,None,Active,POINT (-71.96130 45.74846),1998–open,10.1038/s41597-024-03116-3

In [48]:
lt_main_mincan = match_facilities(main_gdf, min_can_gdf,
                     id_col1='main_id', id_col2='mincan_id',
                     name_col1='facility_name', name_col2='namemine'
                     )

In [49]:
lt_main_mincan.to_csv(r'data/Mappings/LT/lt_main_mincan.csv', index=False)

In [67]:
matches_main_mincan = one_to_many_relationships(
    lt_main_mincan,
    id_main_col='main_id',
    id_sat_col='mincan_id',
    distance_threshold_m=2000,
    similarity_threshold=80,
    similarity_metric="token_set"  
)

In [68]:
min_can_gdf = min_can_gdf.merge(
    matches_main_mincan,
    on="mincan_id", 
    how="left"
)

In [69]:
# For SQL
min_can_gdf = min_can_gdf[min_can_gdf["main_id"].notna()].copy()

In [70]:
col_to_keep = ["mincan_id", "main_id", "mine_status", "operation_periods"]
min_can_gdf = min_can_gdf[col_to_keep]
min_can_gdf

,mincan_id,main_id,mine_status,operation_periods
11,QC-MINCAN-494c7715,QC-MAIN-9de9bb0d,Active,1936–1996; 2005–2013; 2021–open
21,BC-MINCAN-8cc41b53,BC-MAIN-6b4800fe,Active,1972–1998; 2004–open
28,QC-MINCAN-8321e85e,QC-MAIN-e51eda66,Active,1988–open
29,ON-MINCAN-97f916de,ON-MAIN-c5fefb01,Active,2002–open
31,ON-MINCAN-49811fe2,ON-MAIN-687b8c8d,Active,2007–open
34,QC-MINCAN-44904232,QC-MAIN-c0660aec,Active,2008–2011; 2013–open
39,NU-MINCAN-1d9e43a7,NU-MAIN-730aefe3,Active,2010–open
41,ON-MINCAN-643672f4,ON-MAIN-f3e6ff08,Active,2011–open
42,SK-MINCAN-5ac4b2dd,SK-MAIN-22ce14be,Active,2011–open
44,BC-MINCAN-72fabc94,BC-MAIN-aa76f6f2,Active,2012–open
47,MB-MINCAN-15965632,MB-MAIN-be5b3dc8,Active,2013–open
48,ON-MINCAN-07ece30d,ON-MAIN-28f3f0fc,Active,2014–open
51,BC-MINCAN-4eaf1f96,BC-MAIN-ed23117f,Active,2014–open
53,QC-MINCAN-1c16c912,QC-MAIN-6dc537e6,Active,2015–open
54,BC-MINCAN-496a2682,BC-MAIN-8eb8be0d,Active,2015–open
55,SK-MINCAN-7501c939,SK-MAIN-91cf5448,Active,2015–open
56,QC-MINCAN-72adc1b6,QC-MAIN-3032c251,Active,2016–open
57,NS-MINCAN-21b5fbce,NS-MAIN-c9c77a59,Active,2017–open
58,ON-MINCAN-ddd10f1c,ON-MAIN-0aadf28f,Active,2017–open
60,BC-MINCAN-492cfeba,BC-MAIN-857b7b89,Active,2017–open
61,NT-MINCAN-ecb9b239,NT-MAIN-94e652a5,Active,2017–open
64,ON-MINCAN-079b81a1,ON-MAIN-f4fc3276,Active,2018–open
66,ON-MINCAN-b94b1f25,ON-MAIN-1c674cd0,Active,2019–open
68,QC-MINCAN-a6cbac08,QC-MAIN-b8c826a2,Active,2019–open
69,NU-MINCAN-6ca88e12,NU-MAIN-8b0264c9,Active,2019–open
70,YT-MINCAN-8fada64a,YT-MAIN-e05ed9fe,Active,2019–open
71,NU-MINCAN-4efe1cae,NU-MAIN-4ea8ac9d,Active,2019–open
80,NL-MINCAN-d8d4cf69,NL-MAIN-2d8801d6,Active,2005–open
84,QC-MINCAN-6f83c124,QC-MAIN-e7e6a960,Active,1935–1965; 2011–open
87,QC-MINCAN-a6163f93,QC-MAIN-d29e0839,Active,1956–1959; 1974–1975; 1988–open
91,QC-MINCAN-548f03a9,QC-MAIN-084bd95c,Active,1976–open
92,QC-MINCAN-cf418fe9,QC-MAIN-b86f7d07,Active,1988–1991; 1993–open
95,QC-MINCAN-a90e8433,QC-MAIN-a97821c0,Active,1998–open
102,BC-MINCAN-14ce4b06,BC-MAIN-599152a0,Active,1884–1958; 2011–open
103,ON-MINCAN-8c35080f,ON-MAIN-7607a50e,Active,1917–1957; 2010–open
104,ON-MINCAN-838ef03f,ON-MAIN-206041d1,Active,1962–1991; 2007–2009; 2010–open
105,BC-MINCAN-595f5049,BC-MAIN-23155c25,Active,1966–1985; 2002–2015; 2019–open
114,ON-MINCAN-cf9a5c80,ON-MAIN-1f126a43,Active,1933–1999; 2002–open
125,QC-MINCAN-13530c4c,QC-MAIN-649d2873,Active,1976–open
130,ON-MINCAN-1c3b8f14,ON-MAIN-cb85213a,Active,1983–open
132,ON-MINCAN-7b832414,ON-MAIN-aeafbb59,Active,1983–open
140,ON-MINCAN-69e999a0,ON-MAIN-fefeaee4,Active,1997–open
143,ON-MINCAN-fc444118,ON-MAIN-7f050560,Active,1949–open
149,ON-MINCAN-08e05315,ON-MAIN-f8313ebd,Active,1963–open
157,ON-MINCAN-7b29d7b3,ON-MAIN-bfbcd72e,Active,1987–1994; 2012–open

### CTrace

In [71]:
lt_main_ctrace = match_facilities(main_gdf, ctrace_gdf,
                     id_col1='main_id', id_col2='ctrace_id',
                     name_col1='facility_name', name_col2='source_name'
                     )

In [72]:
lt_main_ctrace.to_csv(r'data/Mappings/LT/lt_main_ctrace.csv', index=False)

In [73]:
# matches_main_ctrace = one_to_many_relationships(
#     lt_main_ctrace,
#     id_main_col='main_id',
#     id_sat_col='ctrace_id',
#     distance_threshold_m=2000,
#     similarity_threshold=80,
#     similarity_metric="token_set"
# )
matches_main_ctrace = pd.read_excel(r'data/Mappings/mapping_ctrace.xlsx', sheet_name='mapping')

In [74]:
matches_main_ctrace

    ctrace_id           main_id
0     1754077  QC-MAIN-e51eda66
1     1754071  BC-MAIN-e34feb4d
2     1754084  BC-MAIN-ed23117f
3     1754082  NL-MAIN-c139de6d
4     1754067  QC-MAIN-30c1828c
5    25486533  ON-MAIN-f8313ebd
6     1754096  QC-MAIN-a97821c0
7     1754102  ON-MAIN-40ce0593
8     1754057  BC-MAIN-599152a0
9    25486534  ON-MAIN-a3c56a83
10    1754085  BC-MAIN-3f490561
11    1754081  ON-MAIN-7001a391
12    1754083  YT-MAIN-752fbcae
13    1754087  BC-MAIN-aa76f6f2
14    1754097  BC-MAIN-8eb8be0d
15   36395102  NL-MAIN-b64bae7a
16   36395102  NL-MAIN-18695c6d
17    1754061  BC-MAIN-6b4800fe
18    1754066  BC-MAIN-bf503b6b
19    1754086  BC-MAIN-23155c25
20    1754105  QC-MAIN-b2148882
21    1754055  ON-MAIN-6e9b2449
22    1754058  ON-MAIN-52224e1e
23    1754060  ON-MAIN-48fe2205
24    1754104  ON-MAIN-28f3f0fc
25    1754056  ON-MAIN-f080c409
26    1754103  MB-MAIN-e0a6250e
27    1754106  NL-MAIN-2d8801d6
28    1754075  MB-MAIN-be5b3dc8

In [75]:
ctrace_gdf = ctrace_gdf.merge(
    matches_main_ctrace,
    on="ctrace_id", 
    how="left"
)

In [76]:
# For SQL
ctrace_gdf = ctrace_gdf[ctrace_gdf["main_id"].notna()].copy()

In [77]:
col_to_keep = [
'ctrace_id', 
'year',
'emissions_quantity', 
'gas',
'activity', 'activity_units', 
'capacity', 'capacity_units', 
'source_id',  'substance_id', 'compartment_id',
'main_id'           
]
ctrace_gdf = ctrace_gdf[col_to_keep]
ctrace_gdf

,ctrace_id,year,emissions_quantity,gas,activity,activity_units,capacity,capacity_units,source_id,substance_id,compartment_id,main_id
6,1754055,2023,5.610000e+03,co2e_100yr,8.630000e+05,t of copper ore,4.624000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449
7,1754056,2023,6.403000e+03,co2e_100yr,9.850000e+05,t of copper ore,3.554700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409
8,1754057,2023,2.299160e+05,co2e_100yr,1.457500e+07,t of copper ore,3.670000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0
9,1754058,2023,2.639000e+03,co2e_100yr,4.060000e+05,t of copper ore,1.104100e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e
11,1754060,2023,4.225000e+03,co2e_100yr,6.500000e+05,t of copper ore,4.822000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205
12,1754061,2023,1.316380e+05,co2e_100yr,8.810000e+07,t of copper ore,6.450000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-6b4800fe
16,1754066,2023,2.412130e+06,co2e_100yr,7.288600e+07,t of copper ore,2.631000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-30c1828c
21,1754071,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,1.073810e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-e34feb4d
23,1754075,2023,2.408400e+04,co2e_100yr,1.526729e+06,t of copper ore,1.357000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-be5b3dc8
25,1754077,2023,6.711600e+04,co2e_100yr,1.501481e+06,t of copper ore,1.988200e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-e51eda66
29,1754081,2023,7.782000e+03,co2e_100yr,5.279710e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,7.413000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,2.313000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,YT-MAIN-752fbcae
32,1754084,2023,7.956600e+04,co2e_100yr,2.127800e+07,t of copper ore,2.500250e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-ed23117f
33,1754085,2023,7.137900e+04,co2e_100yr,5.948239e+06,t of copper ore,4.902900e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-3f490561
34,1754086,2023,5.400000e+02,co2e_100yr,4.500000e+04,t of copper ore,4.110000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-23155c25
35,1754087,2023,1.590800e+04,co2e_100yr,2.993000e+06,t of copper ore,3.408700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-aa76f6f2
43,1754096,2023,8.219000e+03,co2e_100yr,6.848790e+05,t of copper ore,1.500000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-a97821c0
44,1754097,2023,8.451100e+04,co2e_100yr,6.887709e+06,t of copper ore,4.549000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-8eb8be0d
49,1754102,2023,1.593900e+04,co2e_100yr,1.431680e+06,t of copper ore,1.690000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-40ce0593
50,1754103,2023,4.433000e+03,co2e_100yr,6.820000e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-e0a6250e
51,1754104,2023,3.367000e+03,co2e_100yr,5.180000e+05,t of copper ore,2.453000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-b2148882
53,1754106,2023,1.144000e+04,co2e_100yr,1.760000e+06,t of copper ore,3.110000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-2d8801d6
54,25486533,2023,1.620000e+04,co2e_100yr,1.350000e+06,t of copper ore,2.500000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f8313ebd
55,25486534,2023,5.914500e+04,co2e_100yr,3.798000e+06,t of copper ore,2.200000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-a3c56a83
56,36395102,2023,5.760720e+05,co2e_100yr,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-b64bae7a
57,36395102,2023,5.760720e+05,co2e_100yr,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-18695c6d

In [78]:
# We separate emissions and production data
ctrace_ghg_gdf = ctrace_gdf.drop(columns=['activity', 'activity_units', 'capacity', 'capacity_units'])
ctrace_prod_gdf = ctrace_gdf.drop(columns=['emissions_quantity', 'gas'])

### Conflict

In [ ]:
lt_main_conflict = match_facilities(main_gdf, conflict_gdf,
                     id_col1='main_id', id_col2='ej_atlas_id',
                     name_col1='facility_name', name_col2='facility_name_ejatlas'
                     )

In [ ]:
matches_main_conflict = one_to_many_relationships(
    lt_main_conflict,
    id_main_col='main_id',
    id_sat_col='ej_atlas_id',
    distance_threshold_m=20000,
    similarity_threshold=80,
    similarity_metric="token_set"  # "partial" or "token_set"
)

In [ ]:
conflict_gdf = conflict_gdf.merge(
    matches_main_conflict,
    on="ej_atlas_id",  
    how="left"
)

In [ ]:
# For SQL
conflict_gdf = conflict_gdf[conflict_gdf["main_id"].notna()].copy()

In [ ]:
col_to_keep = ["ej_atlas_id",
  "main_id",
  "case_name",
  "start_date",
  "end_date",
  "conflict_description",
  "conflict_details",
  "population_affected",
  "conflict_intensity",
  "project_status",
  "source_id"             
               ]
conflict_gdf = conflict_gdf[col_to_keep]
conflict_gdf

### Tailings

In [79]:
lt_main_tailings = match_facilities(main_gdf, tailings_gdf,
                     id_col1='main_id', id_col2='tailing_id',
                     name_col1='facility_name', name_col2='related_mine'
                     )

In [81]:
lt_main_tailings.to_csv(r'data/Mappings/LT/lt_main_tailings.csv', index=False)

In [82]:
# matches_main_tailings = one_to_many_relationships(
#     lt_main_tailings,
#     id_main_col='main_id',
#     id_sat_col='tailing_id',
#     distance_threshold_m=20000,
#     similarity_threshold=80,
#     similarity_metric="token_set"  # "partial" or "token_set"
# )
matches_main_tailings = pd.read_excel(r'data/Mappings/mapping_tailing.xlsx', sheet_name='mapping')

In [83]:
tailings_gdf = tailings_gdf.merge(
    matches_main_tailings,
    on="tailing_id",  
    how="left"
)

In [84]:
# For SQL
tailings_gdf = tailings_gdf[tailings_gdf["main_id"].notna()].copy()

In [85]:
col_to_keep = [
  "row_id",
  "main_id",
  "year",
  "tailing_id",
  "tsf_name",
  "status",
  "construction_year",
  "raise_type",
  "current_maximum_height",
  "current_tailings_storage",
  "planned_storage_5_years",
  "hazard_categorization",
  "classification_system",
  "geometry", 
  "source_id"             
               ]
tailings_gdf = tailings_gdf[col_to_keep]
tailings_gdf

,row_id,main_id,year,tailing_id,tsf_name,status,construction_year,raise_type,current_maximum_height,current_tailings_storage,planned_storage_5_years,hazard_categorization,classification_system,geometry,source_id
0,TAIL-12.0-2019-1,NU-MAIN-730aefe3,2019,12.0,North Cell,Active,2009.0,"Downstream, Upstream",31.0,14400000,14400000,Medium,Canadian Dam Association,POINT (-96.04333 65.02156),https://tailing.grida.no/
1,TAIL-13.0-2019-1,NU-MAIN-730aefe3,2019,13.0,South Cell,Active,2012.0,Downstream,49.0,10420000,10420000,Medium,Canadian Dam Association,POINT (-96.03339 65.01378),https://tailing.grida.no/
2,TAIL-14.0-2019-1,NU-MAIN-730aefe3,2019,14.0,In pit,Active,2009.0,None,NaN,850000,850000,Low,None,POINT (-96.03254 65.00190),https://tailing.grida.no/
3,TAIL-15.0-2019-1,NU-MAIN-8b0264c9,2019,15.0,Meliadine TSF,Active,2019.0,None,5.0,89000,89000,Medium,Canadian Dam Association,POINT (-92.14034 63.02083),https://tailing.grida.no/
4,TAIL-16.0-2019-1,QC-MAIN-c0660aec,2019,16.0,South TSF,Active,2007.0,Not Raised,5.0,1664000,1664000,Medium,Canadian Dam Association,POINT (-77.84198 48.05434),https://tailing.grida.no/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,TAIL-1128.0-2019-1,ON-MAIN-f080c409,2019,1128.0,R3 Tailings,Active,1985.0,Compacted\nOuter Shell,27.0,39000000,39000000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
224,TAIL-1128.0-2019-1,ON-MAIN-63b394c3,2019,1128.0,R3 Tailings,Active,1985.0,Compacted\nOuter Shell,27.0,39000000,39000000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
225,TAIL-1129.0-2019-1,ON-MAIN-f080c409,2019,1129.0,R4 Tailings,Active,1990.0,Compacted\nOuter Shell,22.0,59000000,59000000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
226,TAIL-1129.0-2019-1,ON-MAIN-63b394c3,2019,1129.0,R4 Tailings,Active,1990.0,Compacted\nOuter Shell,22.0,59000000,59000000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
234,TAIL-1243.0-2019-1,QC-MAIN-e7e6a960,2019,1243.0,Canadian Malartic TSF,Active,2012.0,Upstream,40.0,96000000,96000000,Medium to High,CDA/Yamana,POINT (-78.10361 48.11139),https://tailing.grida.no/

### GHG

In [86]:
lt_main_ghg = match_facilities(main_gdf, ghg_gdf,
                     id_col1='main_id', id_col2='ghg_id',
                     name_col1='facility_name', name_col2='facility_name_ghg'
                     )

In [87]:
lt_main_ghg.to_csv(r'data/Mappings/LT/lt_main_ghg.csv', index=False)

In [88]:
# matches_main_ghg = one_to_many_relationships(
#     lt_main_ghg,
#     id_main_col='main_id',
#     id_sat_col='ghg_id',
#     distance_threshold_m=10000,
#     similarity_threshold=80,
#     similarity_metric="token_set"  # "partial" or "token_set"
# )
matches_main_ghg = pd.read_excel(r'data/Mappings/mapping_ghg.xlsx', sheet_name='mapping')

In [89]:
ghg_gdf = ghg_gdf.merge(
    matches_main_ghg,
    on="ghg_id",  
    how="left"
)

In [90]:
# For SQL
ghg_gdf = ghg_gdf[ghg_gdf["main_id"].notna()].copy()

In [91]:
col_to_keep = [
  "row_id",
  "main_id",
  "year",
  "value",
  "unit",
  "compartment_id",
  "substance_id",
  "source_id"             
               ]
ghg_gdf = ghg_gdf[col_to_keep]
ghg_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
0,GHG-10052-2023-1,NL-MAIN-dd723db4,2023,780.52,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
1,GHG-10101-2023-1,NT-MAIN-6c1d6ee6,2023,170.09,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
3,GHG-10188-2023-1,QC-MAIN-084bd95c,2023,274.90,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
5,GHG-10240-2023-1,QC-MAIN-a97821c0,2023,158.00,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
6,GHG-10299-2023-1,QC-MAIN-e25eed27,2023,804.49,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
138,GHG-11730-2023-1,QC-MAIN-92628f16,2023,406.65,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
141,GHG-11765-2023-1,ON-MAIN-4c35e094,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
142,GHG-11765-2023-1,ON-MAIN-020a683c,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
144,GHG-11989-2023-1,QC-MAIN-1eee4ace,2023,952.95,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
146,GHG-12298-2023-1,ON-MAIN-63b394c3,2023,325.43,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...

### NPRI - pollutants

In [92]:
pollutant_npri_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,cas_number,substance_name_npri,substance_unit,compartment_name,release_pathway,value,source_id,geometry,compartment_id
0,npri-1568-2023-1,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 16,Ammonia (total),tonnes,Air,Stack Emissions,0.636,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811
1,npri-1568-2023-2,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 02,Arsenic (and its compounds),kg,Air,Stack Emissions,0.116,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811
2,npri-1568-2023-3,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,630-08-0,Carbon monoxide,tonnes,Air,Stack Emissions,76.208,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811
3,npri-1568-2023-4,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 04,Chromium (and its compounds),tonnes,Air,Stack Emissions,0.00105,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811
4,npri-1568-2023-5,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 05,Cobalt (and its compounds),kg,Air,Stack Emissions,0.18,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6572,npri-2740-2023-108,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 03,Cadmium (and its compounds),kg,Land,Other,0.01,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b
6573,npri-2740-2023-109,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 05,Cobalt (and its compounds),kg,Land,Other,0.1503,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b
6574,npri-2740-2023-110,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 08,Lead (and its compounds),kg,Land,Other,0.256,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b
6575,npri-2740-2023-111,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 12,Selenium (and its compounds),kg,Land,Other,0.0802,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b
6576,npri-2740-2023-112,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 14,Zinc (and its compounds),tonnes,Land,Other,0.0197,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b

In [93]:
lt_main_pollution = match_facilities(main_gdf, pollutant_npri_gdf,
                     id_col1='main_id', id_col2='npri_id',
                     name_col1='facility_name', name_col2='facility_name_npri'
                     )

In [94]:
lt_main_pollution.to_csv(r'data/Mappings/LT/lt_main_pollution.csv', index=False)

In [95]:
# matches_main_pollution = one_to_many_relationships(
#     lt_main_pollution,
#     id_main_col='main_id',
#     id_sat_col='npri_id',
#     distance_threshold_m=10000,
#     similarity_threshold=80,
#     similarity_metric="token_set"  # "partial" or "token_set"
# )
matches_main_pollution = pd.read_excel(r'data/Mappings/mapping_npri.xlsx', sheet_name='mapping')

In [96]:
pollutant_npri_gdf = pollutant_npri_gdf.merge(
    matches_main_pollution,
    on="npri_id",  
    how="left"
)

In [97]:
pollutant_npri_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,cas_number,substance_name_npri,substance_unit,compartment_name,release_pathway,value,source_id,geometry,compartment_id,main_id
0,npri-1568-2023-1,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 16,Ammonia (total),tonnes,Air,Stack Emissions,0.636,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
1,npri-1568-2023-2,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 02,Arsenic (and its compounds),kg,Air,Stack Emissions,0.116,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
2,npri-1568-2023-3,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,630-08-0,Carbon monoxide,tonnes,Air,Stack Emissions,76.208,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
3,npri-1568-2023-4,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 04,Chromium (and its compounds),tonnes,Air,Stack Emissions,0.00105,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
4,npri-1568-2023-5,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 05,Cobalt (and its compounds),kg,Air,Stack Emissions,0.18,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6604,npri-2740-2023-108,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 03,Cadmium (and its compounds),kg,Land,Other,0.01,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6605,npri-2740-2023-109,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 05,Cobalt (and its compounds),kg,Land,Other,0.1503,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6606,npri-2740-2023-110,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 08,Lead (and its compounds),kg,Land,Other,0.256,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6607,npri-2740-2023-111,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 12,Selenium (and its compounds),kg,Land,Other,0.0802,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6608,npri-2740-2023-112,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 14,Zinc (and its compounds),tonnes,Land,Other,0.0197,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3

In [98]:
pollutant_npri_gdf.rename(columns={'cas_number': 'substance_id'}, inplace=True)

In [99]:
# For SQL
pollutant_npri_gdf = pollutant_npri_gdf[pollutant_npri_gdf["main_id"].notna()].copy()

In [100]:
pollutant_npri_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,substance_id,substance_name_npri,substance_unit,compartment_name,release_pathway,value,source_id,geometry,compartment_id,main_id
0,npri-1568-2023-1,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 16,Ammonia (total),tonnes,Air,Stack Emissions,0.636,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
1,npri-1568-2023-2,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 02,Arsenic (and its compounds),kg,Air,Stack Emissions,0.116,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
2,npri-1568-2023-3,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,630-08-0,Carbon monoxide,tonnes,Air,Stack Emissions,76.208,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
3,npri-1568-2023-4,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 04,Chromium (and its compounds),tonnes,Air,Stack Emissions,0.00105,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
4,npri-1568-2023-5,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 05,Cobalt (and its compounds),kg,Air,Stack Emissions,0.18,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),comp3c458811,ON-MAIN-1f126a43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6604,npri-2740-2023-108,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 03,Cadmium (and its compounds),kg,Land,Other,0.01,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6605,npri-2740-2023-109,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 05,Cobalt (and its compounds),kg,Land,Other,0.1503,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6606,npri-2740-2023-110,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 08,Lead (and its compounds),kg,Land,Other,0.256,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6607,npri-2740-2023-111,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 12,Selenium (and its compounds),kg,Land,Other,0.0802,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3
6608,npri-2740-2023-112,2023,2740,EVRAZ Inc NA Canada - Regina Facilities,None,manufacturing,-104.63010,50.51760,Prairie,Nelson River Drainage Area,NA - 14,Zinc (and its compounds),tonnes,Land,Other,0.0197,https://www.canada.ca/en/environment-climate-c...,POINT (-104.63010 50.51760),comp87cf962b,SK-MAIN-26b9aaf3

In [101]:
col_to_keep = [
  "row_id",
  #"npri_id",
  "main_id",
  "year",
  "value",
  "substance_unit",
  "compartment_id",
  "substance_id",
  "release_pathway",  
  "source_id"
 ]
pollutant_npri_gdf = pollutant_npri_gdf[col_to_keep]
pollutant_npri_gdf.rename(columns={'substance_unit': 'unit'}, inplace=True)
pollutant_npri_gdf

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_29444\364978914.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pollutant_npri_gdf.rename(columns={'substance_unit': 'unit'}, inplace=True)

,row_id,main_id,year,value,unit,compartment_id,substance_id,release_pathway,source_id
0,npri-1568-2023-1,ON-MAIN-1f126a43,2023,0.636,tonnes,comp3c458811,NA - 16,Stack Emissions,https://www.canada.ca/en/environment-climate-c...
1,npri-1568-2023-2,ON-MAIN-1f126a43,2023,0.116,kg,comp3c458811,NA - 02,Stack Emissions,https://www.canada.ca/en/environment-climate-c...
2,npri-1568-2023-3,ON-MAIN-1f126a43,2023,76.208,tonnes,comp3c458811,630-08-0,Stack Emissions,https://www.canada.ca/en/environment-climate-c...
3,npri-1568-2023-4,ON-MAIN-1f126a43,2023,0.00105,tonnes,comp3c458811,NA - 04,Stack Emissions,https://www.canada.ca/en/environment-climate-c...
4,npri-1568-2023-5,ON-MAIN-1f126a43,2023,0.18,kg,comp3c458811,NA - 05,Stack Emissions,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...,...
6604,npri-2740-2023-108,SK-MAIN-26b9aaf3,2023,0.01,kg,comp87cf962b,NA - 03,Other,https://www.canada.ca/en/environment-climate-c...
6605,npri-2740-2023-109,SK-MAIN-26b9aaf3,2023,0.1503,kg,comp87cf962b,NA - 05,Other,https://www.canada.ca/en/environment-climate-c...
6606,npri-2740-2023-110,SK-MAIN-26b9aaf3,2023,0.256,kg,comp87cf962b,NA - 08,Other,https://www.canada.ca/en/environment-climate-c...
6607,npri-2740-2023-111,SK-MAIN-26b9aaf3,2023,0.0802,kg,comp87cf962b,NA - 12,Other,https://www.canada.ca/en/environment-climate-c...
6608,npri-2740-2023-112,SK-MAIN-26b9aaf3,2023,0.0197,tonnes,comp87cf962b,NA - 14,Other,https://www.canada.ca/en/environment-climate-c...

### Li et al land occupation

In [ ]:
# li_canada_gdf_copy = li_canada_gdf.copy()
# li_canada_gdf_copy.rename(columns={'geometry': 'geometry_polygon'}, inplace=True)
# li_canada_gdf_copy["geometry"] = gpd.points_from_xy(li_canada_gdf_copy["Longitude"], li_canada_gdf_copy["Latitude"])
# li_canada_gdf_copy = li_canada_gdf_copy.set_geometry("geometry", crs="EPSG:4326")

In [ ]:
# lt_main_li = match_facilities(main_gdf, li_canada_gdf_copy,
#                      id_col1='main_id', id_col2='li_id',
#                      name_col1='facility_name', name_col2='Name'
#                      )
# lt_main_li.to_excel(r'data/Sources/lt_main_li.xlsx', index=False)

In [ ]:
matches_main_li = pd.read_excel(r'data/Sources/lt_main_li.xlsx', sheet_name='for_pandas')

In [ ]:
li_canada_gdf = li_canada_gdf.merge(
    matches_main_li,
    on="li_id",  
    how="left"
)

In [ ]:
li_canada_gdf

In [ ]:
# For SQL
li_canada_gdf = li_canada_gdf[li_canada_gdf["main_id"].notna()].copy()

In [ ]:
li_canada_gdf

## Point to polygon matching

### Protected lands datasets

In [ ]:
from matching_functions import associate_facilities_near_polygons

In [ ]:
wpda_gdf_polygons

In [ ]:
lt_wpda = associate_facilities_near_polygons(
    main_gdf,
    wpda_gdf_polygons,
    facility_id_col="main_id",
    polygon_id_col="WDPA_PID",
    buffer_km=50,
    crs="EPSG:3978"
)

In [ ]:
wpda_gdf_polygons = wpda_gdf_polygons.merge(lt_wpda, on="WDPA_PID", how="left")

In [ ]:
# For SQL
wpda_gdf_polygons = wpda_gdf_polygons[wpda_gdf_polygons["main_id"].notna()].copy()

In [ ]:
lt_indigenous = associate_facilities_near_polygons(
    main_gdf,
    indigenous_can_gdf,
    facility_id_col="main_id",
    polygon_id_col="indigenous_land_id",
    buffer_km=50,
    crs="EPSG:3978"
)

In [ ]:
indigenous_can_gdf = indigenous_can_gdf.merge(lt_indigenous, on="indigenous_land_id", how="left")

In [ ]:
# For SQL
indigenous_can_gdf = indigenous_can_gdf[indigenous_can_gdf["main_id"].notna()].copy()

### Land occupation footprint datasets

In [ ]:
from matching_functions import assign_polygons_to_points

In [ ]:
main_gdf

In [ ]:
assigned_df = assign_polygons_to_points(
    main_gdf,
    tailings_gdf,
    tang_canada_gdf,
    max_dist_km=10
)

In [ ]:
assigned_df

In [ ]:
assigned_df['relation_type'].value_counts()

In [ ]:
polygon_gdf = tang_canada_gdf.merge(assigned_df, on="tang_id", how="left")

In [ ]:
polygon_gdf

In [ ]:
from visualization_functions import plot_polygons_assginment

In [ ]:
plot_polygons_assginment(
    main_gdf,
    tailings_gdf,
    polygon_gdf, 
    output_html="results/data_coverage/facilities_tailings_maps.html"
)

# Create final tables

## Main table

In [ ]:
main_gdf

In [ ]:
ownership_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Ownership')

In [ ]:
# Integrate ownership information into the main_gdf 
main_gdf = main_gdf.merge(
    ownership_df[['main_id', 'owner(s)', 'operator(s)', 'company_URL', 'company_facility_URL', 'MDO_URL']],
    on='main_id',
    how='left'
)

In [ ]:
# # Integrate the operation_periods from min_can_gdf into the main_gdf
main_gdf = main_gdf.merge(
     min_can_gdf[['main_id', 'operation_periods']],
     on='main_id',
     how='left'
 )
# 
# # Add the source_id for MinCan only where operation_periods are not null
main_gdf['source_id'] = main_gdf.apply(
     lambda row: row['source_id'] + ';' + 'https://doi.org/10.1038/s41597-024-03116-3' if pd.notna(row['operation_periods']) else row['source_id'],
     axis=1
 )

In [ ]:
main_gdf

In [ ]:
main_gdf.rename(columns={
    'company_name_folder': 'company_name',
    'company_facility_URL': 'facility_URL'
}, inplace=True)

In [ ]:
column_order = [
       'main_id', 'facility_name', 'facility_group_id', 'facility_group_name', 'company_id', 'company_name',
       'city', 'province', 'geometry',
       'status', 'activity_status', 'development_stage', 'facility_type', 'mining_processing_type',
       'commodity_group', 'commodities',
       'owner(s)', 'operator(s)', 'operation_periods', 
       'company_URL', 'facility_URL', 'MDO_URL', 
       'source_id'
]

In [ ]:
# Fix column orders
main_gdf = main_gdf[column_order].copy()

In [ ]:
main_gdf

## Environment table

### CTrace dataset

In [102]:
ctrace_ghg_gdf.rename(columns={
    'ctrace_id': 'env_id',
    'emissions_quantity': 'value',
    'gas': 'unit'}, inplace=True)

In [103]:
ctrace_ghg_gdf['unit'] = ctrace_ghg_gdf['unit'].replace({'co2e_100yr': 'tCO2eq'})

In [104]:
ctrace_ghg_gdf

,env_id,year,value,unit,source_id,substance_id,compartment_id,main_id
6,1754055,2023,5.610000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449
7,1754056,2023,6.403000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409
8,1754057,2023,2.299160e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0
9,1754058,2023,2.639000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e
11,1754060,2023,4.225000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205
12,1754061,2023,1.316380e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-6b4800fe
16,1754066,2023,2.412130e+06,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-30c1828c
21,1754071,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-e34feb4d
23,1754075,2023,2.408400e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-be5b3dc8
25,1754077,2023,6.711600e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-e51eda66
29,1754081,2023,7.782000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,YT-MAIN-752fbcae
32,1754084,2023,7.956600e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-ed23117f
33,1754085,2023,7.137900e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-3f490561
34,1754086,2023,5.400000e+02,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-23155c25
35,1754087,2023,1.590800e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-aa76f6f2
43,1754096,2023,8.219000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-a97821c0
44,1754097,2023,8.451100e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-8eb8be0d
49,1754102,2023,1.593900e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-40ce0593
50,1754103,2023,4.433000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-e0a6250e
51,1754104,2023,3.367000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-b2148882
53,1754106,2023,1.144000e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-2d8801d6
54,25486533,2023,1.620000e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f8313ebd
55,25486534,2023,5.914500e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-a3c56a83
56,36395102,2023,5.760720e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-b64bae7a
57,36395102,2023,5.760720e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-18695c6d

In [105]:
ctrace_gdf['flow_direction'] = 'Emission'
ctrace_gdf['release_pathway'] = 'Unspecified'

### NPRI dataset

In [106]:
pollutant_npri_gdf.rename(columns={
    'row_id': 'env_id'}, inplace=True)

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_29444\497671354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pollutant_npri_gdf.rename(columns={

In [107]:
pollutant_npri_gdf['flow_direction'] = 'Emission'

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_29444\2093404476.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pollutant_npri_gdf['flow_direction'] = 'Emission'

In [108]:
pollutant_npri_gdf

,env_id,main_id,year,value,unit,compartment_id,substance_id,release_pathway,source_id,flow_direction
0,npri-1568-2023-1,ON-MAIN-1f126a43,2023,0.636,tonnes,comp3c458811,NA - 16,Stack Emissions,https://www.canada.ca/en/environment-climate-c...,Emission
1,npri-1568-2023-2,ON-MAIN-1f126a43,2023,0.116,kg,comp3c458811,NA - 02,Stack Emissions,https://www.canada.ca/en/environment-climate-c...,Emission
2,npri-1568-2023-3,ON-MAIN-1f126a43,2023,76.208,tonnes,comp3c458811,630-08-0,Stack Emissions,https://www.canada.ca/en/environment-climate-c...,Emission
3,npri-1568-2023-4,ON-MAIN-1f126a43,2023,0.00105,tonnes,comp3c458811,NA - 04,Stack Emissions,https://www.canada.ca/en/environment-climate-c...,Emission
4,npri-1568-2023-5,ON-MAIN-1f126a43,2023,0.18,kg,comp3c458811,NA - 05,Stack Emissions,https://www.canada.ca/en/environment-climate-c...,Emission
...,...,...,...,...,...,...,...,...,...,...
6604,npri-2740-2023-108,SK-MAIN-26b9aaf3,2023,0.01,kg,comp87cf962b,NA - 03,Other,https://www.canada.ca/en/environment-climate-c...,Emission
6605,npri-2740-2023-109,SK-MAIN-26b9aaf3,2023,0.1503,kg,comp87cf962b,NA - 05,Other,https://www.canada.ca/en/environment-climate-c...,Emission
6606,npri-2740-2023-110,SK-MAIN-26b9aaf3,2023,0.256,kg,comp87cf962b,NA - 08,Other,https://www.canada.ca/en/environment-climate-c...,Emission
6607,npri-2740-2023-111,SK-MAIN-26b9aaf3,2023,0.0802,kg,comp87cf962b,NA - 12,Other,https://www.canada.ca/en/environment-climate-c...,Emission
6608,npri-2740-2023-112,SK-MAIN-26b9aaf3,2023,0.0197,tonnes,comp87cf962b,NA - 14,Other,https://www.canada.ca/en/environment-climate-c...,Emission

### GHG dataset

In [109]:
ghg_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
0,GHG-10052-2023-1,NL-MAIN-dd723db4,2023,780.52,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
1,GHG-10101-2023-1,NT-MAIN-6c1d6ee6,2023,170.09,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
3,GHG-10188-2023-1,QC-MAIN-084bd95c,2023,274.90,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
5,GHG-10240-2023-1,QC-MAIN-a97821c0,2023,158.00,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
6,GHG-10299-2023-1,QC-MAIN-e25eed27,2023,804.49,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
138,GHG-11730-2023-1,QC-MAIN-92628f16,2023,406.65,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
141,GHG-11765-2023-1,ON-MAIN-4c35e094,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
142,GHG-11765-2023-1,ON-MAIN-020a683c,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
144,GHG-11989-2023-1,QC-MAIN-1eee4ace,2023,952.95,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
146,GHG-12298-2023-1,ON-MAIN-63b394c3,2023,325.43,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...

In [110]:
ghg_gdf.rename(columns={'row_id': 'env_id'}, inplace=True)

In [111]:
ghg_gdf['unit'] = ghg_gdf['unit'].replace({'kilotonnes of carbon dioxide equivalents (kt CO2 eq)': 'ktCO2eq'})

In [112]:
ghg_gdf['flow_direction'] = 'Emission'
ghg_gdf['release_pathway'] = 'Unspecified'

### Manually collected data

In [113]:
env_df

,row_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,substance_type,substance_name,cas_number,subflow_type,unit,value,comment,source,source_id,compartment_id
0,ENV-1f126a43-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Total area of site,ha,2445.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
1,ENV-1f126a43-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Site area physically disturbed by mine-related...,ha,2074.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
2,ENV-1f126a43-2023-3,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Site area currently undisturbed,ha,371.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
3,ENV-e7e6a960-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,NaN,CMP-6265c407,mining,"Open-pit, concentrator",...,NaN,NaN,NaN,Total area of site,ha,64093.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
4,ENV-e7e6a960-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,NaN,CMP-6265c407,mining,"Open-pit, concentrator",...,NaN,NaN,NaN,Site area physically disturbed by mine-related...,ha,3399.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-c5fefb01-2023-12,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Group of substances,PM2.5 - Particulate Matter <= 2.5 Micrometers,NA - M10,-,µm/t,0.74,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
320,ENV-9de9bb0d-2023-13,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,"Underground, concentrator",...,Substance,SO2,2025884,-,t,0.61,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
321,ENV-c5fefb01-2023-13,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Substance,SO2,2025884,-,t,1.14,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
322,ENV-9de9bb0d-2023-14,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,"Underground, concentrator",...,Group of substances,VOCs,NA - M16,-,t,0.20,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
323,ENV-c5fefb01-2023-14,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Group of substances,VOCs,NA - M16,-,t,0.99,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811

In [114]:
env_df

,row_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,substance_type,substance_name,cas_number,subflow_type,unit,value,comment,source,source_id,compartment_id
0,ENV-1f126a43-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Total area of site,ha,2445.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
1,ENV-1f126a43-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Site area physically disturbed by mine-related...,ha,2074.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
2,ENV-1f126a43-2023-3,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Site area currently undisturbed,ha,371.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
3,ENV-e7e6a960-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,NaN,CMP-6265c407,mining,"Open-pit, concentrator",...,NaN,NaN,NaN,Total area of site,ha,64093.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
4,ENV-e7e6a960-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,NaN,CMP-6265c407,mining,"Open-pit, concentrator",...,NaN,NaN,NaN,Site area physically disturbed by mine-related...,ha,3399.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-c5fefb01-2023-12,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Group of substances,PM2.5 - Particulate Matter <= 2.5 Micrometers,NA - M10,-,µm/t,0.74,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
320,ENV-9de9bb0d-2023-13,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,"Underground, concentrator",...,Substance,SO2,2025884,-,t,0.61,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
321,ENV-c5fefb01-2023-13,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Substance,SO2,2025884,-,t,1.14,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
322,ENV-9de9bb0d-2023-14,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,"Underground, concentrator",...,Group of substances,VOCs,NA - M16,-,t,0.20,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
323,ENV-c5fefb01-2023-14,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Group of substances,VOCs,NA - M16,-,t,0.99,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811

In [115]:
env_df.rename(columns={'row_id': 'env_id', 'cas_number': 'substance_id'}, inplace=True)

In [116]:
env_df

,env_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,substance_type,substance_name,substance_id,subflow_type,unit,value,comment,source,source_id,compartment_id
0,ENV-1f126a43-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Total area of site,ha,2445.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
1,ENV-1f126a43-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Site area physically disturbed by mine-related...,ha,2074.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
2,ENV-1f126a43-2023-3,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,CMP-6265c407,mining,"Underground, concentrator",...,NaN,NaN,NaN,Site area currently undisturbed,ha,371.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
3,ENV-e7e6a960-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,NaN,CMP-6265c407,mining,"Open-pit, concentrator",...,NaN,NaN,NaN,Total area of site,ha,64093.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
4,ENV-e7e6a960-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,NaN,CMP-6265c407,mining,"Open-pit, concentrator",...,NaN,NaN,NaN,Site area physically disturbed by mine-related...,ha,3399.00,NaN,2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-c5fefb01-2023-12,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Group of substances,PM2.5 - Particulate Matter <= 2.5 Micrometers,NA - M10,-,µm/t,0.74,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
320,ENV-9de9bb0d-2023-13,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,"Underground, concentrator",...,Substance,SO2,2025884,-,t,0.61,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
321,ENV-c5fefb01-2023-13,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Substance,SO2,2025884,-,t,1.14,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
322,ENV-9de9bb0d-2023-14,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,"Underground, concentrator",...,Group of substances,VOCs,NA - M16,-,t,0.20,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
323,ENV-c5fefb01-2023-14,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,"Open-pit, concentrator",...,Group of substances,VOCs,NA - M16,-,t,0.99,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811

In [117]:
env_df.drop(columns=['reporting_level', 'reported_company_nrcan', 'name', 'facility_type', 'mining_processing_type', 'commodity','compartment_name', 'substance_type', 'substance_name', 'subflow_type', 'source'], inplace=True)

In [118]:
env_df

,env_id,year,main_id,facility_group_id,company_id,flow_direction,substance_id,unit,value,comment,source_id,compartment_id
0,ENV-1f126a43-2023-1,2023,ON-MAIN-1f126a43,NaN,CMP-6265c407,Occupation and transformation,NaN,ha,2445.00,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
1,ENV-1f126a43-2023-2,2023,ON-MAIN-1f126a43,NaN,CMP-6265c407,Occupation and transformation,NaN,ha,2074.00,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
2,ENV-1f126a43-2023-3,2023,ON-MAIN-1f126a43,NaN,CMP-6265c407,Occupation and transformation,NaN,ha,371.00,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
3,ENV-e7e6a960-2023-1,2023,QC-MAIN-e7e6a960,NaN,CMP-6265c407,Occupation and transformation,NaN,ha,64093.00,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
4,ENV-e7e6a960-2023-2,2023,QC-MAIN-e7e6a960,NaN,CMP-6265c407,Occupation and transformation,NaN,ha,3399.00,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,comp87cf962b
...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-c5fefb01-2023-12,2023,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,Emission,NA - M10,µm/t,0.74,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
320,ENV-9de9bb0d-2023-13,2023,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,Emission,2025884,t,0.61,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
321,ENV-c5fefb01-2023-13,2023,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,Emission,2025884,t,1.14,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
322,ENV-9de9bb0d-2023-14,2023,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,Emission,NA - M16,t,0.20,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811
323,ENV-c5fefb01-2023-14,2023,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,Emission,NA - M16,t,0.99,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,comp3c458811

### Concatenate all environment data into a single table

In [119]:
env_table = pd.concat(
    [ctrace_ghg_gdf, pollutant_npri_gdf, ghg_gdf, env_df],
    ignore_index=True
)

In [120]:
env_table

,env_id,year,value,unit,source_id,substance_id,compartment_id,main_id,release_pathway,flow_direction,facility_group_id,company_id,comment
0,1754055,2023,5610.000024,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449,NaN,NaN,NaN,NaN,NaN
1,1754056,2023,6403.000027,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409,NaN,NaN,NaN,NaN,NaN
2,1754057,2023,229916.000984,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0,NaN,NaN,NaN,NaN,NaN
3,1754058,2023,2639.000011,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e,NaN,NaN,NaN,NaN,NaN
4,1754060,2023,4225.000018,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5194,ENV-c5fefb01-2023-12,2023,0.74,µm/t,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NA - M10,comp3c458811,ON-MAIN-c5fefb01,NaN,Emission,NaN,CMP-3d2c4955,NaN
5195,ENV-9de9bb0d-2023-13,2023,0.61,t,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,2025884,comp3c458811,QC-MAIN-9de9bb0d,NaN,Emission,NaN,CMP-3d2c4955,NaN
5196,ENV-c5fefb01-2023-13,2023,1.14,t,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,2025884,comp3c458811,ON-MAIN-c5fefb01,NaN,Emission,NaN,CMP-3d2c4955,NaN
5197,ENV-9de9bb0d-2023-14,2023,0.2,t,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NA - M16,comp3c458811,QC-MAIN-9de9bb0d,NaN,Emission,NaN,CMP-3d2c4955,NaN
5198,ENV-c5fefb01-2023-14,2023,0.99,t,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NA - M16,comp3c458811,ON-MAIN-c5fefb01,NaN,Emission,NaN,CMP-3d2c4955,NaN

In [121]:
env_table.columns

Index(['env_id', 'year', 'value', 'unit', 'source_id', 'substance_id',
       'compartment_id', 'main_id', 'release_pathway', 'flow_direction',
       'facility_group_id', 'company_id', 'comment'],
      dtype='object')

In [122]:
column_order = ['env_id', 'year', 'compartment_id', 'substance_id', 'flow_direction', 'release_pathway', 'unit', 'value', 'comment', 'main_id','facility_group_id', 'company_id', 'source_id']

In [123]:
env_table = env_table[column_order]

In [124]:
env_table

,env_id,year,compartment_id,substance_id,flow_direction,release_pathway,unit,value,comment,main_id,facility_group_id,company_id,source_id
0,1754055,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,5610.000024,NaN,ON-MAIN-6e9b2449,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
1,1754056,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,6403.000027,NaN,ON-MAIN-f080c409,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
2,1754057,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,229916.000984,NaN,BC-MAIN-599152a0,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
3,1754058,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,2639.000011,NaN,ON-MAIN-52224e1e,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
4,1754060,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,4225.000018,NaN,ON-MAIN-48fe2205,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5194,ENV-c5fefb01-2023-12,2023,comp3c458811,NA - M10,Emission,NaN,µm/t,0.74,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
5195,ENV-9de9bb0d-2023-13,2023,comp3c458811,2025884,Emission,NaN,t,0.61,NaN,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
5196,ENV-c5fefb01-2023-13,2023,comp3c458811,2025884,Emission,NaN,t,1.14,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
5197,ENV-9de9bb0d-2023-14,2023,comp3c458811,NA - M16,Emission,NaN,t,0.2,NaN,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
5198,ENV-c5fefb01-2023-14,2023,comp3c458811,NA - M16,Emission,NaN,t,0.99,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables

## Production table

### Manually collected data

In [125]:
production_df

,row_id,year,level,geography,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,...,commodity,reference_point,material_type,data_type,method,unit,value,comment,source,source_id
0,PROD-01c1e81f-2023-1,2023,Site-specific,Canada,Rio Tinto,Alma,QC-MAIN-01c1e81f,NaN,CMP-7a096012,manufacturing,...,Aluminum,Intermediate metal produced,Smelter production,Capacity,Reported,t,473000.0,NaN,https://aluminium.ca/en/the-industry/,SRC_RioTinto_the-industry
1,PROD-01c1e81f-2023-2,2023,Site-specific,Canada,Rio Tinto,Alma,QC-MAIN-01c1e81f,NaN,CMP-7a096012,manufacturing,...,Aluminum,Intermediate metal produced,Smelter production,Production,Reported,kt,484.0,NaN,rt-fact-book-addendum.xlsx,SRC_RioTinto_rt-fact-book-addendum
2,PROD-8d6616b4-2023-1,2023,Site-specific,Canada,Rio Tinto,Alouette,QC-MAIN-8d6616b4,NaN,CMP-7a096012,manufacturing,...,Aluminum,Intermediate metal produced,Smelter production,Capacity,Reported,t,620000.0,NaN,https://aluminium.ca/en/the-industry/,SRC_RioTinto_the-industry
3,PROD-8d6616b4-2023-2,2023,Site-specific,Canada,Rio Tinto,Alouette,QC-MAIN-8d6616b4,NaN,CMP-7a096012,manufacturing,...,Aluminum,Intermediate metal produced,Smelter production,Production,Reported,kt,634.0,NaN,rt-fact-book-addendum.xlsx,SRC_RioTinto_rt-fact-book-addendum
4,PROD-GRP-1402249f-2024-1,2024,Facility-group,Canada,ArcelorMittal,AMCC,NaN,GRP-1402249f,CMP-3775c12e,mining,...,Iron,Usable ore,Unspecified,Production,Reported,Mt,24.2,Ambigous production type,arcelormittal-factbook-2024.pdf,SRC_ArcelorMittal_arcelormittal-factbook-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,PROD-02884fb5-2023-2,2023,Site-specific,Canada,IAMGOLD Corporation,Westwood-Doyon,QC-MAIN-02884fb5,NaN,CMP-3d0a95b7,mining,...,Ore,Total extraction,Ore mined,Production,Reported,kt,1022.0,NaN,operational_data,SRC_IAMGOLDCorporation_operational_data
214,PROD-02884fb5-2023-3,2023,Site-specific,Canada,IAMGOLD Corporation,Westwood-Doyon,QC-MAIN-02884fb5,NaN,CMP-3d0a95b7,mining,...,Gold,Usable ore,Contained metal in concentrate,Production,Reported,koz,93.0,NaN,operational_data.xlsx,SRC_IAMGOLDCorporation_operational_data
215,PROD-687b8c8d-2023-1,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,...,Gold,Usable ore,Contained metal in concentrate,Production,Reported,oz,185100.0,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
216,PROD-687b8c8d-2023-2,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,...,Gold,Total extraction,Ore mined,Production,Reported,t,2878155.0,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
217,PROD-687b8c8d-2023-3,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,...,Gold,Crude ore,Ore processed,Production,Reported,t,2878047.0,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023

In [126]:
production_df.rename(columns={'row_id': 'prod_id'}, inplace=True)
production_df.drop(columns=['level', 'reported_company_nrcan', 'name', 
                            'facility_type', 'mining_processing_type', 'commodities_nrcan', 'source'], inplace=True)

In [127]:
production_df

,prod_id,year,geography,main_id,facility_group_id,company_id,commodity,reference_point,material_type,data_type,method,unit,value,comment,source_id
0,PROD-01c1e81f-2023-1,2023,Canada,QC-MAIN-01c1e81f,NaN,CMP-7a096012,Aluminum,Intermediate metal produced,Smelter production,Capacity,Reported,t,473000.0,NaN,SRC_RioTinto_the-industry
1,PROD-01c1e81f-2023-2,2023,Canada,QC-MAIN-01c1e81f,NaN,CMP-7a096012,Aluminum,Intermediate metal produced,Smelter production,Production,Reported,kt,484.0,NaN,SRC_RioTinto_rt-fact-book-addendum
2,PROD-8d6616b4-2023-1,2023,Canada,QC-MAIN-8d6616b4,NaN,CMP-7a096012,Aluminum,Intermediate metal produced,Smelter production,Capacity,Reported,t,620000.0,NaN,SRC_RioTinto_the-industry
3,PROD-8d6616b4-2023-2,2023,Canada,QC-MAIN-8d6616b4,NaN,CMP-7a096012,Aluminum,Intermediate metal produced,Smelter production,Production,Reported,kt,634.0,NaN,SRC_RioTinto_rt-fact-book-addendum
4,PROD-GRP-1402249f-2024-1,2024,Canada,NaN,GRP-1402249f,CMP-3775c12e,Iron,Usable ore,Unspecified,Production,Reported,Mt,24.2,Ambigous production type,SRC_ArcelorMittal_arcelormittal-factbook-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,PROD-02884fb5-2023-2,2023,Canada,QC-MAIN-02884fb5,NaN,CMP-3d0a95b7,Ore,Total extraction,Ore mined,Production,Reported,kt,1022.0,NaN,SRC_IAMGOLDCorporation_operational_data
214,PROD-02884fb5-2023-3,2023,Canada,QC-MAIN-02884fb5,NaN,CMP-3d0a95b7,Gold,Usable ore,Contained metal in concentrate,Production,Reported,koz,93.0,NaN,SRC_IAMGOLDCorporation_operational_data
215,PROD-687b8c8d-2023-1,2023,Canada,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Gold,Usable ore,Contained metal in concentrate,Production,Reported,oz,185100.0,NaN,SRC_AlamosGoldInc_Data_2023
216,PROD-687b8c8d-2023-2,2023,Canada,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Gold,Total extraction,Ore mined,Production,Reported,t,2878155.0,NaN,SRC_AlamosGoldInc_Data_2023
217,PROD-687b8c8d-2023-3,2023,Canada,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Gold,Crude ore,Ore processed,Production,Reported,t,2878047.0,NaN,SRC_AlamosGoldInc_Data_2023

In [128]:
from constants import unit_conversion

In [129]:
# Apply a function to convert the 'value' column to tonnes
# But we need to do that only for the 'Production' data_type and don't do it for any other data_type
production_df['value_tonnes'] = production_df.apply(
    lambda row: row['value'] * unit_conversion.get(row['unit'], 1) if row['data_type'] == 'Production' else np.nan, 
    axis=1
)

In [130]:
#Check the row where main_id is ON-MAIN-1f126a45
production_df[production_df['main_id'] == 'ON-MAIN-1f126a45']

Empty DataFrame
Columns: [prod_id, year, geography, main_id, facility_group_id, company_id, commodity, reference_point, material_type, data_type, method, unit, value, comment, source_id, value_tonnes]
Index: []

### CTrace dataset

In [131]:
ctrace_prod_gdf

,ctrace_id,year,activity,activity_units,capacity,capacity_units,source_id,substance_id,compartment_id,main_id
6,1754055,2023,8.630000e+05,t of copper ore,4.624000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449
7,1754056,2023,9.850000e+05,t of copper ore,3.554700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409
8,1754057,2023,1.457500e+07,t of copper ore,3.670000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0
9,1754058,2023,4.060000e+05,t of copper ore,1.104100e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e
11,1754060,2023,6.500000e+05,t of copper ore,4.822000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205
12,1754061,2023,8.810000e+07,t of copper ore,6.450000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-6b4800fe
16,1754066,2023,7.288600e+07,t of copper ore,2.631000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-30c1828c
21,1754071,2023,0.000000e+00,t of copper ore,1.073810e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-e34feb4d
23,1754075,2023,1.526729e+06,t of copper ore,1.357000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-be5b3dc8
25,1754077,2023,1.501481e+06,t of copper ore,1.988200e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-e51eda66
29,1754081,2023,5.279710e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,t of copper ore,7.413000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,t of copper ore,2.313000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,YT-MAIN-752fbcae
32,1754084,2023,2.127800e+07,t of copper ore,2.500250e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-ed23117f
33,1754085,2023,5.948239e+06,t of copper ore,4.902900e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-3f490561
34,1754086,2023,4.500000e+04,t of copper ore,4.110000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-23155c25
35,1754087,2023,2.993000e+06,t of copper ore,3.408700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-aa76f6f2
43,1754096,2023,6.848790e+05,t of copper ore,1.500000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-a97821c0
44,1754097,2023,6.887709e+06,t of copper ore,4.549000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-8eb8be0d
49,1754102,2023,1.431680e+06,t of copper ore,1.690000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-40ce0593
50,1754103,2023,6.820000e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-e0a6250e
51,1754104,2023,5.180000e+05,t of copper ore,2.453000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-b2148882
53,1754106,2023,1.760000e+06,t of copper ore,3.110000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-2d8801d6
54,25486533,2023,1.350000e+06,t of copper ore,2.500000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f8313ebd
55,25486534,2023,3.798000e+06,t of copper ore,2.200000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-a3c56a83
56,36395102,2023,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-b64bae7a
57,36395102,2023,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-18695c6d

In [132]:
# Save units before melting
activity_units = ctrace_prod_gdf['activity_units']
capacity_units = ctrace_prod_gdf['capacity_units']

# Melt
ctrace_prod_gdf = pd.melt(
    ctrace_prod_gdf,
    id_vars=['ctrace_id', 'year', 'source_id', 'main_id'],
    value_vars=['activity', 'capacity'],
    var_name='data_type',
    value_name='value'
)

# Set data_type labels
ctrace_prod_gdf['data_type'] = ctrace_prod_gdf['data_type'].replace({
    'activity': 'Production',
    'capacity': 'Capacity'
})

# Concatenate units in correct order (activity first, then capacity)
ctrace_prod_gdf['unit'] = list(activity_units) + list(capacity_units)

In [133]:
ctrace_prod_gdf

,ctrace_id,year,source_id,main_id,data_type,value,unit
0,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Production,8.630000e+05,t of copper ore
1,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Production,9.850000e+05,t of copper ore
2,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Production,1.457500e+07,t of copper ore
3,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Production,4.060000e+05,t of copper ore
4,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Production,6.500000e+05,t of copper ore
5,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Production,8.810000e+07,t of copper ore
6,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Production,7.288600e+07,t of copper ore
7,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Production,0.000000e+00,t of copper ore
8,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Production,0.000000e+00,t of copper ore
9,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Production,1.526729e+06,t of copper ore
10,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Production,1.501481e+06,t of copper ore
11,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Production,5.279710e+05,t of copper ore
12,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Production,0.000000e+00,t of copper ore
13,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Production,0.000000e+00,t of copper ore
14,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Production,2.127800e+07,t of copper ore
15,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Production,5.948239e+06,t of copper ore
16,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Production,4.500000e+04,t of copper ore
17,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Production,2.993000e+06,t of copper ore
18,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Production,6.848790e+05,t of copper ore
19,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Production,6.887709e+06,t of copper ore
20,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Production,1.431680e+06,t of copper ore
21,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Production,6.820000e+05,t of copper ore
22,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Production,5.180000e+05,t of copper ore
23,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Production,0.000000e+00,t of copper ore
24,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Production,1.760000e+06,t of copper ore
25,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Production,1.350000e+06,t of copper ore
26,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Production,3.798000e+06,t of copper ore
27,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Production,1.578280e+07,t of iron ore
28,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Production,1.578280e+07,t of iron ore
29,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Capacity,4.624000e+06,tonnes
30,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Capacity,3.554700e+07,tonnes
31,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Capacity,3.670000e+08,tonnes
32,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Capacity,1.104100e+07,tonnes
33,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Capacity,4.822000e+06,tonnes
34,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Capacity,6.450000e+08,tonnes
35,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Capacity,2.631000e+08,tonnes
36,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Capacity,8.787959e+07,tonnes
37,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Capacity,1.073810e+08,tonnes
38,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Capacity,1.357000e+07,tonnes
39,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Capacity,1.988200e+07,tonnes
40,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Capacity,8.787959e+07,tonnes
41,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Capacity,7.413000e+06,tonnes
42,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Capacity,2.313000e+06,tonnes
43,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Capacity,2.500250e+08,tonnes
44,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Capacity,4.902900e+07,tonnes
45,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Capacity,4.110000e+06,tonnes
46,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Capacity,3.408700e+07,tonnes
47,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Capacity,1.500000e+07,tonnes
48,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Capacity,4.549000e+08,tonnes
49,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Capacity,1.690000e+07,tonnes
50,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Capacity,8.787959e+07,tonnes
51,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Capacity,2.453000e+06,tonnes
52,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Capacity,8.787959e+07,tonnes
53,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Capacity,3.110000e+07,tonnes
54,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Capacity,2.500000e+06,tonnes
55,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Capacity,2.200000e+07,tonnes
56,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Capacity,4.789430e+08,tonnes
57,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Capacity,4.789430e+08,tonnes

In [134]:
ctrace_prod_gdf.rename(columns={'ctrace_id': 'prod_id'}, inplace=True)

In [135]:
# We add the missing columns
ctrace_prod_gdf['geography'] = 'Canada'
ctrace_prod_gdf['reference_point'] = 'Crude ore'
ctrace_prod_gdf['value_tonnes'] = ctrace_prod_gdf['value'] # they are always in tonnes

In [136]:
# Add a commodity column with would be = Copper if unit column = 't of copper ore' and = 'Iron' if unit column = 't of iron ore'
ctrace_prod_gdf['commodity'] = ctrace_prod_gdf['unit'].apply(
    lambda x: 'Copper' if 'copper' in x.lower() else ('Iron' if 'iron' in x.lower() else None)
)

In [137]:
ctrace_prod_gdf

,prod_id,year,source_id,main_id,data_type,value,unit,geography,reference_point,value_tonnes,commodity
0,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Production,8.630000e+05,t of copper ore,Canada,Crude ore,8.630000e+05,Copper
1,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Production,9.850000e+05,t of copper ore,Canada,Crude ore,9.850000e+05,Copper
2,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Production,1.457500e+07,t of copper ore,Canada,Crude ore,1.457500e+07,Copper
3,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Production,4.060000e+05,t of copper ore,Canada,Crude ore,4.060000e+05,Copper
4,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Production,6.500000e+05,t of copper ore,Canada,Crude ore,6.500000e+05,Copper
5,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Production,8.810000e+07,t of copper ore,Canada,Crude ore,8.810000e+07,Copper
6,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Production,7.288600e+07,t of copper ore,Canada,Crude ore,7.288600e+07,Copper
7,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
8,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
9,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Production,1.526729e+06,t of copper ore,Canada,Crude ore,1.526729e+06,Copper
10,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Production,1.501481e+06,t of copper ore,Canada,Crude ore,1.501481e+06,Copper
11,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Production,5.279710e+05,t of copper ore,Canada,Crude ore,5.279710e+05,Copper
12,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
13,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
14,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Production,2.127800e+07,t of copper ore,Canada,Crude ore,2.127800e+07,Copper
15,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Production,5.948239e+06,t of copper ore,Canada,Crude ore,5.948239e+06,Copper
16,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Production,4.500000e+04,t of copper ore,Canada,Crude ore,4.500000e+04,Copper
17,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Production,2.993000e+06,t of copper ore,Canada,Crude ore,2.993000e+06,Copper
18,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Production,6.848790e+05,t of copper ore,Canada,Crude ore,6.848790e+05,Copper
19,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Production,6.887709e+06,t of copper ore,Canada,Crude ore,6.887709e+06,Copper
20,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Production,1.431680e+06,t of copper ore,Canada,Crude ore,1.431680e+06,Copper
21,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Production,6.820000e+05,t of copper ore,Canada,Crude ore,6.820000e+05,Copper
22,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Production,5.180000e+05,t of copper ore,Canada,Crude ore,5.180000e+05,Copper
23,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
24,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Production,1.760000e+06,t of copper ore,Canada,Crude ore,1.760000e+06,Copper
25,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Production,1.350000e+06,t of copper ore,Canada,Crude ore,1.350000e+06,Copper
26,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Production,3.798000e+06,t of copper ore,Canada,Crude ore,3.798000e+06,Copper
27,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Production,1.578280e+07,t of iron ore,Canada,Crude ore,1.578280e+07,Iron
28,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Production,1.578280e+07,t of iron ore,Canada,Crude ore,1.578280e+07,Iron
29,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Capacity,4.624000e+06,tonnes,Canada,Crude ore,4.624000e+06,None
30,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Capacity,3.554700e+07,tonnes,Canada,Crude ore,3.554700e+07,None
31,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Capacity,3.670000e+08,tonnes,Canada,Crude ore,3.670000e+08,None
32,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Capacity,1.104100e+07,tonnes,Canada,Crude ore,1.104100e+07,None
33,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Capacity,4.822000e+06,tonnes,Canada,Crude ore,4.822000e+06,None
34,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Capacity,6.450000e+08,tonnes,Canada,Crude ore,6.450000e+08,None
35,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Capacity,2.631000e+08,tonnes,Canada,Crude ore,2.631000e+08,None
36,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
37,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Capacity,1.073810e+08,tonnes,Canada,Crude ore,1.073810e+08,None
38,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Capacity,1.357000e+07,tonnes,Canada,Crude ore,1.357000e+07,None
39,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Capacity,1.988200e+07,tonnes,Canada,Crude ore,1.988200e+07,None
40,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
41,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Capacity,7.413000e+06,tonnes,Canada,Crude ore,7.413000e+06,None
42,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Capacity,2.313000e+06,tonnes,Canada,Crude ore,2.313000e+06,None
43,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Capacity,2.500250e+08,tonnes,Canada,Crude ore,2.500250e+08,None
44,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Capacity,4.902900e+07,tonnes,Canada,Crude ore,4.902900e+07,None
45,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Capacity,4.110000e+06,tonnes,Canada,Crude ore,4.110000e+06,None
46,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Capacity,3.408700e+07,tonnes,Canada,Crude ore,3.408700e+07,None
47,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Capacity,1.500000e+07,tonnes,Canada,Crude ore,1.500000e+07,None
48,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Capacity,4.549000e+08,tonnes,Canada,Crude ore,4.549000e+08,None
49,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Capacity,1.690000e+07,tonnes,Canada,Crude ore,1.690000e+07,None
50,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
51,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Capacity,2.453000e+06,tonnes,Canada,Crude ore,2.453000e+06,None
52,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
53,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Capacity,3.110000e+07,tonnes,Canada,Crude ore,3.110000e+07,None
54,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Capacity,2.500000e+06,tonnes,Canada,Crude ore,2.500000e+06,None
55,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Capacity,2.200000e+07,tonnes,Canada,Crude ore,2.200000e+07,None
56,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Capacity,4.789430e+08,tonnes,Canada,Crude ore,4.789430e+08,None
57,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Capacity,4.789430e+08,tonnes,Canada,Crude ore,4.789430e+08,None

### Concatenate all production data into a single table

In [138]:
# Concatenate production and ctrace data 
production_table = pd.concat([production_df, ctrace_prod_gdf], ignore_index=True)

In [139]:
production_table.columns

Index(['prod_id', 'year', 'geography', 'main_id', 'facility_group_id',
       'company_id', 'commodity', 'reference_point', 'material_type',
       'data_type', 'method', 'unit', 'value', 'comment', 'source_id',
       'value_tonnes'],
      dtype='object')

In [140]:
column_order = ['prod_id', 'year', 'geography', 
                'commodity', 'reference_point', 'material_type', 'data_type', 
                'unit', 'value', 'value_tonnes', 'comment', 
                'main_id', 'facility_group_id','company_id', 'source_id']

In [141]:
production_table = production_table[column_order]

In [142]:
production_table

,prod_id,year,geography,commodity,reference_point,material_type,data_type,unit,value,value_tonnes,comment,main_id,facility_group_id,company_id,source_id
0,PROD-01c1e81f-2023-1,2023,Canada,Aluminum,Intermediate metal produced,Smelter production,Capacity,t,4.730000e+05,NaN,NaN,QC-MAIN-01c1e81f,NaN,CMP-7a096012,SRC_RioTinto_the-industry
1,PROD-01c1e81f-2023-2,2023,Canada,Aluminum,Intermediate metal produced,Smelter production,Production,kt,4.840000e+02,4.840000e+05,NaN,QC-MAIN-01c1e81f,NaN,CMP-7a096012,SRC_RioTinto_rt-fact-book-addendum
2,PROD-8d6616b4-2023-1,2023,Canada,Aluminum,Intermediate metal produced,Smelter production,Capacity,t,6.200000e+05,NaN,NaN,QC-MAIN-8d6616b4,NaN,CMP-7a096012,SRC_RioTinto_the-industry
3,PROD-8d6616b4-2023-2,2023,Canada,Aluminum,Intermediate metal produced,Smelter production,Production,kt,6.340000e+02,6.340000e+05,NaN,QC-MAIN-8d6616b4,NaN,CMP-7a096012,SRC_RioTinto_rt-fact-book-addendum
4,PROD-GRP-1402249f-2024-1,2024,Canada,Iron,Usable ore,Unspecified,Production,Mt,2.420000e+01,2.420000e+01,Ambigous production type,NaN,GRP-1402249f,CMP-3775c12e,SRC_ArcelorMittal_arcelormittal-factbook-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,1754106,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,3.110000e+07,3.110000e+07,NaN,NL-MAIN-2d8801d6,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
272,25486533,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,2.500000e+06,2.500000e+06,NaN,ON-MAIN-f8313ebd,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
273,25486534,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,2.200000e+07,2.200000e+07,NaN,ON-MAIN-a3c56a83,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
274,36395102,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,4.789430e+08,4.789430e+08,NaN,NL-MAIN-b64bae7a,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
275,36395102,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,4.789430e+08,4.789430e+08,NaN,NL-MAIN-18695c6d,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."

In [143]:
production_table['main_id'].value_counts()

main_id
MB-MAIN-da0b5c3d    11
BC-MAIN-ed23117f     8
BC-MAIN-599152a0     8
NU-MAIN-8b0264c9     7
QC-MAIN-a97821c0     7
                    ..
ON-MAIN-f4fc3276     1
QC-MAIN-33c09b8b     1
QC-MAIN-a555d9b9     1
QC-MAIN-3e146840     1
NU-MAIN-5154702a     1
Name: count, Length: 85, dtype: int64

## Tech attributes table

In [18]:
tech_attributes_df

,row_id,year,level,geography,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,...,commodities_nrcan,commodity,reference_point,material_type,method,unit,value,comment,source,source_id
0,TA-7607a50e-2023-1,2023,Site-specific,Canada,Alamos Gold Inc,Island,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,mining,...,Gold,Gold,Crude ore,Mill grade,Reported,g/t,9.48,Assumed g/t,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
1,TA-7607a50e-2023-2,2023,Site-specific,Canada,Alamos Gold Inc,Island,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,mining,...,Gold,Gold,Crude ore,Mill recovery rate,Reported,%,97.00,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
2,TA-7607a50e-2023-3,2023,Site-specific,Canada,Alamos Gold Inc,Island,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,mining,...,Gold,Gold,Crude ore,Ore grade,Reported,g/t,9.43,Assumed g/t,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
3,TA-687b8c8d-2023-1,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,...,Gold,Gold,Crude ore,Mill grade,Reported,g/t,2.20,Assumed g/t,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
4,TA-687b8c8d-2023-2,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,...,Gold,Gold,Crude ore,Mill recovery rate,Reported,%,90.00,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,TA-6b4800fe-2023-3,2023,Site-specific,Canada,Taseko Mines Limited,Gibraltar,BC-MAIN-6b4800fe,NaN,CMP-e35f138c,mining,...,"Copper, molybdenum, silver",Copper,Usable ore,Copper recovery,Reported,%,82.60,NaN,https://www.tasekomines.com/investors/news/tas...,SRC_TasekoMinesLimited_taseko-reports-strong-f...
93,TA-9de9bb0d-2023-1,2023,Site-specific,Canada,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,...,Gold,Gold,Crude ore,Head grade,Reported,g/t,12.60,NaN,2024-MDA-FINAL,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL
94,TA-9de9bb0d-2023-2,2023,Site-specific,Canada,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,mining,...,Gold,Gold,Crude ore,Recovery rate,Reported,%,96.90,NaN,2024-MDA-FINAL,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL
95,TA-c5fefb01-2023-1,2023,Site-specific,Canada,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,...,Gold,Gold,Crude ore,Head grade,Reported,g/t,5.90,NaN,2024-MDA-FINAL,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL
96,TA-c5fefb01-2023-2,2023,Site-specific,Canada,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,mining,...,Gold,Gold,Crude ore,Recovery rate,Reported,%,98.30,NaN,2024-MDA-FINAL,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL

In [19]:
tech_attributes_df.rename(columns={'row_id': 'tech_attr_id'}, inplace=True)

In [20]:
tech_attributes_table = tech_attributes_df[['tech_attr_id', 'year', 'commodity', 'reference_point', 'material_type', 'method', 'unit', 'value', 'comment', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

## Protected & Indigenous table

In [ ]:
protected_mapping = {
    "WDPA_PID": "protected_area_id",
    "NAME": "land_name",
    "DESIG": "land_type",
    "STATUS_YR": "date"
}

indigenous_mapping = {
    "indigenous_land_id": "protected_area_id",
    "Name": "land_name",
    "Category": "land_type",
    "Data_Date": "date"
}

In [ ]:
protected_clean = wpda_gdf_polygons.rename(columns=protected_mapping)[["protected_area_id", "land_name", "land_type", "distance_km", "geometry", "main_id", "source_id"]].copy()

In [ ]:
indigenous_clean = indigenous_can_gdf.rename(columns=indigenous_mapping)[["protected_area_id", "land_name", "land_type", "distance_km", "geometry", "main_id", "source_id"]].copy()

In [ ]:
target_crs = "EPSG:4326"
protected_clean = protected_clean.to_crs(target_crs)
indigenous_clean = indigenous_clean.to_crs(target_crs)

In [ ]:
protected_land_table = pd.concat([protected_clean, indigenous_clean], ignore_index=True)
protected_land_table = gpd.GeoDataFrame(protected_land_table, geometry="geometry", crs=wpda_gdf_polygons.crs)

In [ ]:
protected_land_table

In [ ]:
protected_land_table['protected_area_id'].value_counts()

## Land cover table

In [ ]:
land_cover_table = land_cover_gdf.copy()
land_cover_table['npv_biome_type'] = npv_gdf['biome_type']
land_cover_table['source_id'] = land_cover_table['source_id'].astype(str) + ';' + npv_gdf['source_id'].astype(str)

In [ ]:
from db_creation_function import assign_row_id

In [ ]:
land_cover_table = assign_row_id(land_cover_table,
                                 facility_id_col='main_id', 
                                 prefix='land_cover_id')

In [ ]:
land_cover_table.drop(columns=['name', 'geometry'], inplace=True)
land_cover_table.rename(columns={'row_id': 'land_cover_id'}, inplace=True)
land_cover_table = land_cover_table[['land_cover_id', 'year', 'modis_land_cover',
       'esa_land_cover', 'npv_biome_type', 'main_id', 'source_id']]

In [ ]:
land_cover_table

## Intensity table

In [32]:
intensity_df.rename(columns={'row_id': 'intensity_id'}, inplace=True)

In [33]:
intensity_table = intensity_df[['intensity_id', 'year', 'commodity', 'type', 'subtype', 'unit', 'value', 'comment', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

In [34]:
intensity_table

,intensity_id,year,commodity,type,subtype,unit,value,comment,main_id,facility_group_id,company_id,source_id
0,INT-CMP-140e111b-2023-1,2023,Aluminum,GHG,Refining,tCO2eq/t of production,0.54000,NaN,NaN,NaN,CMP-140e111b,SRC_AlcoaCorporation_2023-Sustainability-Data-...
1,INT-CMP-140e111b-2023-2,2023,Aluminum,GHG,Smelting,tCO2eq/t of production,4.15000,Operational control,NaN,NaN,CMP-140e111b,SRC_AlcoaCorporation_2023-Sustainability-Data-...
2,INT-CMP-140e111b-2023-3,2023,Aluminum,Land,Land utilization requirements for bauxite residue,m2 land/kt alumina produced,44.97000,NaN,NaN,NaN,CMP-140e111b,SRC_AlcoaCorporation_2023-Sustainability-Data-...
3,INT-CMP-140e111b-2023-4,2023,Aluminum,Land,Bauxite residue intensity,t/t alumina,1.79000,NaN,NaN,NaN,CMP-140e111b,SRC_AlcoaCorporation_2023-Sustainability-Data-...
4,INT-CMP-140e111b-2023-5,2023,Aluminum,Water,Water use intensity,m3/t alumina produced,3.87000,NaN,NaN,NaN,CMP-140e111b,SRC_AlcoaCorporation_2023-Sustainability-Data-...
...,...,...,...,...,...,...,...,...,...,...,...,...
126,INT-7f050560-2024-3,2024,"Gold, silver",Energy,Energy intensity,GJ/oz of gold produced,12.03742,NaN,ON-MAIN-7f050560,NaN,CMP-ca642bce,SRC_EvolutionMiningLtd_EVN_FY24-ESG-Performanc...
127,INT-9de9bb0d-2023-7,2023,Gold,Energy,Energy intensity,GJ/t milled,2.18000,NaN,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023
128,INT-9de9bb0d-2023-8,2023,Gold,Energy,Energy intensity,GJ/oz,5.67000,NaN,QC-MAIN-9de9bb0d,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023
129,INT-c5fefb01-2023-7,2023,Gold,Energy,Energy intensity,GJ/t milled,1.07000,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023
130,INT-c5fefb01-2023-8,2023,Gold,Energy,Energy intensity,GJ/oz,5.78000,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023

## Reserves and resources table

In [144]:
reserves_table = reserves_df.rename(columns={'row_id': 'reserves_id'})

In [145]:
reserves_table

,reserves_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,facility_type,mining_processing_type,commodity,...,ore_unit,grade,grade_unit,metal_content,metal_content_unit,norm,recovery_rate,comment,source,source_id
0,RES-d29e0839-2022-1,2022,Site-specific,Abcourt Mines Inc,Sleeping Giant,QC-MAIN-d29e0839,NaN,mining,Concentrator,Gold,...,Mt,7.14,g/t,173300.0,oz,NaN,NaN,NaN,TR_Abcourt_Geant_Dormant_2023,SRC_AbcourtMinesInc_TR_Abcourt_Geant_Dormant_2023
1,RES-d29e0839-2022-2,2022,Site-specific,Abcourt Mines Inc,Sleeping Giant,QC-MAIN-d29e0839,NaN,mining,Concentrator,Gold,...,Mt,8.74,g/t,248300.0,oz,NaN,NaN,NaN,TR_Abcourt_Geant_Dormant_2023,SRC_AbcourtMinesInc_TR_Abcourt_Geant_Dormant_2023
2,RES-1f126a43-2024-1,2024,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,mining,"Underground, concentrator","Gold, silver",...,kt,0.52,g/t,680.0,koz,NaN,93.233333,NaN,2024_MRMR,SRC_AgnicoEagleMinesLimited_2024_MRMR
3,RES-1f126a43-2024-2,2024,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,mining,"Underground, concentrator","Gold, silver",...,kt,2.43,g/t,6818.0,koz,NaN,93.233333,NaN,2024_MRMR,SRC_AgnicoEagleMinesLimited_2024_MRMR
4,RES-1f126a43-2024-3,2024,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,mining,"Underground, concentrator","Gold, silver",...,kt,1.9,g/t,3232.0,koz,NaN,NaN,NaN,2024_MRMR,SRC_AgnicoEagleMinesLimited_2024_MRMR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,RES-c5fefb01-2024-1,2024,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,mining,"Open-pit, concentrator",Gold,...,kt,11,g/t,107.0,koz,NaN,NaN,NaN,2024-MDA-FINAL.pdf,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL
390,RES-c5fefb01-2024-2,2024,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,mining,"Open-pit, concentrator",Gold,...,kt,8.9,g/t,592.0,koz,NaN,NaN,NaN,2024-MDA-FINAL.pdf,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL
391,RES-c5fefb01-2024-3,2024,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,mining,"Open-pit, concentrator",Gold,...,kt,10.2,g/t,19.0,koz,NaN,NaN,NaN,2024-MDA-FINAL.pdf,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL
392,RES-c5fefb01-2024-4,2024,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,mining,"Open-pit, concentrator",Gold,...,kt,5.4,g/t,138.0,koz,NaN,NaN,NaN,2024-MDA-FINAL.pdf,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL
393,RES-c5fefb01-2024-5,2024,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,mining,"Open-pit, concentrator",Gold,...,kt,5,g/t,411.0,koz,NaN,NaN,NaN,2024-MDA-FINAL.pdf,SRC_WesdomeGoldMinesLtd_2024-MDA-FINAL

In [146]:
reserves_table = reserves_table[['reserves_id', 'year', 'commodity', 'reserves_resources', 'reserves_resources_type', 'ore', 'ore_unit', 'grade', 'grade_unit', 'metal_content', 'metal_content_unit', 'recovery_rate', 'comment', 'main_id', 'facility_group_id', 'source_id']]

## Technosphere table

In [35]:
technosphere_df.rename(columns={'row_id': 'technosphere_id'}, inplace=True)

In [36]:
#energy_table = energy_df.rename(columns={'row_id': 'nrj_id'})
technosphere_table = technosphere_df[['technosphere_id', 'year', 'flow_type', 'subflow_type', 'unit', 'value', 'comment', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

In [37]:
technosphere_table

,technosphere_id,year,flow_type,subflow_type,unit,value,comment,main_id,facility_group_id,company_id,source_id
0,TECH-1f126a43-2023-1,2023,Energy,Diesel,GJ,2.557832e+06,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
1,TECH-1f126a43-2023-2,2023,Energy,Light Fuel & Gasoline,GJ,4.283300e+04,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
2,TECH-1f126a43-2023-3,2023,Energy,Propane,GJ,1.463609e+03,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
3,TECH-1f126a43-2023-4,2023,Energy,Natural gas,GJ,1.628050e+05,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
4,TECH-1f126a43-2023-5,2023,Energy,Electricity consumption,kWh,6.745244e+08,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
...,...,...,...,...,...,...,...,...,...,...,...
229,TECH-c5fefb01-2023-2,2023,Energy,Gasoline,kl,3.600000e+01,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023
230,TECH-c5fefb01-2023-3,2023,Energy,Explosives,t,5.060000e+02,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023
231,TECH-c5fefb01-2023-4,2023,Energy,Natural gas,kl,1.528000e+03,NaN,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023
232,TECH-c5fefb01-2023-5,2023,Energy,Electricity consumption|Grid electricity,MWh,3.205350e+04,Given in MW in the Excel file but does not mak...,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023
233,TECH-c5fefb01-2023-6,2023,Energy,Electricity consumption|Generated on-site,MWh,1.068450e+04,Given in MW in the Excel file but does not mak...,ON-MAIN-c5fefb01,NaN,CMP-3d2c4955,SRC_WesdomeGoldMinesLtd._ESG_data_2023

In [38]:
technosphere_table['unit'].unique()

array(['GJ', 'kWh', 't', 'tCO2eq', 'l', 'gallons', 'pounds', 'TJ', 'GWh',
       'kl', 'MWh', 'kg'], dtype=object)

## Waste table

## Tailings table

In [ ]:
tailings_table = tailings_gdf.rename(columns={'row_id': 'tailing_id',
                             'current_tailings_storage': 'current_storage'})
tailings_table = tailings_table[['tailing_id', 'year', 'tsf_name', 'status', 'construction_year', 
                             'raise_type', 'current_maximum_height', 'current_storage', 'hazard_categorization', 
                             'classification_system', 'geometry', 'main_id', 'source_id']]

## Land occupation table

In [ ]:
# Change the Land-use values from m2 to km2
li_canada_gdf['area_km2'] = li_canada_gdf['Land_use'].apply(lambda x: x / 1e6 if pd.notna(x) else x)

In [ ]:
li_canada_gdf.rename(columns={'li_id': 'land_occupation_id'}, inplace=True)

In [ ]:
li_canada_gdf = li_canada_gdf[['land_occupation_id', 'area_km2', 'geometry', 'main_id', 'source_id']]

In [ ]:
tang_gdf = polygon_gdf.rename(columns={'tang_id': 'land_occupation_id'}, inplace=True)

In [ ]:
polygon_gdf = polygon_gdf.to_crs(li_canada_gdf.crs)

In [ ]:
# Add the li_canada_gdf to the polygon_gdf
land_occupation_table = pd.concat([polygon_gdf, li_canada_gdf], ignore_index=True)

In [ ]:
land_occupation_table

In [ ]:
land_occupation_table = land_occupation_table[['land_occupation_id', 'area_km2', 'geometry', 'distance_km', 'main_id', 'tailing_id', 'source_id']]

In [ ]:
# Drop duplicates caused by tailing id, so drop duplicates only on the 
land_occupation_table = land_occupation_table.drop_duplicates(subset=['land_occupation_id'])

In [ ]:
land_occupation_table

In [ ]:
land_occupation_table['compartment_id'] = 'compde27e9f6'

## By-product

In [ ]:
bth_table = bth_df.drop(columns=['facility_name'])

In [ ]:
bth_table

## Archetypes table

In [26]:
archetypes_df.rename(columns={'row_id': 'archetype_id',
                              'mining_processing_type_nrcan': 'mining_method',
                              'mining_method_cleaned': 'mining_submethod',
                              'likely_ore_type': 'ore_type'
                              }, inplace=True)

In [27]:
archetypes_df

,archetype_id,TR_available,reported_company_nrcan,name,main_id,facility_group_id,facility_type,mining_method,mining_method_mdo,mining_submethod,...,deposit_gr_cmmi,deposit_type_cmmi,deposit_mdo,ore_type,mining_depth,mining_method_mdo.1,mining_method_cleaned.1,processing_method,source,source_id
0,ARCH-d29e0839-1,Yes,Abcourt Mines Inc,Sleeping Giant,QC-MAIN-d29e0839,NaN,mining,Concentrator,Shrinkage stoping;Room-and-pillar;Longhole sto...,Underground – Room and pillar – Room-and-Pilla...,...,NaN,NaN,VMS,Sulfide,NaN,Shrinkage stoping;Room-and-pillar;Longhole sto...,Underground – Room and pillar – Room-and-Pilla...,NaN,NaN,SRC_AbcourtMinesInc_nan
1,ARCH-1f126a43-1,Yes,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,NaN,mining,"Underground, concentrator","Open pit, conventional truck and shovel; remot...",Surface – Truck & Shovel,...,Orogenic,Mesozonal orogenic Au,Disseminated gold deposit,Sulfide,NaN,"Open pit, conventional truck and shovel; remot...",Surface – Truck & Shovel,"Conventional crushing, grinding, gravity conce...",NaN,SRC_AgnicoEagleMinesLimited_nan
2,ARCH-e7e6a960-1,Yes,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,NaN,mining,"Open-pit, concentrator","Open pit, conventional truck and shovel method",Surface – Truck & Shovel,...,Orogenic,Mesozonal orogenic Au,Disseminated and structurally controlled lode ...,Sulfide,NaN,"Open pit, conventional truck and shovel method",Surface – Truck & Shovel,"Crushing, grinding, gravity concentration, cya...",NaN,SRC_AgnicoEagleMinesLimited_nan
3,ARCH-8b0264c9-1,NaN,Agnico Eagle Mines Limited,Goldex,NU-MAIN-8b0264c9,NaN,mining,"Underground, concentrator",Truck & Shovel / Loader;Longhole stoping,"Surface – Truck & Shovel, Underground – Stopin...",...,NaN,NaN,Vein / narrow vein\nSkarn\nHydrothermal,Sulfide,NaN,Truck & Shovel / Loader;Longhole stoping,"Surface – Truck & Shovel, Underground – Stopin...",NaN,NaN,SRC_AgnicoEagleMinesLimited_nan
4,ARCH-4ea8ac9d-1,Yes,Agnico Eagle Mines Limited,LaRonde,NU-MAIN-4ea8ac9d,NaN,mining,"Open-pit, underground, concentrator",Longitudinal and transverse longhole open stop...,NaN,...,NaN,NaN,Polymetallic massive sulphide and lode gold de...,NaN,NaN,Longitudinal and transverse longhole open stop...,NaN,NaN,NaN,SRC_AgnicoEagleMinesLimited_nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,ARCH-d9036091-1,NaN,Vale,Voisey’s Bay,NL-MAIN-d9036091,NaN,mining,Refinery,Drift & Fill;Open stoping,Underground – Stoping – Cut-and-Fill Stoping,...,Anorthosite conduit,Anorthosite conduit Ni-Cu-PGE,Magmatic,Sulfide,NaN,Drift & Fill;Open stoping,Underground – Stoping – Cut-and-Fill Stoping,NaN,NaN,SRC_Vale_nan
81,ARCH-e05ed9fe-1,NaN,Victoria Gold Corporation,Eagle (Dublin Gulch),YT-MAIN-e05ed9fe,NaN,mining,"Open-pit, concentrator",Truck & Shovel / Loader,Surface – Truck & Shovel,...,NaN,NaN,Vein / narrow vein\nIntrusion related,Sulfide,NaN,Truck & Shovel / Loader,Surface – Truck & Shovel,NaN,NaN,SRC_VictoriaGoldCorporation_nan
82,ARCH-9de9bb0d-1,NaN,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,NaN,mining,"Underground, concentrator",Longhole stoping;Alimak;Sub-level open stoping...,Underground – Stoping – Long-Hole Stoping,...,NaN,NaN,Mesothermal\nVein / narrow vein,Sulfide,NaN,Longhole stoping;Alimak;Sub-level open stoping...,Underground – Stoping – Long-Hole Stoping,NaN,NaN,SRC_WesdomeGoldMinesLtd_nan
83,ARCH-c5fefb01-1,NaN,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,NaN,mining,"Open-pit, concentrator",Longhole stoping;Longitudinal retreat,Underground – Stoping – Long-Hole Stoping,...,NaN,NaN,Vein / narrow vein\nBreccia pipe / Stockwork\n...,Sulfide,NaN,Longhole stoping;Longitudinal retreat,Underground – Stoping – Long-Hole Stoping,NaN,NaN,SRC_WesdomeGoldMinesLtd_nan
84,ARCH-cb85213a-1,NaN,Wesdome Gold Mines Ltd,Mishi,ON-MAIN-cb85213a,NaN,mining,Open-pit,Truck & Shovel / Loader,Surface – Truck & Shovel,...,NaN,NaN,Vein / narrow vein\nMesothermal,Sulfide,NaN,Truck & Shovel / Loader,Surface – Truck & Shovel,NaN,NaN,SRC_WesdomeGoldMinesLtd_nan

In [28]:
archetype_table = archetypes_df[['archetype_id', 'ore_type', 'mining_method', 'mining_submethod', 'mining_depth', 'main_id', 'facility_group_id', 'source_id']]

In [29]:
archetype_table

,archetype_id,ore_type,mining_method,mining_submethod,mining_depth,main_id,facility_group_id,source_id
0,ARCH-d29e0839-1,Sulfide,Concentrator,Underground – Room and pillar – Room-and-Pilla...,NaN,QC-MAIN-d29e0839,NaN,SRC_AbcourtMinesInc_nan
1,ARCH-1f126a43-1,Sulfide,"Underground, concentrator",Surface – Truck & Shovel,NaN,ON-MAIN-1f126a43,NaN,SRC_AgnicoEagleMinesLimited_nan
2,ARCH-e7e6a960-1,Sulfide,"Open-pit, concentrator",Surface – Truck & Shovel,NaN,QC-MAIN-e7e6a960,NaN,SRC_AgnicoEagleMinesLimited_nan
3,ARCH-8b0264c9-1,Sulfide,"Underground, concentrator","Surface – Truck & Shovel, Underground – Stopin...",NaN,NU-MAIN-8b0264c9,NaN,SRC_AgnicoEagleMinesLimited_nan
4,ARCH-4ea8ac9d-1,NaN,"Open-pit, underground, concentrator",NaN,NaN,NU-MAIN-4ea8ac9d,NaN,SRC_AgnicoEagleMinesLimited_nan
...,...,...,...,...,...,...,...,...
80,ARCH-d9036091-1,Sulfide,Refinery,Underground – Stoping – Cut-and-Fill Stoping,NaN,NL-MAIN-d9036091,NaN,SRC_Vale_nan
81,ARCH-e05ed9fe-1,Sulfide,"Open-pit, concentrator",Surface – Truck & Shovel,NaN,YT-MAIN-e05ed9fe,NaN,SRC_VictoriaGoldCorporation_nan
82,ARCH-9de9bb0d-1,Sulfide,"Underground, concentrator",Underground – Stoping – Long-Hole Stoping,NaN,QC-MAIN-9de9bb0d,NaN,SRC_WesdomeGoldMinesLtd_nan
83,ARCH-c5fefb01-1,Sulfide,"Open-pit, concentrator",Underground – Stoping – Long-Hole Stoping,NaN,ON-MAIN-c5fefb01,NaN,SRC_WesdomeGoldMinesLtd_nan
84,ARCH-cb85213a-1,Sulfide,Open-pit,Surface – Truck & Shovel,NaN,ON-MAIN-cb85213a,NaN,SRC_WesdomeGoldMinesLtd_nan

## Water risk table

In [ ]:
water_risk_table = water_risk_gdf.rename(columns={'row_id': 'water_risk_id'})
water_risk_table = water_risk_table[['water_risk_id', 'indicator', 'value', 'year', 'scenario', 'value', 'main_id', 'source_id']]

In [ ]:
water_risk_table

## Climate categories table

In [ ]:
climate_category_table = climate_category_gdf.rename(columns={'row_id': 'climate_category_id'})
climate_category_table = climate_category_table[['climate_category_id', 'year', 'scenario', 'category', 'main_id', 'source_id']]

In [ ]:
climate_category_table

## Weather table

In [ ]:
weather_table = weather_gdf.rename(columns={'row_id': 'weather_id'})
weather_table = weather_table[['weather_id', 'year', 'variable', 'value', 'unit', 'scenario', 'main_id', 'source_id']]

In [ ]:
weather_table

## Conflict table

In [ ]:
conflict_table = conflict_gdf

In [ ]:
conflict_table = conflict_table[['ej_atlas_id', 'case_name', 'start_date', 'end_date', 
                             'conflict_description', 'conflict_details', 'population_affected',
                             'conflict_intensity', 'project_status', 'main_id', 'source_id']]

In [ ]:
conflict_table

## Population table

In [ ]:
population_table = population_gdf.rename(columns={'row_id': 'population_id'})
population_table = population_table[['population_id', 'year', 'buffer_size', 'total_population', 'main_id', 'source_id']]

In [ ]:
population_table

## Peatland table

In [ ]:
peatland_table = peatland_gdf[['peatland_presence', 'main_id', 'source_id']]

In [ ]:
peatland_table

## Prioritization area table

In [ ]:
prioritization_area_gdf

In [ ]:
prioritization_conservation_area_table = prioritization_area_gdf.rename(columns={
    'jung_priority_point': 'score_1_km',
    'jung_priority_mean_50km': 'mean_score_50_km',})
prioritization_conservation_area_table = prioritization_conservation_area_table[['score_1_km', 'mean_score_50_km', 'main_id', 'source_id']]

In [ ]:
prioritization_conservation_area_table

# Exports

## Exports tables to CSV

In [39]:
#env_table.to_csv(r'database/CSV/environment_table_new.csv', index=False, encoding="utf-8-sig")
technosphere_table.to_csv(r'database/csv/technosphere_table.csv', index=False, encoding="utf-8-sig")
#production_table.to_csv(r'database/CSV/production_table.csv', index=False, encoding="utf-8-sig")
#tech_attributes_df.to_csv(r'database/CSV/tech_attributes_table.csv', index=False, encoding="utf-8-sig")
#reserves_df.to_csv(r'database/CSV/reserves_table.csv', index=False, encoding="utf-8-sig")
#archetype_table.to_csv(r'database/CSV/archetypes_table.csv', index=False, encoding="utf-8-sig")
intensity_table.to_csv(r'database/CSV/intensity_table.csv', index=False, encoding="utf-8-sig")

In [ ]:
# Export all the tables to CSV
main_gdf.to_csv(r'database/CSV/main_table.csv', index=False, encoding="utf-8-sig")
production_table.to_csv(r'database/CSV/production_table.csv', index=False, encoding="utf-8-sig")
env_table.to_csv(r'database/CSV/env_table.csv', index=False, encoding="utf-8-sig")
land_cover_table.to_csv(r'database/CSV/land_cover_table.csv', index=False, encoding="utf-8-sig")
#env_int_df.to_csv(r'database/CSV/env_int_table.csv', index=False, encoding="utf-8-sig")
reserves_df.to_csv(r'database/CSV/reserves_table.csv', index=False, encoding="utf-8-sig")
technosphere_df.to_csv(r'database/csv/technosphere_table.csv', index=False, encoding="utf-8-sig")
tailings_gdf.to_csv(r'database/CSV/tailings_table.csv', index=False, encoding="utf-8-sig")
polygon_gdf.to_csv(r'database/CSV/land_occupation_table.csv', index=False, encoding="utf-8-sig")
archetypes_df.to_csv(r'database/CSV/archetypes_table.csv', index=False, encoding="utf-8-sig")
water_risk_gdf.to_csv(r'database/CSV/water_risk_table.csv', index=False, encoding="utf-8-sig")
climate_category_gdf.to_csv(r'database/CSV/climate_category_table.csv', index=False, encoding="utf-8-sig")
weather_gdf.to_csv(r'database/CSV/weather_table.csv', index=False, encoding="utf-8-sig")
conflict_gdf.to_csv(r'database/CSV/conflict_table.csv', index=False, encoding="utf-8-sig")
population_gdf.to_csv(r'database/CSV/population_table.csv', index=False, encoding="utf-8-sig")
peatland_gdf.to_csv(r'database/CSV/peatland_table.csv', index=False, encoding="utf-8-sig")
prioritization_area_gdf.to_csv(r'database/CSV/prioritization_area_table.csv', index=False, encoding="utf-8-sig")
bth_df.to_csv(r'database/CSV/bth_table.csv', index=False, encoding="utf-8-sig")
protected_land_table.to_csv(r'database/CSV/protected_land_table.csv', index=False, encoding="utf-8-sig")

In [ ]:
# We remove the geometry column to avoid issues with large file size
#protected_land_table.drop(columns=['geometry'], inplace=True)
protected_land_table.to_csv(r'database/CSV/protected_land_table.csv', index=False, encoding="utf-8-sig")

## Export DB to SQLite

In [ ]:
from matching_functions import create_and_populate_database

In [ ]:
tables_dict = {
    "Main": main_gdf,
    
    "Sources": source_table, 
    "Substances": substance_table,
    "Compartments": compartment_table,
    
    "Reserves_resources": reserves_table,
    "Production": production_table,
    "Energy": energy_table,
    "Environmental_flows": env_table,
    "Environmental_intensity": env_int_table,
    "Archetypes": archetype_table,
    
    "Tailings": tailings_table,
    "Land_occupation": land_occupation_table,
    "By_products": bth_table,
    
    "Water_risk": water_risk_table,
    "Climate_category": climate_category_table,
    "Weather": weather_table,
    "Land_cover": land_cover_table,
    "Conflict": conflict_table,
    "Population": population_table,
    "Peatland": peatland_table,
    "Prioritization_conservation_areas": prioritization_conservation_area_table,
    "Protected_indigenous_lands": protected_land_table,
    
}

# Run the function
create_and_populate_database(
    db_path="database/metallican.sqlite",
    schema_path="database/schema.sql",
    tables_dict=tables_dict,
    keep_geometry_tables=["main", "tailings", "polygons"]
)