In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

# Imports

In [2]:
main_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/main_gdf.parquet")
tailings_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/tailings_gdf.parquet")
min_can_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/min_can_gdf.parquet")
ctrace_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/ctrace_gdf.parquet")
conflict_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/conflict_gdf.parquet")
ghg_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/ghg_gdf.parquet")
pollutant_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/pollutant_gdf.parquet")
climate_category_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/climate_category_gdf.parquet")
weather_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/weather_gdf.parquet")
peatland_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/peatland_gdf.parquet")
prioritization_area_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/prioritization_area_gdf.parquet")
population_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/population_gdf.parquet")
water_risk_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/water_risk_gdf.parquet")
land_cover_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/land_cover_gdf.parquet")
npv_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/npv_gdf.parquet")
indigenous_can_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/indigenous_can_gdf.parquet")
wpda_gdf_polygons = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/wpda_gdf_polygons.parquet")
tang_canada_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/tang_canada_gdf.parquet")
li_canada_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/li_canada_gdf.parquet")

In [3]:
bth_df = pd.read_excel(r'data/Sources/Greffe_2024/BtH_mapped_sites.xlsx')

In [4]:
# From manually collected data
production_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Production')
reserves_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Reserves')
energy_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Energy')
env_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Env')
env_int_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Env_int')
archetypes_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Archetype')

In [5]:
from db_creation_function import assign_row_id_to_collected_data

In [6]:
# We need to assign row_ids to the manually collected data
production_df = assign_row_id_to_collected_data(production_df, 
                  facility_id_col='main_id',
                  prefix='PROD',
                  year_col='year'           
                  )

reserves_df = assign_row_id_to_collected_data(reserves_df, 
                  facility_id_col='main_id',
                  prefix='RES',
                  year_col='year'           
                  )

energy_df = assign_row_id_to_collected_data(energy_df, 
                  facility_id_col='main_id',
                  prefix='NRJ',
                  year_col='year'           
                  )

env_df = assign_row_id_to_collected_data(env_df, 
                  facility_id_col='main_id',
                  prefix='ENV',
                  year_col='year'           
                  )

env_int_df = assign_row_id_to_collected_data(env_int_df, 
                  facility_id_col='main_id',
                  prefix='ENV_INT',
                  year_col='year'           
                  )

archetypes_df = assign_row_id_to_collected_data(archetypes_df, 
                  facility_id_col='main_id',
                  prefix='ARCH',
                  )

# Create auxiliary tables

## Source table

In [7]:
# For the main table
source_map = {
    "project": "https://open.canada.ca/data/en/dataset/22b2db8a-dc12-47f2-9737-99d3da921751",
    "mining": "https://open.canada.ca/data/en/dataset/000183ed-8864-42f0-ae43-c4313a860720",
    "manufacturing": "https://open.canada.ca/data/en/dataset/000183ed-8864-42f0-ae43-c4313a860720"
}
main_gdf["source_id"] = main_gdf["facility_type"].map(source_map)
main_gdf

,main_id,facility_name,facility_group_name,facility_group_id,reported_company,company_name_folder,company_id,longitude,latitude,geometry,...,province,status,activity_status,development_stage,facility_type,mining_processing_type,commodity_group,primary_commodity,commodities,source_id
0,QC-MAIN-5801b453,Abcourt-Barvue,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.679010,48.521540,POINT (-77.67901 48.52154),...,Quebec,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, silver",https://open.canada.ca/data/en/dataset/22b2db8...
1,QC-MAIN-d29e0839,Sleeping Giant,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.974340,49.132590,POINT (-77.97434 49.13259),...,Quebec,active_facility,None,None,mining,Concentrator,Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...
2,QC-MAIN-f1ff4920,Akasaba West,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-77.580000,48.040000,POINT (-77.58000 48.04000),...,Quebec,project_facility,Active,Advanced project,project,None,None,Gold,"Gold, copper",https://open.canada.ca/data/en/dataset/22b2db8...
3,NU-MAIN-4ea8ac9d,Amaruq,Meadowbank complex,GRP-0a2c0d69,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-96.697000,65.415000,POINT (-96.69700 65.41500),...,Nunavut,active_facility,None,None,mining,"Open-pit, underground",Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...
4,QC-MAIN-e7e6a960,Canadian Malartic,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-78.130824,48.122223,POINT (-78.13082 48.12222),...,Quebec,active_facility,None,None,mining,"Open-pit, concentrator",Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,None,None,Wesdome Gold Mines Ltd.,Wesdome Gold Mines Ltd,CMP-3d2c4955,-85.452500,48.110280,POINT (-85.45250 48.11028),...,Ontario,active_facility,None,None,mining,Open-pit,Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...
266,BC-MAIN-feb13c30,Record Ridge,None,None,West High Yield Resources Ltd.,West High Yield Resources Ltd,CMP-1023f9c0,-117.884000,49.082000,POINT (-117.88400 49.08200),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Magnesium,Magnesium,https://open.canada.ca/data/en/dataset/22b2db8...
267,YT-MAIN-5e0d8b48,Casino,None,None,Western Copper and Gold Corporation,Western Copper and Gold Corporation,CMP-2dac9896,-138.833330,62.733330,POINT (-138.83333 62.73333),...,Yukon,project_facility,Active,Advanced project,project,None,None,Copper,"Copper, gold, molybdenum, silver",https://open.canada.ca/data/en/dataset/22b2db8...
268,ON-MAIN-12c68d49,Eagle's Nest,None,None,Wyloo,Wyloo,CMP-65b36728,-86.303800,52.742020,POINT (-86.30380 52.74202),...,Ontario,project_facility,Active,Advanced project,project,None,None,Nickel,"Nickel, copper, gold, platinum, palladium",https://open.canada.ca/data/en/dataset/22b2db8...
269,BC-MAIN-891d3cb5,Akie,None,None,ZincX Resources Corp.,ZincX Resources Corp,CMP-3416049b,-124.865990,57.380880,POINT (-124.86599 57.38088),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, lead, silver",https://open.canada.ca/data/en/dataset/22b2db8...

In [8]:
# For the datasets
tailings_gdf["source_id"] = 'https://tailing.grida.no/'
min_can_gdf["source_id"] = '10.1038/s41597-024-03116-3'
ctrace_gdf["source_id"] = 'Jolleys, M. et al (2024). Mineral Extraction sector: Mining and Quarrying Emissions from Copper, Iron, Bauxite, Rock and Sand, Hypervine, UK, Climate TRACE Emissions Inventory'
conflict_gdf["source_id"] = 'http://journals.librarypublishing.arizona.edu/jpe/article/id/1932/'
ghg_gdf["source_id"] = 'https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions/large-facilities.html'
pollutant_gdf["source_id"] = 'https://www.canada.ca/en/environment-climate-change/services/national-pollutant-release-inventory/tools-resources-data/exploredata.html' 
prioritization_area_gdf['source_id'] = 'https://doi.org/10.5281/zenodo.5006332'
climate_category_gdf['source_id'] = 'https://doi.org/10.1038/s41597-023-02549-6'
weather_gdf['source_id'] = 'https://climate-scenarios.canada.ca/?page=CanDCS6-indices'
peatland_gdf['source_id'] = 'https://greifswaldmoor.de/global-peatland-database-en.html'
population_gdf['source_id'] = 'https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F40-C41DA8332CFE' 
water_risk_gdf['source_id'] = 'https://www.wri.org/data/aqueduct-global-maps-40-data'
land_cover_gdf['source_id'] = 'https://doi.org/10.5067/MODIS/MCD12Q1.061 + https://doi.org/10.5281/zenodo.7254221'
npv_gdf['source_id'] = 'https://doi.org/10.7717/peerj.5457'
indigenous_can_gdf['source_id'] = 'http://www.landmarkmap.org'
wpda_gdf_polygons['source_id'] = 'https://www.protectedplanet.net'
tang_canada_gdf['source_id'] = 'https://doi.org/10.1038/s43247-023-00805-6'
#maus_canada_gdf['source_id'] = 'https://doi.org/10.1038/s41597-022-01547-4'
li_canada_gdf['source_id'] = 'https://www.nature.com/articles/s41597-025-05296-y'
bth_df['source_id'] = 'https://pubs.acs.org/doi/10.1021/acs.est.4c05293'

In [9]:
from db_creation_function import add_source_id_to_collected_data

In [10]:
production_df = add_source_id_to_collected_data(production_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

reserves_df = add_source_id_to_collected_data(reserves_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

energy_df = add_source_id_to_collected_data(energy_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

env_df = add_source_id_to_collected_data(env_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

env_int_df = add_source_id_to_collected_data(env_int_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

archetypes_df = add_source_id_to_collected_data(archetypes_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

In [11]:
from db_creation_function import create_source_table_from_datasets

In [12]:
dataset_dict = {
    "Global Tailings Portal": tailings_gdf,
    "A Comprehensive Historical and Geolocalized Database of Mining Activities in Canada": min_can_gdf,
    "ClimateTRACE mineral extraction sector": ctrace_gdf,
    "Environmental Justice Atlas": conflict_gdf,
    "GHG from large facilities": ghg_gdf,
    "National Pollutant Inventory Report (NPRI)": pollutant_gdf,
    "Areas of global importance for conserving terrestrial biodiversity, carbon and water": prioritization_area_gdf,
    "High-Resolution (1 km) Koppen-Geiger Maps for 1901–2099 Based on Constrained CMIP6 Projections": climate_category_gdf,
    "CMIP6 statistically downscaled climate indices (CanDCS-M6)": weather_gdf,
    "Global Peatland Database": peatland_gdf,
    "Global Human Settlement Layer (GHSL)": population_gdf,
    "Aqueduct 4.0": water_risk_gdf,
    "Modis Land Cover and ESA World Cover": land_cover_gdf,
    "Potential Natural Vegetation (NPV)": npv_gdf,
    "Indigenous Peoples’ and Local Community Lands and Territories": indigenous_can_gdf,
    "World Database on Protected Areas (WDPA)": wpda_gdf_polygons,
    "Global Mining Footprint Mapped from High-Resolution Satellite Imagery": tang_canada_gdf,
    "Machine learning-enhanced monitoring of global copper mining areas": li_canada_gdf,
    "Byproduct-to-Host Ratios for Assessing the Accessibility of Mineral Resources": bth_df,
}

manual_dfs = [production_df, reserves_df, energy_df, env_df, env_int_df, archetypes_df] 

source_table = create_source_table_from_datasets(dataset_dict, manual_dfs)

In [13]:
source_table

,source_id,source_provenance,source_name
0,https://tailing.grida.no/,dataset,Global Tailings Portal
18,https://pubs.acs.org/doi/10.1021/acs.est.4c05293,dataset,Byproduct-to-Host Ratios for Assessing the Acc...
17,https://www.nature.com/articles/s41597-025-052...,dataset,Machine learning-enhanced monitoring of global...
16,https://doi.org/10.1038/s43247-023-00805-6,dataset,Global Mining Footprint Mapped from High-Resol...
15,https://www.protectedplanet.net,dataset,World Database on Protected Areas (WDPA)
...,...,...,...
84,SRC_BaffinlandIronMinesCorporation_4q24-analys...,report,4q24-analyst-model-with-factbook-app.xlsx
85,SRC_BarrickGoldCorporation_Reserves_2024,report,Reserves_2024
86,SRC_BurgundyDiamondMines_2024-Annual-Mineral-R...,report,2024-Annual-Mineral-Resouces-and-Ore-Reserves-...
76,SRC_SherrittInternationalCorporationandGeneral...,report,TR_2023.pdf
258,SRC_WesdomeGoldMinesLtd_MDO,report,MDO

In [244]:
source_table.to_csv(r'database/CSV/sources_table.csv', index=False)

## Substance table

In [15]:
from db_creation_function import create_substance_table

In [16]:
substance_table = create_substance_table(pollutant_gdf, env_df)

In [17]:
substance_table

,substance_id,harmonized_name,original_name,source
0,SUB07971a0766,"1,2,4-Trimethylbenzene","1,2,4-Trimethylbenzene",NPRI
1,SUBbdfdffeb95,1-Nitropyrene,1-Nitropyrene,NPRI
2,SUB0f01e7c1d0,2-Butoxyethanol,2-Butoxyethanol,NPRI
3,SUB324959500a,"7,12-Dimethylbenz[a]anthracene","7,12-Dimethylbenz[a]anthracene",NPRI
4,SUBfee6b26acd,"7H-Dibenzo[c,g]carbazole","7H-Dibenzo[c,g]carbazole",NPRI
...,...,...,...,...
169,SUB787e5ac1a2,Vanadium (and its compounds),Vanadium (and its compounds),NPRI
170,SUBe849a2ff09,Xylene (all isomers),Xylene (all isomers),NPRI
171,SUBae95939c3f,Zinc (and its compounds),Zinc (and its compounds),NPRI
172,SUB090a1237c1,i-Butyl alcohol,i-Butyl alcohol,NPRI
173,SUBd049575022,n-Hexane,n-Hexane,NPRI

In [18]:
pollutant_gdf = pollutant_gdf.merge(
    substance_table[['substance_id', 'original_name']],
    how='left',
    left_on='substance_name_npri',
    right_on='original_name'
).drop(columns='original_name')

In [19]:
pollutant_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,substance_name_npri,substance_name_ecoinvent,substance_unit,emission_type,emission_subtype,value,source_id,geometry,substance_id
0,npri-1568-2023-1,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Ammonia (total),Ammonia,tonnes,Air Emissions / Émissions à l'air,Stack Emissions,0.636,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB1c6e015419
1,npri-1568-2023-2,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Arsenic (and its compounds),Arsenic,kg,Air Emissions / Émissions à l'air,Stack Emissions,0.116,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB0cbc90a094
2,npri-1568-2023-3,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Carbon monoxide,"Carbon monoxide, fossil",tonnes,Air Emissions / Émissions à l'air,Stack Emissions,76.208,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB642eab0862
3,npri-1568-2023-4,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Chromium (and its compounds),Chromium,tonnes,Air Emissions / Émissions à l'air,Stack Emissions,0.00105,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB7e3f017a30
4,npri-1568-2023-5,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Cobalt (and its compounds),Cobalt,kg,Air Emissions / Émissions à l'air,Stack Emissions,0.18,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUBd94d47b1d8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24125,npri-5697-2023-6,2023,5697,Rayette Manufacturing,None,manufacturing,-79.49600,43.80800,Mixedwood Plain,St. Lawrence Drainage Area,Speciated VOC - Hydrotreated heavy naphtha,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",25.1008,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49600 43.80800),SUBb215244183
24126,npri-5698-2023-6,2023,5698,Bowes Manufacturing,None,manufacturing,-79.49480,43.80360,Mixedwood Plain,St. Lawrence Drainage Area,Speciated VOC - Hydrotreated heavy naphtha,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",23.418,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49480 43.80360),SUBb215244183
24127,npri-34697-2023-2,2023,34697,541 Bowes Warehouse,None,manufacturing,-79.49707,43.81726,Mixedwood Plain,St. Lawrence Drainage Area,Speciated VOC - Hydrotreated heavy naphtha,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",16.543746,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49707 43.81726),SUBb215244183
24128,npri-5697-2023-7,2023,5697,Rayette Manufacturing,None,manufacturing,-79.49600,43.80800,Mixedwood Plain,St. Lawrence Drainage Area,Volatile Organic Compounds (Total),None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",12.5823,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49600 43.80800),SUB8319f60a2f
24129,npri-5698-2023-7,2023,5698,Bowes Manufacturing,None,manufacturing,-79.49480,43.80360,Mixedwood Plain,St. Lawrence Drainage Area,Volatile Organic Compounds (Total),None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",11.87719,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49480 43.80360),SUB8319f60a2f

In [20]:
env_df = env_df.merge(
    substance_table[['substance_id', 'original_name']],
    how='left',
    left_on='substance_name',
    right_on='original_name'
).drop(columns='original_name')

In [163]:
env_int_df = env_int_df.merge(
    substance_table[['substance_id', 'original_name']],
    how='left',
    left_on='substance_name',
    right_on='original_name'
).drop(columns='original_name')

In [21]:
# For CTrace and GHG datasets, we create a substance_id column = NaN because we do not have substance names, only flow_tyoe
ctrace_gdf['substance_id'] = np.nan
ghg_gdf['substance_id'] = np.nan

In [ ]:
substance_table = substance_table.rename(columns={'harmonized_name': 'substance_name'})
substance_table = substance_table[['substance_id', 'substance_name']]

In [261]:
substance_table.to_csv(r'database/CSV/substances_table.csv', index=False)

## Compartment table

In [23]:
pollutant_gdf[pollutant_gdf['emission_type'] == 'Water Releases / Rejets à l\'eau']['emission_subtype'].unique()

array(['Direct Discharge', 'Total', 'Receiving Waterbody (English)',
       'Receiving Waterbody (French)', 'Spills'], dtype=object)

In [24]:
# Change the value to 'None' for emission_subtype when emission_type = 'Water Releases / Rejets à l'eau' and 'emission_subtype' is 'Receiving Waterbody (English)' or 'Receiving Waterbody (French)'
pollutant_gdf.loc[
    (pollutant_gdf['emission_type'] == 'Water Releases / Rejets à l\'eau') & 
    (pollutant_gdf['emission_subtype'].isin(['Receiving Waterbody (English)', 'Receiving Waterbody (French)'])),
    'emission_subtype'
] = None

In [25]:
from db_creation_function import create_compartment_table

In [26]:
compartment_table = create_compartment_table(pollutant_gdf, env_df)

In [27]:
pollutant_gdf = pollutant_gdf.merge(
    compartment_table[[
        'compartment_id', 'raw_compartment_label', 'raw_pathway_label'
    ]],
    how='left',
    left_on=['emission_type', 'emission_subtype'],
    right_on=['raw_compartment_label', 'raw_pathway_label']
).drop(columns=['raw_compartment_label', 'raw_pathway_label'])

In [28]:
env_df['compartment_pathway'] = 'Unspecified'
env_df = env_df.merge(
    compartment_table[[
        'compartment_id', 'raw_compartment_label', 'raw_pathway_label'
    ]],
    how='left',
    left_on=['compartment', 'compartment_pathway'],
    right_on=['raw_compartment_label', 'raw_pathway_label']
).drop(columns=['raw_compartment_label', 'raw_pathway_label'])

In [164]:
env_int_df['compartment_pathway'] = 'Unspecified'
env_int_df = env_int_df.merge(
    compartment_table[[
        'compartment_id', 'raw_compartment_label', 'raw_pathway_label'
    ]],
    how='left',
    left_on=['compartment', 'compartment_pathway'],
    right_on=['raw_compartment_label', 'raw_pathway_label']
).drop(columns=['raw_compartment_label', 'raw_pathway_label'])

In [29]:
# For CTrace and GHG datasets, we assign the compartment_id corresponding to 'Air' and 'Unspecified' pathway
ctrace_gdf['compartment_id'] = 'CMPf3265e9fca'
ghg_gdf['compartment_id'] = 'CMPf3265e9fca'

In [264]:
compartment_table = compartment_table.rename(columns={'compartment': 'compartment_name'})
compartment_table = compartment_table[['compartment_id', 'compartment_name', 'compartment_pathway']]

In [346]:
compartment_table = compartment_table.drop_duplicates().reset_index(drop=True)

In [347]:
compartment_table.to_csv(r'database/CSV/compartments_table.csv', index=False)

# Matching

## Point to point matching

In [31]:
from matching_functions import match_facilities, one_to_many_relationships

### MinCan

In [32]:
# Let's keep only Active mines
min_can_gdf = min_can_gdf[min_can_gdf['mine_status'] == 'Active'].copy()

Some mines in MinCan dataset have very slightly different name (e.g. LaRonde - Zone 5 and LaRonde), the same name but one without town (e.g. Detour Lake) or several companies for the same mines.

In [33]:
# min_can_id = ON-MINCAN-6316d452 = Detour Lake = 2013 - open
# min_can_id = ON-MINCAN-7b832414 = Detour Lake = 1983 - open
# min_can_id = QC-MINCAN-775312a1 = LaRonde - Zone 5 = 2018 - open
# min_can_id = QC-MINCAN-8321e85e = LaRonde = 1988 - open

In [34]:
# We delete the duplicates, aligned with information from MDO for Detour Lake and LaRonde
min_can_gdf = min_can_gdf[~min_can_gdf['mincan_id'].isin(['ON-MINCAN-6316d452', 'QC-MINCAN-775312a1'])].copy()

In [35]:
min_can_gdf

,mincan_id,namemine,town,province,latitude,longitude,commodityall,information,mine_status,geometry,operation_periods,source_id
7,ON-MINCAN-ccf2bf99,Haley,Haley,Ontario,45.598880,-76.751710,Magnesium,None,Active,POINT (-76.75171 45.59888),1942–open,10.1038/s41597-024-03116-3
13,NB-MINCAN-63ccd128,Stratmat (Halfmile),None,New Brunswick,47.305278,-66.320000,"Zinc, Lead, Copper, Gold, Silver",indigenous participation,Active,POINT (-66.32000 47.30528),1951–open,10.1038/s41597-024-03116-3
18,ON-MINCAN-9abb16ea,Calcite Division,Perth,Ontario,45.149689,-76.498756,Calcium Carbonate,None,Active,POINT (-76.49876 45.14969),1962–open,10.1038/s41597-024-03116-3
23,QC-MINCAN-06b1f129,Parent Mica Deposit,Suzor,Quebec,47.938412,-74.634602,Mica,"Changed name in Lacana Mines Inc. ""In late 198...",Active,POINT (-74.63460 47.93841),1976–open,10.1038/s41597-024-03116-3
24,QC-MINCAN-227d3d18,Charlevoix,Charlevoix (Saint-Urbain),Quebec,47.749900,-70.696711,Silica,None,Active,POINT (-70.69671 47.74990),1977–open,10.1038/s41597-024-03116-3
...,...,...,...,...,...,...,...,...,...,...,...,...
923,BC-MINCAN-d8cf3b3a,None,Fort Langley,British Columbia,49.189659,-122.660599,Lime,None,Active,POINT (-122.66060 49.18966),1991–open,10.1038/s41597-024-03116-3
924,AB-MINCAN-bab4efd2,None,Exshaw,Alberta,51.071389,-115.135199,Lime,None,Active,POINT (-115.13520 51.07139),1991–open,10.1038/s41597-024-03116-3
927,SK-MINCAN-2aefa179,None,Hudson Bay,Saskatchewan,52.985830,-101.744038,Silica,small scale /// Lower Cretaceous Mannville Gro...,Active,POINT (-101.74404 52.98583),1993–open,10.1038/s41597-024-03116-3
935,NT-MINCAN-ea720725,Panda (Ekati Project),Lac de Gras,Northwest Territories,64.716667,-110.608333,Diamond,Brief closure between 2020 and 2021,Active,POINT (-110.60833 64.71667),1997–open,10.1038/s41597-024-03116-3
936,QC-MINCAN-8f0f7e05,Ardorbec,Danville,Quebec,45.748462,-71.961305,Magnesium,None,Active,POINT (-71.96130 45.74846),1998–open,10.1038/s41597-024-03116-3

In [36]:
lt_main_mincan = match_facilities(main_gdf, min_can_gdf,
                     id_col1='main_id', id_col2='mincan_id',
                     name_col1='facility_name', name_col2='namemine'
                     )

In [37]:
matches_main_mincan = one_to_many_relationships(
    lt_main_mincan,
    id_main_col='main_id',
    id_sat_col='mincan_id',
    distance_threshold_m=2000,
    similarity_threshold=80,
    similarity_metric="token_set"  
)

In [38]:
min_can_gdf = min_can_gdf.merge(
    matches_main_mincan,
    on="mincan_id", 
    how="left"
)

In [39]:
# For SQL
min_can_gdf = min_can_gdf[min_can_gdf["main_id"].notna()].copy()

In [40]:
col_to_keep = ["mincan_id", "main_id", "mine_status", "operation_periods"]
min_can_gdf = min_can_gdf[col_to_keep]
min_can_gdf

,mincan_id,main_id,mine_status,operation_periods
11,QC-MINCAN-494c7715,QC-MAIN-9de9bb0d,Active,1936–1996; 2005–2013; 2021–open
21,BC-MINCAN-8cc41b53,BC-MAIN-6b4800fe,Active,1972–1998; 2004–open
28,QC-MINCAN-8321e85e,QC-MAIN-e51eda66,Active,1988–open
29,ON-MINCAN-97f916de,ON-MAIN-c5fefb01,Active,2002–open
31,ON-MINCAN-49811fe2,ON-MAIN-687b8c8d,Active,2007–open
34,QC-MINCAN-44904232,QC-MAIN-c0660aec,Active,2008–2011; 2013–open
39,NU-MINCAN-1d9e43a7,NU-MAIN-730aefe3,Active,2010–open
41,ON-MINCAN-643672f4,ON-MAIN-f3e6ff08,Active,2011–open
42,SK-MINCAN-5ac4b2dd,SK-MAIN-22ce14be,Active,2011–open
44,BC-MINCAN-72fabc94,BC-MAIN-aa76f6f2,Active,2012–open
47,MB-MINCAN-15965632,MB-MAIN-be5b3dc8,Active,2013–open
48,ON-MINCAN-07ece30d,ON-MAIN-28f3f0fc,Active,2014–open
51,BC-MINCAN-4eaf1f96,BC-MAIN-ed23117f,Active,2014–open
53,QC-MINCAN-1c16c912,QC-MAIN-6dc537e6,Active,2015–open
54,BC-MINCAN-496a2682,BC-MAIN-8eb8be0d,Active,2015–open
55,SK-MINCAN-7501c939,SK-MAIN-91cf5448,Active,2015–open
56,QC-MINCAN-72adc1b6,QC-MAIN-3032c251,Active,2016–open
57,NS-MINCAN-21b5fbce,NS-MAIN-c9c77a59,Active,2017–open
58,ON-MINCAN-ddd10f1c,ON-MAIN-0aadf28f,Active,2017–open
60,BC-MINCAN-492cfeba,BC-MAIN-857b7b89,Active,2017–open
61,NT-MINCAN-ecb9b239,NT-MAIN-94e652a5,Active,2017–open
64,ON-MINCAN-079b81a1,ON-MAIN-f4fc3276,Active,2018–open
66,ON-MINCAN-b94b1f25,ON-MAIN-1c674cd0,Active,2019–open
68,QC-MINCAN-a6cbac08,QC-MAIN-b8c826a2,Active,2019–open
69,NU-MINCAN-6ca88e12,NU-MAIN-8b0264c9,Active,2019–open
70,YT-MINCAN-8fada64a,YT-MAIN-e05ed9fe,Active,2019–open
71,NU-MINCAN-4efe1cae,NU-MAIN-4ea8ac9d,Active,2019–open
80,NL-MINCAN-d8d4cf69,NL-MAIN-2d8801d6,Active,2005–open
84,QC-MINCAN-6f83c124,QC-MAIN-e7e6a960,Active,1935–1965; 2011–open
87,QC-MINCAN-a6163f93,QC-MAIN-d29e0839,Active,1956–1959; 1974–1975; 1988–open
91,QC-MINCAN-548f03a9,QC-MAIN-084bd95c,Active,1976–open
92,QC-MINCAN-cf418fe9,QC-MAIN-b86f7d07,Active,1988–1991; 1993–open
95,QC-MINCAN-a90e8433,QC-MAIN-a97821c0,Active,1998–open
102,BC-MINCAN-14ce4b06,BC-MAIN-599152a0,Active,1884–1958; 2011–open
103,ON-MINCAN-8c35080f,ON-MAIN-7607a50e,Active,1917–1957; 2010–open
104,ON-MINCAN-838ef03f,ON-MAIN-206041d1,Active,1962–1991; 2007–2009; 2010–open
105,BC-MINCAN-595f5049,BC-MAIN-23155c25,Active,1966–1985; 2002–2015; 2019–open
114,ON-MINCAN-cf9a5c80,ON-MAIN-1f126a43,Active,1933–1999; 2002–open
125,QC-MINCAN-13530c4c,QC-MAIN-649d2873,Active,1976–open
130,ON-MINCAN-1c3b8f14,ON-MAIN-cb85213a,Active,1983–open
132,ON-MINCAN-7b832414,ON-MAIN-aeafbb59,Active,1983–open
140,ON-MINCAN-69e999a0,ON-MAIN-fefeaee4,Active,1997–open
143,ON-MINCAN-fc444118,ON-MAIN-7f050560,Active,1949–open
149,ON-MINCAN-08e05315,ON-MAIN-f8313ebd,Active,1963–open
157,ON-MINCAN-7b29d7b3,ON-MAIN-bfbcd72e,Active,1987–1994; 2012–open

### CTrace

In [41]:
lt_main_ctrace = match_facilities(main_gdf, ctrace_gdf,
                     id_col1='main_id', id_col2='ctrace_id',
                     name_col1='facility_name', name_col2='source_name'
                     )

In [42]:
matches_main_ctrace = one_to_many_relationships(
    lt_main_ctrace,
    id_main_col='main_id',
    id_sat_col='ctrace_id',
    distance_threshold_m=2000,
    similarity_threshold=80,
    similarity_metric="token_set"  
)

In [43]:
ctrace_gdf = ctrace_gdf.merge(
    matches_main_ctrace,
    on="ctrace_id", 
    how="left"
)

In [44]:
# For SQL
ctrace_gdf = ctrace_gdf[ctrace_gdf["main_id"].notna()].copy()

In [45]:
ctrace_gdf.columns

Index(['ctrace_id', 'year', 'source_name', 'emissions_quantity', 'gas',
       'activity', 'activity_units', 'capacity', 'capacity_units', 'latitude',
       'longitude', 'geometry', 'source_id', 'substance_id', 'compartment_id',
       'main_id'],
      dtype='object')

In [46]:
col_to_keep = [
'ctrace_id', 
'year',
'emissions_quantity', 
'gas',
'activity', 'activity_units', 
'capacity', 'capacity_units', 
'source_id',  'substance_id', 'compartment_id',
'main_id'           
]
ctrace_gdf = ctrace_gdf[col_to_keep]
ctrace_gdf

,ctrace_id,year,emissions_quantity,gas,activity,activity_units,capacity,capacity_units,source_id,substance_id,compartment_id,main_id
6,1754055,2023,5.610000e+03,co2e_100yr,8.630000e+05,t of copper ore,4.624000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-6e9b2449
7,1754056,2023,6.403000e+03,co2e_100yr,9.850000e+05,t of copper ore,3.554700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-63b394c3
8,1754057,2023,2.299160e+05,co2e_100yr,1.457500e+07,t of copper ore,3.670000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-599152a0
9,1754058,2023,2.639000e+03,co2e_100yr,4.060000e+05,t of copper ore,1.104100e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-52224e1e
11,1754060,2023,4.225000e+03,co2e_100yr,6.500000e+05,t of copper ore,4.822000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-48fe2205
12,1754061,2023,1.316380e+05,co2e_100yr,8.810000e+07,t of copper ore,6.450000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-6b4800fe
16,1754066,2023,2.412130e+06,co2e_100yr,7.288600e+07,t of copper ore,2.631000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-30c1828c
25,1754077,2023,6.711600e+04,co2e_100yr,1.501481e+06,t of copper ore,1.988200e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-e51eda66
29,1754081,2023,7.782000e+03,co2e_100yr,5.279710e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,7.413000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,2.313000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,YT-MAIN-752fbcae
32,1754084,2023,7.956600e+04,co2e_100yr,2.127800e+07,t of copper ore,2.500250e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-ed23117f
33,1754085,2023,7.137900e+04,co2e_100yr,5.948239e+06,t of copper ore,4.902900e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-3f490561
34,1754086,2023,5.400000e+02,co2e_100yr,4.500000e+04,t of copper ore,4.110000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-23155c25
35,1754087,2023,1.590800e+04,co2e_100yr,2.993000e+06,t of copper ore,3.408700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-aa76f6f2
43,1754096,2023,8.219000e+03,co2e_100yr,6.848790e+05,t of copper ore,1.500000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-a97821c0
44,1754097,2023,8.451100e+04,co2e_100yr,6.887709e+06,t of copper ore,4.549000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-8eb8be0d
51,1754104,2023,3.367000e+03,co2e_100yr,5.180000e+05,t of copper ore,2.453000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-b2148882
54,25486533,2023,1.620000e+04,co2e_100yr,1.350000e+06,t of copper ore,2.500000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-f8313ebd
55,25486534,2023,5.914500e+04,co2e_100yr,3.798000e+06,t of copper ore,2.200000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-a3c56a83
56,36395102,2023,5.760720e+05,co2e_100yr,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-b64bae7a

In [47]:
# We separate emissions and production data
ctrace_ghg_gdf = ctrace_gdf.drop(columns=['activity', 'activity_units', 'capacity', 'capacity_units'])
ctrace_prod_gdf = ctrace_gdf.drop(columns=['emissions_quantity', 'gas'])

### Conflict

In [48]:
lt_main_conflict = match_facilities(main_gdf, conflict_gdf,
                     id_col1='main_id', id_col2='ej_atlas_id',
                     name_col1='facility_name', name_col2='facility_name_ejatlas'
                     )

In [49]:
matches_main_conflict = one_to_many_relationships(
    lt_main_conflict,
    id_main_col='main_id',
    id_sat_col='ej_atlas_id',
    distance_threshold_m=20000,
    similarity_threshold=80,
    similarity_metric="token_set"  # "partial" or "token_set"
)

In [50]:
conflict_gdf = conflict_gdf.merge(
    matches_main_conflict,
    on="ej_atlas_id",  
    how="left"
)

In [51]:
# For SQL
conflict_gdf = conflict_gdf[conflict_gdf["main_id"].notna()].copy()

In [52]:
col_to_keep = ["ej_atlas_id",
  "main_id",
  "case_name",
  "start_date",
  "end_date",
  "conflict_description",
  "conflict_details",
  "population_affected",
  "conflict_intensity",
  "project_status",
  "source_id"             
               ]
conflict_gdf = conflict_gdf[col_to_keep]
conflict_gdf

,ej_atlas_id,main_id,case_name,start_date,end_date,conflict_description,conflict_details,population_affected,conflict_intensity,project_status,source_id
9,4135,NL-MAIN-2d8801d6,"Vale Mining in Voisey's Bay, Labrador, Canada",11/1994,None,<p>Voiseyâ€™s Bay nickel mine in Labrador was ...,"Voiseyâ€™s Bay is a â€œ6,000 tonnes-per-day fa...",Rural,"MEDIUM (street protests, visible mobilization)",In operation,http://journals.librarypublishing.arizona.edu/...
10,4145,ON-MAIN-2e13aaa0,Port Colborne Class Action Lawsuit Against Val...,06/2000,04/2012,"<p>In Pearson (later Smith) v. Inco, the large...",Raw materials from Valeâ€™s Sudbury mining ope...,Urban,LOW (some local organising),In operation,http://journals.librarypublishing.arizona.edu/...
15,5599,QC-MAIN-d6748d40,Nouveau Mondeâ€™s Matawinie graphite mine in Q...,01/01/2017,None,<p>Five kilometers southwest of the municipali...,The project includes 319 mining concessions (c...,Rural,"MEDIUM (street protests, visible mobilization)",Under construction,http://journals.librarypublishing.arizona.edu/...

### Tailings

In [53]:
lt_main_tailings = match_facilities(main_gdf, tailings_gdf,
                     id_col1='main_id', id_col2='tailing_id',
                     name_col1='facility_name', name_col2='related_mine'
                     )

In [54]:
matches_main_tailings = one_to_many_relationships(
    lt_main_tailings,
    id_main_col='main_id',
    id_sat_col='tailing_id',
    distance_threshold_m=20000,
    similarity_threshold=80,
    similarity_metric="token_set"  # "partial" or "token_set"
)

In [55]:
tailings_gdf = tailings_gdf.merge(
    matches_main_tailings,
    on="tailing_id",  
    how="left"
)

In [56]:
# For SQL
tailings_gdf = tailings_gdf[tailings_gdf["main_id"].notna()].copy()

In [57]:
col_to_keep = [
  "row_id",
  "main_id",
  "year",
  "tailing_id",
  "tsf_name",
  "status",
  "construction_year",
  "raise_type",
  "current_maximum_height",
  "current_tailings_storage",
  "planned_storage_5_years",
  "hazard_categorization",
  "classification_system",
  "geometry", 
  "source_id"             
               ]
tailings_gdf = tailings_gdf[col_to_keep]
tailings_gdf

,row_id,main_id,year,tailing_id,tsf_name,status,construction_year,raise_type,current_maximum_height,current_tailings_storage,planned_storage_5_years,hazard_categorization,classification_system,geometry,source_id
0,TAIL-12.0-2019-1,NU-MAIN-730aefe3,2019,12.0,North Cell,Active,2009.0,"Downstream, Upstream",31.0,14400000,14400000,Medium,Canadian Dam Association,POINT (-96.04333 65.02156),https://tailing.grida.no/
1,TAIL-13.0-2019-1,NU-MAIN-730aefe3,2019,13.0,South Cell,Active,2012.0,Downstream,49.0,10420000,10420000,Medium,Canadian Dam Association,POINT (-96.03339 65.01378),https://tailing.grida.no/
2,TAIL-14.0-2019-1,NU-MAIN-730aefe3,2019,14.0,In pit,Active,2009.0,None,NaN,850000,850000,Low,None,POINT (-96.03254 65.00190),https://tailing.grida.no/
3,TAIL-15.0-2019-1,NU-MAIN-8b0264c9,2019,15.0,Meliadine TSF,Active,2019.0,None,5.0,89000,89000,Medium,Canadian Dam Association,POINT (-92.14034 63.02083),https://tailing.grida.no/
4,TAIL-16.0-2019-1,QC-MAIN-c0660aec,2019,16.0,South TSF,Active,2007.0,Not Raised,5.0,1664000,1664000,Medium,Canadian Dam Association,POINT (-77.84198 48.05434),https://tailing.grida.no/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,TAIL-1126.0-2019-1,ON-MAIN-f080c409,2019,1126.0,R1 Tailings,Active,1985.0,Compacted\nOuter Shell,14.0,2900000,2900000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
216,TAIL-1127.0-2019-1,ON-MAIN-f080c409,2019,1127.0,R2 Tailings,Active,1985.0,Compacted\nOuter Shell,13.0,18000000,18000000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
217,TAIL-1128.0-2019-1,ON-MAIN-f080c409,2019,1128.0,R3 Tailings,Active,1985.0,Compacted\nOuter Shell,27.0,39000000,39000000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
218,TAIL-1129.0-2019-1,ON-MAIN-f080c409,2019,1129.0,R4 Tailings,Active,1990.0,Compacted\nOuter Shell,22.0,59000000,59000000,Extreme,Canadian Dam Association,POINT (-81.14058 46.47142),https://tailing.grida.no/
226,TAIL-1243.0-2019-1,QC-MAIN-e7e6a960,2019,1243.0,Canadian Malartic TSF,Active,2012.0,Upstream,40.0,96000000,96000000,Medium to High,CDA/Yamana,POINT (-78.10361 48.11139),https://tailing.grida.no/

### GHG

In [58]:
lt_main_ghg = match_facilities(main_gdf, ghg_gdf,
                     id_col1='main_id', id_col2='ghg_id',
                     name_col1='facility_name', name_col2='facility_name_ghg'
                     )

In [59]:
matches_main_ghg = one_to_many_relationships(
    lt_main_ghg,
    id_main_col='main_id',
    id_sat_col='ghg_id',
    distance_threshold_m=10000,
    similarity_threshold=80,
    similarity_metric="token_set"  # "partial" or "token_set"
)

In [60]:
ghg_gdf = ghg_gdf.merge(
    matches_main_ghg,
    on="ghg_id",  
    how="left"
)

In [61]:
# For SQL
ghg_gdf = ghg_gdf[ghg_gdf["main_id"].notna()].copy()

In [62]:
col_to_keep = [
  "row_id",
  "main_id",
  "year",
  "value",
  "unit",
  "compartment_id",
  "substance_id",
  "source_id"             
               ]
ghg_gdf = ghg_gdf[col_to_keep]
ghg_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
1,GHG-10101-2022-1,NT-MAIN-6c1d6ee6,2022,164.88,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
4,GHG-10188-2022-1,QC-MAIN-084bd95c,2022,293.10,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
7,GHG-10240-2022-1,QC-MAIN-a97821c0,2022,129.26,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
8,GHG-10299-2022-1,QC-MAIN-e25eed27,2022,909.89,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
9,GHG-10350-2022-1,NL-MAIN-b64bae7a,2022,110.93,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
153,GHG-10791-2022-1,QC-MAIN-c1c7eb99,2022,96.48,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
154,GHG-10810-2022-1,NL-MAIN-d9036091,2022,50.09,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
169,GHG-11723-2022-1,ON-MAIN-2e13aaa0,2022,14.17,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
170,GHG-11730-2022-1,QC-MAIN-92628f16,2022,380.82,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
178,GHG-12298-2022-1,ON-MAIN-63b394c3,2022,330.67,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...

### Pollution

In [63]:
pollutant_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,substance_name_npri,substance_name_ecoinvent,substance_unit,emission_type,emission_subtype,value,source_id,geometry,substance_id,compartment_id
0,npri-1568-2023-1,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Ammonia (total),Ammonia,tonnes,Air Emissions / Émissions à l'air,Stack Emissions,0.636,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB1c6e015419,CMP1718f4466d
1,npri-1568-2023-2,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Arsenic (and its compounds),Arsenic,kg,Air Emissions / Émissions à l'air,Stack Emissions,0.116,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB0cbc90a094,CMP1718f4466d
2,npri-1568-2023-3,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Carbon monoxide,"Carbon monoxide, fossil",tonnes,Air Emissions / Émissions à l'air,Stack Emissions,76.208,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB642eab0862,CMP1718f4466d
3,npri-1568-2023-4,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Chromium (and its compounds),Chromium,tonnes,Air Emissions / Émissions à l'air,Stack Emissions,0.00105,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB7e3f017a30,CMP1718f4466d
4,npri-1568-2023-5,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,Cobalt (and its compounds),Cobalt,kg,Air Emissions / Émissions à l'air,Stack Emissions,0.18,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUBd94d47b1d8,CMP1718f4466d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24125,npri-5697-2023-6,2023,5697,Rayette Manufacturing,None,manufacturing,-79.49600,43.80800,Mixedwood Plain,St. Lawrence Drainage Area,Speciated VOC - Hydrotreated heavy naphtha,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",25.1008,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49600 43.80800),SUBb215244183,CMP281acc6045
24126,npri-5698-2023-6,2023,5698,Bowes Manufacturing,None,manufacturing,-79.49480,43.80360,Mixedwood Plain,St. Lawrence Drainage Area,Speciated VOC - Hydrotreated heavy naphtha,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",23.418,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49480 43.80360),SUBb215244183,CMP281acc6045
24127,npri-34697-2023-2,2023,34697,541 Bowes Warehouse,None,manufacturing,-79.49707,43.81726,Mixedwood Plain,St. Lawrence Drainage Area,Speciated VOC - Hydrotreated heavy naphtha,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",16.543746,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49707 43.81726),SUBb215244183,CMP281acc6045
24128,npri-5697-2023-7,2023,5697,Rayette Manufacturing,None,manufacturing,-79.49600,43.80800,Mixedwood Plain,St. Lawrence Drainage Area,Volatile Organic Compounds (Total),None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",12.5823,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49600 43.80800),SUB8319f60a2f,CMP281acc6045
24129,npri-5698-2023-7,2023,5698,Bowes Manufacturing,None,manufacturing,-79.49480,43.80360,Mixedwood Plain,St. Lawrence Drainage Area,Volatile Organic Compounds (Total),None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",11.87719,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49480 43.80360),SUB8319f60a2f,CMP281acc6045

In [64]:
lt_main_pollution = match_facilities(main_gdf, pollutant_gdf,
                     id_col1='main_id', id_col2='npri_id',
                     name_col1='facility_name', name_col2='facility_name_npri'
                     )

In [65]:
matches_main_pollution = one_to_many_relationships(
    lt_main_pollution,
    id_main_col='main_id',
    id_sat_col='npri_id',
    distance_threshold_m=10000,
    similarity_threshold=80,
    similarity_metric="token_set"  # "partial" or "token_set"
)

In [66]:
matches_main_pollution

       npri_id           main_id
16814  11588.0  ON-MAIN-fcb287a4
45019  11123.0  ON-MAIN-cb85213a
11963   6344.0  QC-MAIN-5398dfac
44365  11878.0  ON-MAIN-28f3f0fc
43960   1471.0  ON-MAIN-2e13aaa0
...        ...               ...
5206    1106.0  AB-MAIN-9fed34a8
40383  10199.0  ON-MAIN-6e9b2449
10102  20131.0  BC-MAIN-e34feb4d
12656  31260.0  QC-MAIN-5398dfac
42023    444.0  ON-MAIN-63b394c3

[80 rows x 2 columns]

In [67]:
pollutant_gdf = pollutant_gdf.merge(
    matches_main_pollution,
    on="npri_id",  
    how="left"
)

In [68]:
pollutant_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,...,substance_name_ecoinvent,substance_unit,emission_type,emission_subtype,value,source_id,geometry,substance_id,compartment_id,main_id
0,npri-1568-2023-1,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,...,Ammonia,tonnes,Air Emissions / Émissions à l'air,Stack Emissions,0.636,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB1c6e015419,CMP1718f4466d,ON-MAIN-1f126a43
1,npri-1568-2023-2,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,...,Arsenic,kg,Air Emissions / Émissions à l'air,Stack Emissions,0.116,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB0cbc90a094,CMP1718f4466d,ON-MAIN-1f126a43
2,npri-1568-2023-3,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,...,"Carbon monoxide, fossil",tonnes,Air Emissions / Émissions à l'air,Stack Emissions,76.208,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB642eab0862,CMP1718f4466d,ON-MAIN-1f126a43
3,npri-1568-2023-4,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,...,Chromium,tonnes,Air Emissions / Émissions à l'air,Stack Emissions,0.00105,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUB7e3f017a30,CMP1718f4466d,ON-MAIN-1f126a43
4,npri-1568-2023-5,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,...,Cobalt,kg,Air Emissions / Émissions à l'air,Stack Emissions,0.18,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),SUBd94d47b1d8,CMP1718f4466d,ON-MAIN-1f126a43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24125,npri-5697-2023-6,2023,5697,Rayette Manufacturing,None,manufacturing,-79.49600,43.80800,Mixedwood Plain,St. Lawrence Drainage Area,...,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",25.1008,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49600 43.80800),SUBb215244183,CMP281acc6045,NaN
24126,npri-5698-2023-6,2023,5698,Bowes Manufacturing,None,manufacturing,-79.49480,43.80360,Mixedwood Plain,St. Lawrence Drainage Area,...,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",23.418,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49480 43.80360),SUBb215244183,CMP281acc6045,NaN
24127,npri-34697-2023-2,2023,34697,541 Bowes Warehouse,None,manufacturing,-79.49707,43.81726,Mixedwood Plain,St. Lawrence Drainage Area,...,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",16.543746,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49707 43.81726),SUBb215244183,CMP281acc6045,NaN
24128,npri-5697-2023-7,2023,5697,Rayette Manufacturing,None,manufacturing,-79.49600,43.80800,Mixedwood Plain,St. Lawrence Drainage Area,...,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",12.5823,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49600 43.80800),SUB8319f60a2f,CMP281acc6045,NaN
24129,npri-5698-2023-7,2023,5698,Bowes Manufacturing,None,manufacturing,-79.49480,43.80360,Mixedwood Plain,St. Lawrence Drainage Area,...,None,tonnes,Grand Total,"Total Releases, Disposals and Transfers for Re...",11.87719,https://www.canada.ca/en/environment-climate-c...,POINT (-79.49480 43.80360),SUB8319f60a2f,CMP281acc6045,NaN

In [69]:
# For SQL
pollutant_gdf = pollutant_gdf[pollutant_gdf["main_id"].notna()].copy()

In [70]:
# # Adding terrestrial ecozone and watershed to the main_gdf
# main_gdf_b = main_gdf.merge(
#     pollutant_gdf[['main_id', 'terrestrial_ecozone', 'watershed']],
#     on='main_id',
#     how='left'
# )
# 
# # Adding NPRI source for the main_gdf where watershed and terrestrial ecozone are not null
# main_gdf['source_id'] = main_gdf.apply(
#     lambda row: row['source_id'] + ';' + 'https://www.canada.ca/en/environment-climate-change/services/national-pollutant-release-inventory/tools-resources-data/exploredata.html' if pd.notna(row['watershed']) or pd.notna(row['terrestrial_ecozone']) else row['source_id'],
#     axis=1
# )

In [71]:
col_to_keep = [
  "row_id",
  #"npri_id",
  "main_id",
  "year",
  "value",
  "substance_unit",
  "compartment_id",
  "substance_id",
  "source_id"
 ]
pollutant_gdf = pollutant_gdf[col_to_keep]
pollutant_gdf.rename(columns={'substance_unit': 'unit'}, inplace=True)
pollutant_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
0,npri-1568-2023-1,ON-MAIN-1f126a43,2023,0.636,tonnes,CMP1718f4466d,SUB1c6e015419,https://www.canada.ca/en/environment-climate-c...
1,npri-1568-2023-2,ON-MAIN-1f126a43,2023,0.116,kg,CMP1718f4466d,SUB0cbc90a094,https://www.canada.ca/en/environment-climate-c...
2,npri-1568-2023-3,ON-MAIN-1f126a43,2023,76.208,tonnes,CMP1718f4466d,SUB642eab0862,https://www.canada.ca/en/environment-climate-c...
3,npri-1568-2023-4,ON-MAIN-1f126a43,2023,0.00105,tonnes,CMP1718f4466d,SUB7e3f017a30,https://www.canada.ca/en/environment-climate-c...
4,npri-1568-2023-5,ON-MAIN-1f126a43,2023,0.18,kg,CMP1718f4466d,SUBd94d47b1d8,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
24116,npri-28761-2023-117,NL-MAIN-d9036091,2023,4.405,tonnes,CMP281acc6045,SUB4cedd6b899,https://www.canada.ca/en/environment-climate-c...
24117,npri-28761-2023-118,NL-MAIN-d9036091,2023,0.2475,tonnes,CMP281acc6045,SUBda6a6d231d,https://www.canada.ca/en/environment-climate-c...
24118,npri-28761-2023-119,NL-MAIN-d9036091,2023,29.277299999999997,tonnes,CMP281acc6045,SUB28f44d0e11,https://www.canada.ca/en/environment-climate-c...
24119,npri-28761-2023-120,NL-MAIN-d9036091,2023,0.485,tonnes,CMP281acc6045,SUBba3b5d11c7,https://www.canada.ca/en/environment-climate-c...
24120,npri-28761-2023-121,NL-MAIN-d9036091,2023,39.214054000000004,tonnes,CMP281acc6045,SUBae95939c3f,https://www.canada.ca/en/environment-climate-c...

In [72]:
pollutant_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
0,npri-1568-2023-1,ON-MAIN-1f126a43,2023,0.636,tonnes,CMP1718f4466d,SUB1c6e015419,https://www.canada.ca/en/environment-climate-c...
1,npri-1568-2023-2,ON-MAIN-1f126a43,2023,0.116,kg,CMP1718f4466d,SUB0cbc90a094,https://www.canada.ca/en/environment-climate-c...
2,npri-1568-2023-3,ON-MAIN-1f126a43,2023,76.208,tonnes,CMP1718f4466d,SUB642eab0862,https://www.canada.ca/en/environment-climate-c...
3,npri-1568-2023-4,ON-MAIN-1f126a43,2023,0.00105,tonnes,CMP1718f4466d,SUB7e3f017a30,https://www.canada.ca/en/environment-climate-c...
4,npri-1568-2023-5,ON-MAIN-1f126a43,2023,0.18,kg,CMP1718f4466d,SUBd94d47b1d8,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
24116,npri-28761-2023-117,NL-MAIN-d9036091,2023,4.405,tonnes,CMP281acc6045,SUB4cedd6b899,https://www.canada.ca/en/environment-climate-c...
24117,npri-28761-2023-118,NL-MAIN-d9036091,2023,0.2475,tonnes,CMP281acc6045,SUBda6a6d231d,https://www.canada.ca/en/environment-climate-c...
24118,npri-28761-2023-119,NL-MAIN-d9036091,2023,29.277299999999997,tonnes,CMP281acc6045,SUB28f44d0e11,https://www.canada.ca/en/environment-climate-c...
24119,npri-28761-2023-120,NL-MAIN-d9036091,2023,0.485,tonnes,CMP281acc6045,SUBba3b5d11c7,https://www.canada.ca/en/environment-climate-c...
24120,npri-28761-2023-121,NL-MAIN-d9036091,2023,39.214054000000004,tonnes,CMP281acc6045,SUBae95939c3f,https://www.canada.ca/en/environment-climate-c...

### Li et al land occupation

In [73]:
# li_canada_gdf_copy = li_canada_gdf.copy()
# li_canada_gdf_copy.rename(columns={'geometry': 'geometry_polygon'}, inplace=True)
# li_canada_gdf_copy["geometry"] = gpd.points_from_xy(li_canada_gdf_copy["Longitude"], li_canada_gdf_copy["Latitude"])
# li_canada_gdf_copy = li_canada_gdf_copy.set_geometry("geometry", crs="EPSG:4326")

In [74]:
# lt_main_li = match_facilities(main_gdf, li_canada_gdf_copy,
#                      id_col1='main_id', id_col2='li_id',
#                      name_col1='facility_name', name_col2='Name'
#                      )
# lt_main_li.to_excel(r'data/Sources/lt_main_li.xlsx', index=False)

In [75]:
matches_main_li = pd.read_excel(r'data/Sources/lt_main_li.xlsx', sheet_name='for_pandas')

In [76]:
li_canada_gdf = li_canada_gdf.merge(
    matches_main_li,
    on="li_id",  
    how="left"
)

In [77]:
li_canada_gdf

,li_id,Name,Latitude,Longitude,P_C,List_of_C,A_S,Country,State_Prov,Land_use,Cum_Prod,MI,geometry,source_id,main_id
0,QC-LI-91179bef,Ansil,48.366670,-79.116670,Copper,"Copper,Gold,Silver,Zinc",Inactive,Canada,Quebec,6.430820e+05,646039.0,100.459820,"MULTIPOLYGON Z (((-79.08135 48.35734 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,NaN
1,ON-LI-b4159d5a,Winston Lake,48.977500,-87.383610,Zinc,"Zinc,Copper,Gold,Silver",Inactive,Canada,Ontario,3.674623e+05,45600.0,12.409435,"POLYGON Z ((-87.37186 48.98162 0.00000, -87.37...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-3c468faa
2,QC-LI-71058cde,Abcourt-Barvue,48.521540,-77.679010,Zinc,"Zinc,Silver,Gold,Copper",Active,Canada,Quebec,8.480085e+05,248738.0,29.332017,"MULTIPOLYGON Z (((-77.66261 48.52210 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-5801b453
3,NS-LI-0ef10de8,Sterling,45.729170,-60.436940,Zinc,"Zinc,Lead,Copper,Silver,Gold",Inactive,Canada,Nova Scotia,2.375619e+05,486766.0,204.900724,"POLYGON Z ((-60.42757 45.72727 0.00000, -60.42...",https://www.nature.com/articles/s41597-025-052...,NaN
4,QC-LI-daf5c7b6,LaRonde,48.250560,-78.441670,Gold,"Gold,Silver,Zinc,Copper,Lead",Active,Canada,Quebec,5.150369e+06,192033.0,3.728529,"MULTIPOLYGON Z (((-78.43917 48.25134 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-e51eda66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,SK-LI-61977a89,Hanson Lake,54.673220,-102.861800,Copper,"Copper,Zinc,Lead,Silver",Active,Canada,Saskatchewan,2.547733e+04,207675.0,815.136583,"POLYGON Z ((-102.85598 54.67964 0.00000, -102....",https://www.nature.com/articles/s41597-025-052...,NaN
184,BC-LI-f95462e5,Texas,49.408240,-119.111560,Gold,"Gold,Silver,Copper,Lead,Zinc",Active,Canada,British Columbia,3.198705e+05,181497.0,56.740774,"POLYGON Z ((-119.09592 49.43913 0.00000, -119....",https://www.nature.com/articles/s41597-025-052...,NaN
185,ON-LI-8e5e6d12,Gowan,48.681165,-81.109475,Copper,"Copper,Silver,Zinc,Nickel",Active,Canada,Ontario,2.466126e+07,1195597.0,4.848077,"MULTIPOLYGON Z (((-81.07836 48.55417 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,NaN
186,ON-LI-ab2f9062,Genex,48.474010,-81.571480,Gold,"Gold,Copper,Zinc,Silver,Cobalt",Active,Canada,Ontario,2.071482e+05,544094.0,262.659331,"MULTIPOLYGON Z (((-81.56275 48.53520 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,NaN
187,QC-LI-81f5c1bf,Ledden,49.913630,-74.369950,Copper,"Copper,Gold",Active,Canada,Quebec,1.733646e+06,375998.0,21.688278,"MULTIPOLYGON Z (((-74.36829 49.95810 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,NaN

In [78]:
# For SQL
li_canada_gdf = li_canada_gdf[li_canada_gdf["main_id"].notna()].copy()

In [79]:
li_canada_gdf

,li_id,Name,Latitude,Longitude,P_C,List_of_C,A_S,Country,State_Prov,Land_use,Cum_Prod,MI,geometry,source_id,main_id
1,ON-LI-b4159d5a,Winston Lake,48.97750,-87.38361,Zinc,"Zinc,Copper,Gold,Silver",Inactive,Canada,Ontario,3.674623e+05,4.560000e+04,12.409435,"POLYGON Z ((-87.37186 48.98162 0.00000, -87.37...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-3c468faa
2,QC-LI-71058cde,Abcourt-Barvue,48.52154,-77.67901,Zinc,"Zinc,Silver,Gold,Copper",Active,Canada,Quebec,8.480085e+05,2.487380e+05,29.332017,"MULTIPOLYGON Z (((-77.66261 48.52210 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-5801b453
4,QC-LI-daf5c7b6,LaRonde,48.25056,-78.44167,Gold,"Gold,Silver,Zinc,Copper,Lead",Active,Canada,Quebec,5.150369e+06,1.920330e+05,3.728529,"MULTIPOLYGON Z (((-78.43917 48.25134 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-e51eda66
7,BC-LI-356e0fe7,Myra Falls,49.57394,-125.58518,Zinc,"Zinc,Lead,Copper,Silver,Gold",Active,Canada,British Columbia,1.499690e+06,2.262000e+05,15.083119,"POLYGON Z ((-125.59807 49.57709 0.00000, -125....",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-23155c25
9,NB-LI-4677c505,Murray Brook,47.52528,-66.43167,Zinc,"Zinc,Lead,Silver,Copper,Gold",Active,Canada,New Brunswick,2.552090e+05,1.460550e+05,57.229572,"POLYGON Z ((-66.42615 47.52543 0.00000, -66.42...",https://www.nature.com/articles/s41597-025-052...,NB-MAIN-8e04eb21
10,QC-LI-81c20425,Sleeping Giant,49.13115,-77.97601,Gold,"Gold,Silver,Copper,Zinc",Active,Canada,Quebec,1.113517e+06,1.825560e+05,16.394547,"POLYGON Z ((-77.97116 49.13362 0.00000, -77.97...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-d29e0839
12,ON-LI-28377156,Lac des Iles,49.15774,-89.61886,Palladium,"Palladium,Platinum,Gold,Copper,Nickel,Rhodium",Active,Canada,Ontario,8.409093e+06,5.573147e+04,0.662752,"MULTIPOLYGON Z (((-89.65770 49.16201 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-a3c56a83
13,QC-LI-22e70cb6,Goldex,48.09250,-77.87250,Gold,"Gold,Silver,Copper",Active,Canada,Quebec,1.341835e+06,4.717560e+05,35.157522,"MULTIPOLYGON Z (((-77.86273 48.09418 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-c0660aec
14,QC-LI-07027dd8,Westwood,48.25519,-78.50213,Gold,"Gold,Copper,Zinc,Silver",Active,Canada,Quebec,7.249147e+06,4.024100e+05,5.551136,"MULTIPOLYGON Z (((-78.54047 48.26526 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-02884fb5
18,ON-LI-0825b8aa,Red Lake,51.06098,-93.73213,Gold,"Gold,Copper,Silver",Active,Canada,Ontario,6.139378e+06,1.242835e+06,20.243661,"MULTIPOLYGON Z (((-93.75149 51.07450 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-7f050560
21,BC-LI-53364ff0,Copper Mountain,49.33884,-120.53599,Copper,"Copper,Gold,Silver",Active,Canada,British Columbia,1.323321e+07,1.470000e+06,11.108416,"MULTIPOLYGON Z (((-120.53945 49.34078 0.00000,...",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-599152a0
27,QC-LI-a160f62a,LaRonde Zone 5,48.25246,-78.47266,Gold,"Gold,Copper,Silver,Zinc",Active,Canada,Quebec,4.240549e+05,1.422730e+05,33.550609,"POLYGON Z ((-78.46721 48.24976 0.00000, -78.46...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-e51eda66
38,BC-LI-a5c8b930,Highland Valley,50.48556,-121.04722,Copper,"Copper,Molybdenum,Silver,Gold",Active,Canada,British Columbia,6.392426e+07,8.364983e+06,13.085772,"MULTIPOLYGON Z (((-120.99509 50.51731 0.00000,...",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-bf503b6b
39,BC-LI-b39bcd09,Gibraltar,52.51639,-122.28341,Copper,"Copper,Molybdenum,Silver,Gold",Active,Canada,British Columbia,2.252800e+07,1.251920e+06,5.557174,"MULTIPOLYGON Z (((-122.26933 52.53500 0.00000,...",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-6b4800fe
43,BC-LI-f2cf05dc,Mount Polley,52.54506,-121.63292,Copper,"Copper,Gold,Silver",Active,Canada,British Columbia,7.967835e+06,2.653931e+05,3.330806,"MULTIPOLYGON Z (((-121.64123 52.53456 0.00000,...",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-3f490561
44,BC-LI-62850c01,Eskay Creek,56.64630,-130.44214,Gold,"Gold,Silver,Copper,Lead,Zinc,Antimony,Arsenic,...",Active,Canada,British Columbia,7.707949e+04,1.971670e+05,255.796981,"POLYGON Z ((-130.42792 56.65497 0.00000, -130....",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-b1fe389a
45,BC-LI-69fbeec0,New Afton,50.66056,-120.51361,Gold,"Gold,Copper,Silver,Palladium",Active,Canada,British Columbia,4.950460e+06,9.961360e+05,20.122090,"POLYGON Z ((-120.50849 50.66585 0.00000, -120....",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-aa76f6f2
46,QC-LI-c4bafa7b,Horne 5,48.25425,-79.00953,Gold,"Gold,Copper,Zinc,Silver,Nickel",Active,Canada,Quebec,3.704188e+06,9.605290e+05,25.930891,"MULTIPOLYGON Z (((-78.97849 48.26789 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-30c1828c
47,BC-LI-38a92ebf,Mount Milligan,55.11806,-124.03111,Copper,"Copper,Gold,Silver",Active,Canada,British Columbia,1.260679e+07,3.094550e+05,2.454670,"POLYGON Z ((-123.98510 55.13948 0.00000, -123....",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-ed23117f
57,MB-LI-2b2d142c,Lynn Lake,56.82115,-101.03294,Nickel,"Nickel,Copper,Cobalt,Platinum,Zinc,Lead,Silver...",Active,Canada,Manitoba,5.260796e+06,1.311499e+06,24.929667,"MULTIPOLYGON Z (((-100.97073 56.87094 0.00000,...",https://www.nature.com/articles/s41597-025-052...,MB-MAIN-6fca9d6d
67,ON-LI-232fddc4,Ontario Division,46.49222,-81.06667,Nickel,"Nickel,Copper,Rhodium,Cobalt,Platinum,Palladiu...",Active,Canada,Ontario,2.159125e+07,9.420397e+06,43.630625,"MULTIPOLYGON Z (((-81.13563 46.48732 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-f080c409
68,ON-LI-232fddc4,Ontario Division,46.49222,-81.06667,Nickel,"Nickel,Copper,Rhodium,Cobalt,Platinum,Palladiu...",Active,Canada,Ontario,2.159125e+07,9.420397e+06,43.630625,"MULTIPOLYGON Z (((-81.13563 46.48732 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-de2f9639
69,QC-LI-a1ac6320,Troilus,51.01024,-74.46643,Gold,"Gold,Copper,Silver",Temporarily On Hold,Canada,Quebec,9.487628e+06,7.329273e+04,0.772508,"MULTIPOLYGON Z (((-74.48351 51.00345 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-b2148882
79,ON-LI-d9b37843,Nickel Rim South,46.65800,-80.79700,Nickel,"Nickel,Copper,Cobalt,Platinum,Palladium,Gold,S...",Active,Canada,Ontario,2.920384e+05,1.485610e+05,50.870363,"MULTIPOLYGON Z (((-80.79782 46.67513 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-fcb287a4
83,ON-LI-535c4fbd,Nickel Rim South,46.65800,-80.79700,Nickel,"Nickel,Copper,Cobalt,Platinum,Palladium,Gold,S...",Active,Canada,Ontario,1.496369e+06,3.468220e+05,23.177566,"MULTIPOLYGON Z (((-80.80209 46.60910 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-fcb287a4
85,BC-LI-ee31292d,Red Chris,57.70019,-129.80495,Copper,"Copper,Gold,Silver",Active,Canada,British Columbia,1.153165e+07,4.374000e+05,3.793040,"MULTIPOLYGON Z (((-129.72184 57.75056 0.00000,...",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-8eb8be0d
87,NL-LI-05d5336d,Voisey's Bay,56.33024,-62.09573,Nickel,"Nickel,Copper,Cobalt",Active,Canada,Newfoundland and Labrador,4.789014e+06,5.588060e+05,11.668498,"MULTIPOLYGON Z (((-62.09272 56.37773 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,NL-MAIN-2d8801d6
103,ON-LI-2752f4ec,Sudbury Operations,46.63626,-81.39866,Copper,"Copper,Nickel,Platinum,Palladium,Gold,Cobalt,R...",Active,Canada,Ontario,9.891461e+05,6.000000e+05,60.658382,"MULTIPOLYGON Z (((-81.41883 46.66474 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-7001a391
114,MB-LI-b5e1ad74,Lalor Lake,54.86562,-100.15120,Zinc,"Zinc,Copper,Gold,Silver",Active,Canada,Manitoba,3.634383e+05,2.949450e+05,81.154078,"MULTIPOLYGON Z (((-100.14013 54.86711 0.00000,...",https://www.nature.com/articles/s41597-025-052...,MB-MAIN-be5b3dc8
119,ON-LI-1c9fdf31,Crean Hill,46.42933,-81.35099,Nickel,"Nickel,Copper,Cobalt,Platinum,Palladium,Gold",Active,Canada,Ontario,3.862308e+05,8.553000e+04,22.144790,"MULTIPOLYGON Z (((-81.35071 46.42285 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-b1d981ca
120,ON-LI-d9dec6c8,Victoria,46.41667,-81.38333,Nickel,"Nickel,Copper,Gold,Silver,Cobalt,Platinum,Pall...",Active,Canada,Ontario,2.425190e+05,2.825110e+05,116.490271,"POLYGON Z ((-81.38100 46.41148 0.00000, -81.38...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-9a34108c
124,QC-LI-219a2e44,Horne 5,48.25425,-79.00953,Gold,"Gold,Copper,Zinc,Silver,Nickel",Active,Canada,Quebec,2.926809e+06,2.987480e+05,10.207294,"MULTIPOLYGON Z (((-79.08482 48.22969 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-30c1828c
130,BC-LI-9c3aa818,Eskay Creek,56.64630,-130.44214,Gold,"Gold,Silver,Copper,Lead,Zinc,Antimony,Arsenic,...",Active,Canada,British Columbia,1.226440e+05,3.188080e+05,259.945835,"POLYGON Z ((-130.49620 56.64851 0.00000, -130....",https://www.nature.com/articles/s41597-025-052...,BC-MAIN-b1fe389a
143,ON-LI-1a9a061c,Kidd Claims,48.69000,-81.36000,Copper,"Copper,Zinc,Lead,Silver",Inactive,Canada,Ontario,4.202254e+06,2.610000e+06,62.109532,"MULTIPOLYGON Z (((-81.36899 48.67882 0.00000, ...",https://www.nature.com/articles/s41597-025-052...,ON-MAIN-f8313ebd
157,QC-LI-94bd8222,Casa Berardi,49.55453,-79.19476,Gold,"Gold,Copper,Zinc,Lead",Inactive,Canada,Quebec,6.202897e+06,4.851480e+05,7.821313,"POLYGON Z ((-79.22196 49.57467 0.00000, -79.22...",https://www.nature.com/articles/s41597-025-052...,QC-MAIN-b86f7d07
159,MB-LI-3e566fc3,Lynn Lake,56.82115,-101.03294,Nickel,"Nickel,Copper,Cobalt,Platinum,Zinc,Lead,Silver...",Active,Canada,Manitoba,4.096435e+05,3.737930e+05,91.248363,"MULTIPOLYGON Z (((-101.09514 56.81934 0.00000,...",https://www.nature.com/articles/s41597-025-052...,MB-MAIN-6fca9d6d

## Point to polygon matching

### Protected lands datasets

In [80]:
from matching_functions import associate_facilities_near_polygons

In [81]:
wpda_gdf_polygons

,WDPA_PID,NAME,DESIG,OWN_TYPE,MANG_AUTH,STATUS_YR,geometry,source_id
0,611_A,Wood Buffalo National Park Of Canada,National Park,State,Parks Canada Agency,1922,"POLYGON ((-112.87253 59.99877, -111.53006 59.7...",https://www.protectedplanet.net
1,611_B,Wood Buffalo National Park Of Canada,National Park,State,Parks Canada Agency,1922,"POLYGON ((-112.87253 59.99877, -115.58450 59.9...",https://www.protectedplanet.net
2,612,Kluane National Park Reserve Of Canada,National Park,State,Parks Canada Agency,1972,"POLYGON ((-141.00187 60.30634, -137.43466 60.7...",https://www.protectedplanet.net
3,613_B,Auyuittuq National Park Of Canada,National Park,State,Parks Canada Agency,1972,"MULTIPOLYGON (((-64.62292 67.13706, -63.92605 ...",https://www.protectedplanet.net
4,613_A,Auyuittuq National Park Of Canada,National Park,State,Parks Canada Agency,1972,"MULTIPOLYGON (((-68.23194 67.76712, -67.56846 ...",https://www.protectedplanet.net
...,...,...,...,...,...,...,...,...
13463,555785733,Grosse Île and the Irish Memorial National His...,Lieu historique national,State,Parks Canada Agency,2023,"MULTIPOLYGON (((-70.67843 47.01639, -70.67802 ...",https://www.protectedplanet.net
13464,555785734,Navy Island National Historic Site,National Historic Site,State,Parks Canada Agency,2023,"POLYGON ((-79.01037 43.04900, -79.00871 43.060...",https://www.protectedplanet.net
13465,555785735,Fort George National Historic Site (Paradise G...,National Historic Site,State,Parks Canada Agency,2023,"POLYGON ((-79.06782 43.24368, -79.05901 43.248...",https://www.protectedplanet.net
13466,555785736,Rideau Canal National Historic Site,National Historic Site,State,Parks Canada Agency,2023,"MULTIPOLYGON (((-76.24341 44.90190, -76.19385 ...",https://www.protectedplanet.net
13467,555785737,Capital Recreation Area,OECM,State,National Capital Commission (NCC),2023,"POLYGON ((-75.60920 45.33843, -75.61502 45.332...",https://www.protectedplanet.net

In [82]:
lt_wpda = associate_facilities_near_polygons(
    main_gdf,
    wpda_gdf_polygons,
    facility_id_col="main_id",
    polygon_id_col="WDPA_PID",
    buffer_km=50,
    crs="EPSG:3978"
)

In [83]:
wpda_gdf_polygons = wpda_gdf_polygons.merge(lt_wpda, on="WDPA_PID", how="left")

In [84]:
# For SQL
wpda_gdf_polygons = wpda_gdf_polygons[wpda_gdf_polygons["main_id"].notna()].copy()

In [85]:
lt_indigenous = associate_facilities_near_polygons(
    main_gdf,
    indigenous_can_gdf,
    facility_id_col="main_id",
    polygon_id_col="indigenous_land_id",
    buffer_km=50,
    crs="EPSG:3978"
)

In [86]:
indigenous_can_gdf = indigenous_can_gdf.merge(lt_indigenous, on="indigenous_land_id", how="left")

In [87]:
# For SQL
indigenous_can_gdf = indigenous_can_gdf[indigenous_can_gdf["main_id"].notna()].copy()

### Land occupation footprint datasets

In [284]:
from matching_functions import assign_polygons_to_points

In [285]:
main_gdf

,main_id,facility_name,facility_group_name,facility_group_id,reported_company,company_name_folder,company_id,longitude,latitude,geometry,...,province,status,activity_status,development_stage,facility_type,mining_processing_type,commodity_group,primary_commodity,commodities,source_id
0,QC-MAIN-5801b453,Abcourt-Barvue,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.679010,48.521540,POINT (-77.67901 48.52154),...,Quebec,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, silver",None
1,QC-MAIN-d29e0839,Sleeping Giant,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.974340,49.132590,POINT (-77.97434 49.13259),...,Quebec,active_facility,None,None,mining,Concentrator,Precious metals,Gold,"Gold, silver",None
2,QC-MAIN-f1ff4920,Akasaba West,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-77.580000,48.040000,POINT (-77.58000 48.04000),...,Quebec,project_facility,Active,Advanced project,project,None,None,Gold,"Gold, copper",None
3,NU-MAIN-4ea8ac9d,Amaruq,Meadowbank complex,GRP-0a2c0d69,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-96.697000,65.415000,POINT (-96.69700 65.41500),...,Nunavut,active_facility,None,None,mining,"Open-pit, underground",Precious metals,Gold,Gold,None
4,QC-MAIN-e7e6a960,Canadian Malartic,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-78.130824,48.122223,POINT (-78.13082 48.12222),...,Quebec,active_facility,None,None,mining,"Open-pit, concentrator",Precious metals,Gold,"Gold, silver",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,None,None,Wesdome Gold Mines Ltd.,Wesdome Gold Mines Ltd,CMP-3d2c4955,-85.452500,48.110280,POINT (-85.45250 48.11028),...,Ontario,active_facility,None,None,mining,Open-pit,Precious metals,Gold,Gold,None
266,BC-MAIN-feb13c30,Record Ridge,None,None,West High Yield Resources Ltd.,West High Yield Resources Ltd,CMP-1023f9c0,-117.884000,49.082000,POINT (-117.88400 49.08200),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Magnesium,Magnesium,None
267,YT-MAIN-5e0d8b48,Casino,None,None,Western Copper and Gold Corporation,Western Copper and Gold Corporation,CMP-2dac9896,-138.833330,62.733330,POINT (-138.83333 62.73333),...,Yukon,project_facility,Active,Advanced project,project,None,None,Copper,"Copper, gold, molybdenum, silver",None
268,ON-MAIN-12c68d49,Eagle's Nest,None,None,Wyloo,Wyloo,CMP-65b36728,-86.303800,52.742020,POINT (-86.30380 52.74202),...,Ontario,project_facility,Active,Advanced project,project,None,None,Nickel,"Nickel, copper, gold, platinum, palladium",None
269,BC-MAIN-891d3cb5,Akie,None,None,ZincX Resources Corp.,ZincX Resources Corp,CMP-3416049b,-124.865990,57.380880,POINT (-124.86599 57.38088),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, lead, silver",None

In [286]:
assigned_df = assign_polygons_to_points(
    main_gdf,
    tailings_gdf,
    tang_canada_gdf,
    max_dist_km=10
)

In [287]:
assigned_df

              main_id  tailing_id  tang_id  distance_km relation_type
0    NS-MAIN-c9c77a59         NaN    45954     0.000000   one-to-many
1    NS-MAIN-c9c77a59         NaN    45955     1.186584   one-to-many
2    NL-MAIN-d9036091         NaN     7631     0.811781   one-to-many
3    NL-MAIN-d9036091         NaN     7641     4.647047   one-to-many
4    NL-MAIN-d9036091         NaN     7633     0.000000   many-to-one
..                ...         ...      ...          ...           ...
789  NT-MAIN-6c1d6ee6         NaN    26078     2.857250   one-to-many
790  NT-MAIN-6c1d6ee6         NaN    43740     0.833606   one-to-many
791  NT-MAIN-6c1d6ee6         NaN     3479     0.000000   one-to-many
792  NT-MAIN-6c1d6ee6         NaN    50385     2.150861   one-to-many
793  NT-MAIN-6c1d6ee6         NaN    26137     4.650487   one-to-many

[794 rows x 5 columns]

In [288]:
assigned_df['relation_type'].value_counts()

relation_type
one-to-many    707
many-to-one     56
one-to-one      31
Name: count, dtype: int64

In [290]:
polygon_gdf = tang_canada_gdf.merge(assigned_df, on="tang_id", how="left")

In [291]:
polygon_gdf

,tang_id,geometry,area_km2,source_id,main_id,tailing_id,distance_km,relation_type
0,6383,"POLYGON Z ((1795479.979 -83564.531 0.000, 1795...",0.026130,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
1,6388,"POLYGON Z ((1796123.448 -80625.526 0.000, 1796...",0.671399,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
2,6390,"POLYGON Z ((1796791.634 -80270.697 0.000, 1796...",0.050909,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
3,45954,"POLYGON Z ((2466485.124 185586.547 0.000, 2466...",2.622800,https://doi.org/10.1038/s43247-023-00805-6,NS-MAIN-c9c77a59,NaN,0.000000,one-to-many
4,45955,"POLYGON Z ((2465809.682 185862.507 0.000, 2465...",0.441869,https://doi.org/10.1038/s43247-023-00805-6,NS-MAIN-c9c77a59,NaN,1.186584,one-to-many
...,...,...,...,...,...,...,...,...
1915,3399,"POLYGON Z ((-717210.659 1915423.857 0.000, -71...",0.541024,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
1916,3401,"POLYGON Z ((-715648.337 1916385.463 0.000, -71...",1.053173,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
1917,26364,"POLYGON Z ((-717332.782 1916999.286 0.000, -71...",0.079894,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
1918,43739,"POLYGON Z ((-713032.430 1919630.086 0.000, -71...",1.519488,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
1919,44287,"POLYGON Z ((-466746.640 2074582.808 0.000, -46...",0.121349,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN

In [95]:
from visualization_functions import plot_polygons_assginment

In [96]:
plot_polygons_assginment(
    main_gdf,
    tailings_gdf,
    polygon_gdf, 
    output_html="results/data_coverage/facilities_tailings_maps.html"
)

✅ Map saved to results/data_coverage/facilities_tailings_maps.html

# Create final tables

## Main table

In [292]:
main_gdf

,main_id,facility_name,facility_group_name,facility_group_id,reported_company,company_name_folder,company_id,longitude,latitude,geometry,...,province,status,activity_status,development_stage,facility_type,mining_processing_type,commodity_group,primary_commodity,commodities,source_id
0,QC-MAIN-5801b453,Abcourt-Barvue,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.679010,48.521540,POINT (-77.67901 48.52154),...,Quebec,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, silver",None
1,QC-MAIN-d29e0839,Sleeping Giant,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.974340,49.132590,POINT (-77.97434 49.13259),...,Quebec,active_facility,None,None,mining,Concentrator,Precious metals,Gold,"Gold, silver",None
2,QC-MAIN-f1ff4920,Akasaba West,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-77.580000,48.040000,POINT (-77.58000 48.04000),...,Quebec,project_facility,Active,Advanced project,project,None,None,Gold,"Gold, copper",None
3,NU-MAIN-4ea8ac9d,Amaruq,Meadowbank complex,GRP-0a2c0d69,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-96.697000,65.415000,POINT (-96.69700 65.41500),...,Nunavut,active_facility,None,None,mining,"Open-pit, underground",Precious metals,Gold,Gold,None
4,QC-MAIN-e7e6a960,Canadian Malartic,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-78.130824,48.122223,POINT (-78.13082 48.12222),...,Quebec,active_facility,None,None,mining,"Open-pit, concentrator",Precious metals,Gold,"Gold, silver",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,None,None,Wesdome Gold Mines Ltd.,Wesdome Gold Mines Ltd,CMP-3d2c4955,-85.452500,48.110280,POINT (-85.45250 48.11028),...,Ontario,active_facility,None,None,mining,Open-pit,Precious metals,Gold,Gold,None
266,BC-MAIN-feb13c30,Record Ridge,None,None,West High Yield Resources Ltd.,West High Yield Resources Ltd,CMP-1023f9c0,-117.884000,49.082000,POINT (-117.88400 49.08200),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Magnesium,Magnesium,None
267,YT-MAIN-5e0d8b48,Casino,None,None,Western Copper and Gold Corporation,Western Copper and Gold Corporation,CMP-2dac9896,-138.833330,62.733330,POINT (-138.83333 62.73333),...,Yukon,project_facility,Active,Advanced project,project,None,None,Copper,"Copper, gold, molybdenum, silver",None
268,ON-MAIN-12c68d49,Eagle's Nest,None,None,Wyloo,Wyloo,CMP-65b36728,-86.303800,52.742020,POINT (-86.30380 52.74202),...,Ontario,project_facility,Active,Advanced project,project,None,None,Nickel,"Nickel, copper, gold, platinum, palladium",None
269,BC-MAIN-891d3cb5,Akie,None,None,ZincX Resources Corp.,ZincX Resources Corp,CMP-3416049b,-124.865990,57.380880,POINT (-124.86599 57.38088),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, lead, silver",None

In [293]:
ownership_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Ownership')

In [294]:
# Integrate ownership information into the main_gdf 
main_gdf = main_gdf.merge(
    ownership_df[['main_id', 'owner(s)', 'operator(s)', 'company_URL', 'company_facility_URL', 'MDO_URL']],
    on='main_id',
    how='left'
)

In [295]:
# # Integrate the operation_periods from min_can_gdf into the main_gdf
main_gdf = main_gdf.merge(
     min_can_gdf[['main_id', 'operation_periods']],
     on='main_id',
     how='left'
 )
# 
# # Add the source_id for MinCan only where operation_periods are not null
main_gdf['source_id'] = main_gdf.apply(
     lambda row: row['source_id'] + ';' + 'https://doi.org/10.1038/s41597-024-03116-3' if pd.notna(row['operation_periods']) else row['source_id'],
     axis=1
 )

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

In [101]:
main_gdf

,main_id,facility_name,facility_group_name,facility_group_id,reported_company,company_name_folder,company_id,longitude,latitude,geometry,...,commodity_group,primary_commodity,commodities,source_id,owner(s),operator(s),company_URL,company_facility_URL,MDO_URL,operation_periods
0,QC-MAIN-5801b453,Abcourt-Barvue,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.679010,48.521540,POINT (-77.67901 48.52154),...,None,Zinc,"Zinc, silver",https://open.canada.ca/data/en/dataset/22b2db8...,NaN,NaN,NaN,NaN,NaN,NaN
1,QC-MAIN-d29e0839,Sleeping Giant,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.974340,49.132590,POINT (-77.97434 49.13259),...,Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...,Abcourt Mines Inc (100%),Abcourt Mines Inc,https://abcourt.info/,https://abcourt.info/projects/the-sleeping-gia...,https://miningdataonline.com/property/1589/Sle...,1956–1959; 1974–1975; 1988–open
2,QC-MAIN-f1ff4920,Akasaba West,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-77.580000,48.040000,POINT (-77.58000 48.04000),...,None,Gold,"Gold, copper",https://open.canada.ca/data/en/dataset/22b2db8...,NaN,NaN,https://agnicoeagle.com/Home/default.aspx,https://www.agnicoeagle.com/English/operations...,https://miningdataonline.com/property/47/Meado...,NaN
3,NU-MAIN-4ea8ac9d,Amaruq,Meadowbank complex,GRP-0a2c0d69,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-96.697000,65.415000,POINT (-96.69700 65.41500),...,Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...,Agnico Eagle Mines Limited (100%),Agnico Eagle Mines Limited,https://agnicoeagle.com/Home/default.aspx,https://www.agnicoeagle.com/English/operations...,https://miningdataonline.com/property/46/LaRon...,2019–open
4,QC-MAIN-e7e6a960,Canadian Malartic,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-78.130824,48.122223,POINT (-78.13082 48.12222),...,Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...,Agnico Eagle Mines Limited (100%),Agnico Eagle Mines Limited,https://agnicoeagle.com/Home/default.aspx,https://www.agnicoeagle.com/English/operations...,https://miningdataonline.com/property/13/Detou...,1935–1965; 2011–open
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,None,None,Wesdome Gold Mines Ltd.,Wesdome Gold Mines Ltd,CMP-3d2c4955,-85.452500,48.110280,POINT (-85.45250 48.11028),...,Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...,Wesdome Gold Mines Ltd (100%),NaN,https://www.wesdome.com/English/overview/defau...,https://www.wesdome.com/English/operations/kie...,https://miningdataonline.com/property/3048/Kie...,2002–open
266,BC-MAIN-feb13c30,Record Ridge,None,None,West High Yield Resources Ltd.,West High Yield Resources Ltd,CMP-1023f9c0,-117.884000,49.082000,POINT (-117.88400 49.08200),...,None,Magnesium,Magnesium,https://open.canada.ca/data/en/dataset/22b2db8...,NaN,NaN,NaN,NaN,NaN,NaN
267,YT-MAIN-5e0d8b48,Casino,None,None,Western Copper and Gold Corporation,Western Copper and Gold Corporation,CMP-2dac9896,-138.833330,62.733330,POINT (-138.83333 62.73333),...,None,Copper,"Copper, gold, molybdenum, silver",https://open.canada.ca/data/en/dataset/22b2db8...,NaN,NaN,NaN,NaN,NaN,NaN
268,ON-MAIN-12c68d49,Eagle's Nest,None,None,Wyloo,Wyloo,CMP-65b36728,-86.303800,52.742020,POINT (-86.30380 52.74202),...,None,Nickel,"Nickel, copper, gold, platinum, palladium",https://open.canada.ca/data/en/dataset/22b2db8...,NaN,NaN,NaN,NaN,NaN,NaN
269,BC-MAIN-891d3cb5,Akie,None,None,ZincX Resources Corp.,ZincX Resources Corp,CMP-3416049b,-124.865990,57.380880,POINT (-124.86599 57.38088),...,None,Zinc,"Zinc, lead, silver",https://open.canada.ca/data/en/dataset/22b2db8...,NaN,NaN,NaN,NaN,NaN,NaN

In [296]:
main_gdf.rename(columns={
    'company_name_folder': 'company_name',
    'company_facility_URL': 'facility_URL'
}, inplace=True)

In [297]:
column_order = [
       'main_id', 'facility_name', 'facility_group_id', 'facility_group_name', 'company_id', 'company_name',
       'city', 'province', 'geometry',
       'status', 'activity_status', 'development_stage', 'facility_type', 'mining_processing_type',
       'commodity_group', 'commodities',
       'owner(s)', 'operator(s)', 'operation_periods', 
       'company_URL', 'facility_URL', 'MDO_URL', 
       'source_id'
]

In [298]:
# Fix column orders
main_gdf = main_gdf[column_order].copy()

In [299]:
main_gdf

,main_id,facility_name,facility_group_id,facility_group_name,company_id,company_name,city,province,geometry,status,...,mining_processing_type,commodity_group,commodities,owner(s),operator(s),operation_periods,company_URL,facility_URL,MDO_URL,source_id
0,QC-MAIN-5801b453,Abcourt-Barvue,None,None,CMP-0a6a3062,Abcourt Mines Inc,None,Quebec,POINT (-77.67901 48.52154),project_facility,...,None,None,"Zinc, silver",NaN,NaN,NaN,NaN,NaN,NaN,None
1,QC-MAIN-d29e0839,Sleeping Giant,None,None,CMP-0a6a3062,Abcourt Mines Inc,north of Amos,Quebec,POINT (-77.97434 49.13259),active_facility,...,Concentrator,Precious metals,"Gold, silver",Abcourt Mines Inc (100%),Abcourt Mines Inc,1956–1959; 1974–1975; 1988–open,https://abcourt.info/,https://abcourt.info/projects/the-sleeping-gia...,https://miningdataonline.com/property/1589/Sle...,None
2,QC-MAIN-f1ff4920,Akasaba West,None,None,CMP-6265c407,Agnico Eagle Mines Limited,None,Quebec,POINT (-77.58000 48.04000),project_facility,...,None,None,"Gold, copper",NaN,NaN,NaN,https://agnicoeagle.com/Home/default.aspx,https://www.agnicoeagle.com/English/operations...,https://miningdataonline.com/property/47/Meado...,None
3,NU-MAIN-4ea8ac9d,Amaruq,GRP-0a2c0d69,Meadowbank complex,CMP-6265c407,Agnico Eagle Mines Limited,Baker Lake,Nunavut,POINT (-96.69700 65.41500),active_facility,...,"Open-pit, underground",Precious metals,Gold,Agnico Eagle Mines Limited (100%),Agnico Eagle Mines Limited,2019–open,https://agnicoeagle.com/Home/default.aspx,https://www.agnicoeagle.com/English/operations...,https://miningdataonline.com/property/46/LaRon...,None
4,QC-MAIN-e7e6a960,Canadian Malartic,None,None,CMP-6265c407,Agnico Eagle Mines Limited,Malartic,Quebec,POINT (-78.13082 48.12222),active_facility,...,"Open-pit, concentrator",Precious metals,"Gold, silver",Agnico Eagle Mines Limited (100%),Agnico Eagle Mines Limited,1935–1965; 2011–open,https://agnicoeagle.com/Home/default.aspx,https://www.agnicoeagle.com/English/operations...,https://miningdataonline.com/property/13/Detou...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,None,None,CMP-3d2c4955,Wesdome Gold Mines Ltd,Wawa,Ontario,POINT (-85.45250 48.11028),active_facility,...,Open-pit,Precious metals,Gold,Wesdome Gold Mines Ltd (100%),NaN,2002–open,https://www.wesdome.com/English/overview/defau...,https://www.wesdome.com/English/operations/kie...,https://miningdataonline.com/property/3048/Kie...,None
266,BC-MAIN-feb13c30,Record Ridge,None,None,CMP-1023f9c0,West High Yield Resources Ltd,None,British Columbia,POINT (-117.88400 49.08200),project_facility,...,None,None,Magnesium,NaN,NaN,NaN,NaN,NaN,NaN,None
267,YT-MAIN-5e0d8b48,Casino,None,None,CMP-2dac9896,Western Copper and Gold Corporation,None,Yukon,POINT (-138.83333 62.73333),project_facility,...,None,None,"Copper, gold, molybdenum, silver",NaN,NaN,NaN,NaN,NaN,NaN,None
268,ON-MAIN-12c68d49,Eagle's Nest,None,None,CMP-65b36728,Wyloo,None,Ontario,POINT (-86.30380 52.74202),project_facility,...,None,None,"Nickel, copper, gold, platinum, palladium",NaN,NaN,NaN,NaN,NaN,NaN,None
269,BC-MAIN-891d3cb5,Akie,None,None,CMP-3416049b,ZincX Resources Corp,None,British Columbia,POINT (-124.86599 57.38088),project_facility,...,None,None,"Zinc, lead, silver",NaN,NaN,NaN,NaN,NaN,NaN,None

## Environment table

### CTrace dataset

In [106]:
ctrace_ghg_gdf

,ctrace_id,year,emissions_quantity,gas,source_id,substance_id,compartment_id,main_id
6,1754055,2023,5.610000e+03,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-6e9b2449
7,1754056,2023,6.403000e+03,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-63b394c3
8,1754057,2023,2.299160e+05,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-599152a0
9,1754058,2023,2.639000e+03,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-52224e1e
11,1754060,2023,4.225000e+03,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-48fe2205
12,1754061,2023,1.316380e+05,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-6b4800fe
16,1754066,2023,2.412130e+06,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-30c1828c
25,1754077,2023,6.711600e+04,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-e51eda66
29,1754081,2023,7.782000e+03,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,YT-MAIN-752fbcae
32,1754084,2023,7.956600e+04,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-ed23117f
33,1754085,2023,7.137900e+04,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-3f490561
34,1754086,2023,5.400000e+02,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-23155c25
35,1754087,2023,1.590800e+04,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-aa76f6f2
43,1754096,2023,8.219000e+03,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-a97821c0
44,1754097,2023,8.451100e+04,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-8eb8be0d
51,1754104,2023,3.367000e+03,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-b2148882
54,25486533,2023,1.620000e+04,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-f8313ebd
55,25486534,2023,5.914500e+04,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-a3c56a83
56,36395102,2023,5.760720e+05,co2e_100yr,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-b64bae7a

In [107]:
ctrace_ghg_gdf.rename(columns={
    'ctrace_id': 'env_id',
    'emissions_quantity': 'value',
    'gas': 'unit'}, inplace=True)

In [108]:
ctrace_ghg_gdf['unit'] = ctrace_ghg_gdf['unit'].replace({'co2e_100yr': 'tCO2eq'})

In [109]:
ctrace_ghg_gdf

,env_id,year,value,unit,source_id,substance_id,compartment_id,main_id
6,1754055,2023,5.610000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-6e9b2449
7,1754056,2023,6.403000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-63b394c3
8,1754057,2023,2.299160e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-599152a0
9,1754058,2023,2.639000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-52224e1e
11,1754060,2023,4.225000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-48fe2205
12,1754061,2023,1.316380e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-6b4800fe
16,1754066,2023,2.412130e+06,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-30c1828c
25,1754077,2023,6.711600e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-e51eda66
29,1754081,2023,7.782000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,YT-MAIN-752fbcae
32,1754084,2023,7.956600e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-ed23117f
33,1754085,2023,7.137900e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-3f490561
34,1754086,2023,5.400000e+02,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-23155c25
35,1754087,2023,1.590800e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-aa76f6f2
43,1754096,2023,8.219000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-a97821c0
44,1754097,2023,8.451100e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-8eb8be0d
51,1754104,2023,3.367000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-b2148882
54,25486533,2023,1.620000e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-f8313ebd
55,25486534,2023,5.914500e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-a3c56a83
56,36395102,2023,5.760720e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-b64bae7a

### NPRI dataset

In [110]:
pollutant_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
0,npri-1568-2023-1,ON-MAIN-1f126a43,2023,0.636,tonnes,CMP1718f4466d,SUB1c6e015419,https://www.canada.ca/en/environment-climate-c...
1,npri-1568-2023-2,ON-MAIN-1f126a43,2023,0.116,kg,CMP1718f4466d,SUB0cbc90a094,https://www.canada.ca/en/environment-climate-c...
2,npri-1568-2023-3,ON-MAIN-1f126a43,2023,76.208,tonnes,CMP1718f4466d,SUB642eab0862,https://www.canada.ca/en/environment-climate-c...
3,npri-1568-2023-4,ON-MAIN-1f126a43,2023,0.00105,tonnes,CMP1718f4466d,SUB7e3f017a30,https://www.canada.ca/en/environment-climate-c...
4,npri-1568-2023-5,ON-MAIN-1f126a43,2023,0.18,kg,CMP1718f4466d,SUBd94d47b1d8,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
24116,npri-28761-2023-117,NL-MAIN-d9036091,2023,4.405,tonnes,CMP281acc6045,SUB4cedd6b899,https://www.canada.ca/en/environment-climate-c...
24117,npri-28761-2023-118,NL-MAIN-d9036091,2023,0.2475,tonnes,CMP281acc6045,SUBda6a6d231d,https://www.canada.ca/en/environment-climate-c...
24118,npri-28761-2023-119,NL-MAIN-d9036091,2023,29.277299999999997,tonnes,CMP281acc6045,SUB28f44d0e11,https://www.canada.ca/en/environment-climate-c...
24119,npri-28761-2023-120,NL-MAIN-d9036091,2023,0.485,tonnes,CMP281acc6045,SUBba3b5d11c7,https://www.canada.ca/en/environment-climate-c...
24120,npri-28761-2023-121,NL-MAIN-d9036091,2023,39.214054000000004,tonnes,CMP281acc6045,SUBae95939c3f,https://www.canada.ca/en/environment-climate-c...

In [111]:
pollutant_gdf.rename(columns={
    'row_id': 'env_id'}, inplace=True)

### GHG dataset

In [112]:
ghg_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
1,GHG-10101-2022-1,NT-MAIN-6c1d6ee6,2022,164.88,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
4,GHG-10188-2022-1,QC-MAIN-084bd95c,2022,293.10,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
7,GHG-10240-2022-1,QC-MAIN-a97821c0,2022,129.26,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
8,GHG-10299-2022-1,QC-MAIN-e25eed27,2022,909.89,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
9,GHG-10350-2022-1,NL-MAIN-b64bae7a,2022,110.93,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
153,GHG-10791-2022-1,QC-MAIN-c1c7eb99,2022,96.48,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
154,GHG-10810-2022-1,NL-MAIN-d9036091,2022,50.09,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
169,GHG-11723-2022-1,ON-MAIN-2e13aaa0,2022,14.17,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
170,GHG-11730-2022-1,QC-MAIN-92628f16,2022,380.82,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...
178,GHG-12298-2022-1,ON-MAIN-63b394c3,2022,330.67,kilotonnes of carbon dioxide equivalents (kt C...,CMPf3265e9fca,NaN,https://www.canada.ca/en/environment-climate-c...

In [113]:
ghg_gdf.rename(columns={'row_id': 'env_id'}, inplace=True)

In [114]:
ghg_gdf['unit'] = ghg_gdf['unit'].replace({'kilotonnes of carbon dioxide equivalents (kt CO2 eq)': 'ktCO2eq'})

### Manually collected data

In [115]:
env_df

,row_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,subflow_type,substance_name,unit,value,comment,source,source_id,substance_id,compartment_pathway,compartment_id
0,ENV-1f126a43-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,-,NaN,mining,"Underground, concentrator",...,-,SOx,t,315,"""In absence of site-level monitoring emission ...",2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB2c1715b8f1,Unspecified,CMPf3265e9fca
1,ENV-1f126a43-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Canadian Malartic,ON-MAIN-1f126a43,-,NaN,mining,"Underground, concentrator",...,-,NOx,t,4802,"""In absence of site-level monitoring emission ...",2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB515573c582,Unspecified,CMPf3265e9fca
2,ENV-e7e6a960-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,-,NaN,mining,"Open-pit, concentrator",...,-,SOx,t,486,"""In absence of site-level monitoring emission ...",2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB2c1715b8f1,Unspecified,CMPf3265e9fca
3,ENV-e7e6a960-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,-,NaN,mining,"Open-pit, concentrator",...,-,NOx,t,7414,"""In absence of site-level monitoring emission ...",2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB515573c582,Unspecified,CMPf3265e9fca
4,ENV-8b0264c9-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Goldex,NU-MAIN-8b0264c9,-,NaN,mining,"Underground, concentrator",...,-,SOx,t,38,"""In absence of site-level monitoring emission ...",2023-Sustainability-Performance_data.xlsx,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB2c1715b8f1,Unspecified,CMPf3265e9fca
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,ENV-9de9bb0d-2023-19,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,Total water discharged,-,m3,324347,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
746,ENV-c5fefb01-2023-16,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,-,NaN,mining,"Open-pit, concentrator",...,Water withdrawal,-,m3,168115,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
747,ENV-c5fefb01-2023-17,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,-,NaN,mining,"Open-pit, concentrator",...,Water withdrawal|Freshwater withdrawn,-,m3,168115,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
748,ENV-c5fefb01-2023-18,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,-,NaN,mining,"Open-pit, concentrator",...,Total water consumption,-,m3,82144,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
749,ENV-c5fefb01-2023-19,2023,Site-specific,Wesdome Gold Mines Ltd,Kiena,ON-MAIN-c5fefb01,-,NaN,mining,"Open-pit, concentrator",...,Total water discharged,-,m3,536420,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352

In [116]:
env_df.rename(columns={'row_id': 'env_id'}, inplace=True)
env_df.drop(columns=['reporting_level', 'reported_company_nrcan', 'name', 'facility_type', 'mining_processing_type', 'commodity','compartment', 'flow_type','subflow_type', 'substance_name', 'source', 'compartment_pathway'], inplace=True)

In [117]:
env_df

,env_id,year,main_id,facility_group_id,company_id,unit,value,comment,source_id,substance_id,compartment_id
0,ENV-1f126a43-2023-1,2023,ON-MAIN-1f126a43,-,NaN,t,315,"""In absence of site-level monitoring emission ...",SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB2c1715b8f1,CMPf3265e9fca
1,ENV-1f126a43-2023-2,2023,ON-MAIN-1f126a43,-,NaN,t,4802,"""In absence of site-level monitoring emission ...",SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB515573c582,CMPf3265e9fca
2,ENV-e7e6a960-2023-1,2023,QC-MAIN-e7e6a960,-,NaN,t,486,"""In absence of site-level monitoring emission ...",SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB2c1715b8f1,CMPf3265e9fca
3,ENV-e7e6a960-2023-2,2023,QC-MAIN-e7e6a960,-,NaN,t,7414,"""In absence of site-level monitoring emission ...",SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB515573c582,CMPf3265e9fca
4,ENV-8b0264c9-2023-1,2023,NU-MAIN-8b0264c9,-,NaN,t,38,"""In absence of site-level monitoring emission ...",SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...,SUB2c1715b8f1,CMPf3265e9fca
...,...,...,...,...,...,...,...,...,...,...,...
745,ENV-9de9bb0d-2023-19,2023,QC-MAIN-9de9bb0d,-,NaN,m3,324347,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352
746,ENV-c5fefb01-2023-16,2023,ON-MAIN-c5fefb01,-,NaN,m3,168115,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352
747,ENV-c5fefb01-2023-17,2023,ON-MAIN-c5fefb01,-,NaN,m3,168115,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352
748,ENV-c5fefb01-2023-18,2023,ON-MAIN-c5fefb01,-,NaN,m3,82144,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352
749,ENV-c5fefb01-2023-19,2023,ON-MAIN-c5fefb01,-,NaN,m3,536420,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352

### Concatenate all environment data into a single table

In [118]:
env_table = pd.concat(
    [ctrace_ghg_gdf, pollutant_gdf, ghg_gdf, env_df],
    ignore_index=True
)

In [119]:
env_table

,env_id,year,value,unit,source_id,substance_id,compartment_id,main_id,facility_group_id,company_id,comment
0,1754055,2023,5610.000024,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-6e9b2449,NaN,NaN,NaN
1,1754056,2023,6403.000027,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-63b394c3,NaN,NaN,NaN
2,1754057,2023,229916.000984,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-599152a0,NaN,NaN,NaN
3,1754058,2023,2639.000011,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-52224e1e,NaN,NaN,NaN
4,1754060,2023,4225.000018,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-48fe2205,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
14520,ENV-9de9bb0d-2023-19,2023,324347,m3,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352,QC-MAIN-9de9bb0d,-,NaN,NaN
14521,ENV-c5fefb01-2023-16,2023,168115,m3,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352,ON-MAIN-c5fefb01,-,NaN,NaN
14522,ENV-c5fefb01-2023-17,2023,168115,m3,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352,ON-MAIN-c5fefb01,-,NaN,NaN
14523,ENV-c5fefb01-2023-18,2023,82144,m3,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352,ON-MAIN-c5fefb01,-,NaN,NaN
14524,ENV-c5fefb01-2023-19,2023,536420,m3,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,CMP68bd334352,ON-MAIN-c5fefb01,-,NaN,NaN

In [120]:
env_table.columns

Index(['env_id', 'year', 'value', 'unit', 'source_id', 'substance_id',
       'compartment_id', 'main_id', 'facility_group_id', 'company_id',
       'comment'],
      dtype='object')

In [121]:
column_order = ['env_id', 'year', 'compartment_id', 'substance_id', 'unit', 'value', 'comment', 'main_id','facility_group_id', 'company_id', 'source_id']

In [122]:
env_table = env_table[column_order]

In [123]:
env_table

,env_id,year,compartment_id,substance_id,unit,value,comment,main_id,facility_group_id,company_id,source_id
0,1754055,2023,CMPf3265e9fca,NaN,tCO2eq,5610.000024,NaN,ON-MAIN-6e9b2449,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
1,1754056,2023,CMPf3265e9fca,NaN,tCO2eq,6403.000027,NaN,ON-MAIN-63b394c3,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
2,1754057,2023,CMPf3265e9fca,NaN,tCO2eq,229916.000984,NaN,BC-MAIN-599152a0,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
3,1754058,2023,CMPf3265e9fca,NaN,tCO2eq,2639.000011,NaN,ON-MAIN-52224e1e,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
4,1754060,2023,CMPf3265e9fca,NaN,tCO2eq,4225.000018,NaN,ON-MAIN-48fe2205,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
...,...,...,...,...,...,...,...,...,...,...,...
14520,ENV-9de9bb0d-2023-19,2023,CMP68bd334352,NaN,m3,324347,NaN,QC-MAIN-9de9bb0d,-,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
14521,ENV-c5fefb01-2023-16,2023,CMP68bd334352,NaN,m3,168115,NaN,ON-MAIN-c5fefb01,-,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
14522,ENV-c5fefb01-2023-17,2023,CMP68bd334352,NaN,m3,168115,NaN,ON-MAIN-c5fefb01,-,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
14523,ENV-c5fefb01-2023-18,2023,CMP68bd334352,NaN,m3,82144,NaN,ON-MAIN-c5fefb01,-,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables
14524,ENV-c5fefb01-2023-19,2023,CMP68bd334352,NaN,m3,536420,NaN,ON-MAIN-c5fefb01,-,NaN,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables

## Production table

### Manually collected data

In [124]:
production_df

,row_id,year,level,geography,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,...,commodities_nrcan,commodity,reference_point,material_type,data_type,unit,value,comment,source,source_id
0,PROD-UNKNOWN-2023-1,2023,Company-level,World,Glencore,-,-,-,NaN,Refinery,...,"Copper (cathodes), gold, silver, tellurium, se...",Copper,Refined metal produced,Refinery production,Production,kt,443.30,Includes production by Horne and CCR but also ...,GLEN_2024-FY_ProductionReport_tables.xlsx,SRC_Glencore_GLEN_2024-FY_ProductionReport_tables
1,PROD-UNKNOWN-2023-2,2023,Company-level,World,Glencore,-,-,-,NaN,Refinery,...,"Copper (cathodes), gold, silver, tellurium, se...",Copper,Refined metal produced,Refinery production,Production,kt,507.30,Includes production by Horne and CCR but also ...,GLEN_2024-FY_ProductionReport_tables.xlsx,SRC_Glencore_GLEN_2024-FY_ProductionReport_tables
2,PROD-CMP-140e111b-2023-1,2023,Company-level,World,Alcoa Corporation,-,-,NaN,CMP-140e111b,manufacturing,...,Aluminum,Aluminum,Intermediate metal produced,Aluminum production,Production,kmt,2114.00,NaN,4Q23-Alcoa-Financial-Results,SRC_AlcoaCorporation_4Q23-Alcoa-Financial-Results
3,PROD-CMP-c08ac7d7-2023-1,2023,Company-level,World,Champion Iron Ltd,-,-,-,CMP-c08ac7d7,mining,...,Iron,Iron,Usable ore,Concentrate,Production,Mt,14.16,NaN,cil-23sr-esg-databookvf.xlsx,SRC_ChampionIronLtd_cil-23sr-esg-databookvf
4,PROD-CMP-c08ac7d7-2023-2,2023,Company-level,World,Champion Iron Ltd,-,-,-,CMP-c08ac7d7,mining,...,Iron,Iron,Total extraction,Ore mined,Production,Mt,40.87,Ore mined and hauled,cil-23sr-esg-databookvf.xlsx,SRC_ChampionIronLtd_cil-23sr-esg-databookvf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PROD-687b8c8d-2023-2,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,-,NaN,mining,...,Gold,Gold,Total extraction,Ore mined,Production,t,2878155.00,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
340,PROD-687b8c8d-2023-3,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,-,NaN,mining,...,Gold,Gold,Crude ore,Ore processed,Production,t,2878047.00,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
341,PROD-687b8c8d-2023-4,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,-,NaN,mining,...,Gold,Gold,Crude ore,Mill grade,Technical attribute,?,2.20,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
342,PROD-687b8c8d-2023-5,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,-,NaN,mining,...,Gold,Gold,Crude ore,Mill recovery rate,Technical attribute,%,90.00,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023
343,PROD-687b8c8d-2023-6,2023,Site-specific,Canada,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,-,NaN,mining,...,Gold,Gold,Crude ore,Ore grade,Technical attribute,?,2.20,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023

In [125]:
production_df.rename(columns={'row_id': 'prod_id'}, inplace=True)
production_df.drop(columns=['level', 'reported_company_nrcan', 'name', 
                            'facility_type', 'mining_processing_type', 'commodities_nrcan', 'source'], inplace=True)

In [126]:
production_df

,prod_id,year,geography,main_id,facility_group_id,company_id,commodity,reference_point,material_type,data_type,unit,value,comment,source_id
0,PROD-UNKNOWN-2023-1,2023,World,-,-,NaN,Copper,Refined metal produced,Refinery production,Production,kt,443.30,Includes production by Horne and CCR but also ...,SRC_Glencore_GLEN_2024-FY_ProductionReport_tables
1,PROD-UNKNOWN-2023-2,2023,World,-,-,NaN,Copper,Refined metal produced,Refinery production,Production,kt,507.30,Includes production by Horne and CCR but also ...,SRC_Glencore_GLEN_2024-FY_ProductionReport_tables
2,PROD-CMP-140e111b-2023-1,2023,World,-,NaN,CMP-140e111b,Aluminum,Intermediate metal produced,Aluminum production,Production,kmt,2114.00,NaN,SRC_AlcoaCorporation_4Q23-Alcoa-Financial-Results
3,PROD-CMP-c08ac7d7-2023-1,2023,World,-,-,CMP-c08ac7d7,Iron,Usable ore,Concentrate,Production,Mt,14.16,NaN,SRC_ChampionIronLtd_cil-23sr-esg-databookvf
4,PROD-CMP-c08ac7d7-2023-2,2023,World,-,-,CMP-c08ac7d7,Iron,Total extraction,Ore mined,Production,Mt,40.87,Ore mined and hauled,SRC_ChampionIronLtd_cil-23sr-esg-databookvf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PROD-687b8c8d-2023-2,2023,Canada,ON-MAIN-687b8c8d,-,NaN,Gold,Total extraction,Ore mined,Production,t,2878155.00,NaN,SRC_AlamosGoldInc_Data_2023
340,PROD-687b8c8d-2023-3,2023,Canada,ON-MAIN-687b8c8d,-,NaN,Gold,Crude ore,Ore processed,Production,t,2878047.00,NaN,SRC_AlamosGoldInc_Data_2023
341,PROD-687b8c8d-2023-4,2023,Canada,ON-MAIN-687b8c8d,-,NaN,Gold,Crude ore,Mill grade,Technical attribute,?,2.20,NaN,SRC_AlamosGoldInc_Data_2023
342,PROD-687b8c8d-2023-5,2023,Canada,ON-MAIN-687b8c8d,-,NaN,Gold,Crude ore,Mill recovery rate,Technical attribute,%,90.00,NaN,SRC_AlamosGoldInc_Data_2023
343,PROD-687b8c8d-2023-6,2023,Canada,ON-MAIN-687b8c8d,-,NaN,Gold,Crude ore,Ore grade,Technical attribute,?,2.20,NaN,SRC_AlamosGoldInc_Data_2023

In [127]:
from constants import unit_conversion

In [128]:
# Apply a function to convert the 'value' column to tonnes
# But we need to do that only for the 'Production' data_type and don't do it for any other data_type
production_df['value_tonnes'] = production_df.apply(
    lambda row: row['value'] * unit_conversion.get(row['unit'], 1) if row['data_type'] == 'Production' else np.nan, 
    axis=1
)

### CTrace dataset

In [129]:
ctrace_prod_gdf

,ctrace_id,year,activity,activity_units,capacity,capacity_units,source_id,substance_id,compartment_id,main_id
6,1754055,2023,8.630000e+05,t of copper ore,4.624000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-6e9b2449
7,1754056,2023,9.850000e+05,t of copper ore,3.554700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-63b394c3
8,1754057,2023,1.457500e+07,t of copper ore,3.670000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-599152a0
9,1754058,2023,4.060000e+05,t of copper ore,1.104100e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-52224e1e
11,1754060,2023,6.500000e+05,t of copper ore,4.822000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-48fe2205
12,1754061,2023,8.810000e+07,t of copper ore,6.450000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-6b4800fe
16,1754066,2023,7.288600e+07,t of copper ore,2.631000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-30c1828c
25,1754077,2023,1.501481e+06,t of copper ore,1.988200e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-e51eda66
29,1754081,2023,5.279710e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,t of copper ore,7.413000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,t of copper ore,2.313000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,YT-MAIN-752fbcae
32,1754084,2023,2.127800e+07,t of copper ore,2.500250e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-ed23117f
33,1754085,2023,5.948239e+06,t of copper ore,4.902900e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-3f490561
34,1754086,2023,4.500000e+04,t of copper ore,4.110000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-23155c25
35,1754087,2023,2.993000e+06,t of copper ore,3.408700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-aa76f6f2
43,1754096,2023,6.848790e+05,t of copper ore,1.500000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-a97821c0
44,1754097,2023,6.887709e+06,t of copper ore,4.549000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,BC-MAIN-8eb8be0d
51,1754104,2023,5.180000e+05,t of copper ore,2.453000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,QC-MAIN-b2148882
54,25486533,2023,1.350000e+06,t of copper ore,2.500000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-f8313ebd
55,25486534,2023,3.798000e+06,t of copper ore,2.200000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,ON-MAIN-a3c56a83
56,36395102,2023,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NaN,CMPf3265e9fca,NL-MAIN-b64bae7a

In [130]:
# Save units before melting
activity_units = ctrace_prod_gdf['activity_units']
capacity_units = ctrace_prod_gdf['capacity_units']

# Melt
ctrace_prod_gdf = pd.melt(
    ctrace_prod_gdf,
    id_vars=['ctrace_id', 'year', 'source_id', 'main_id'],
    value_vars=['activity', 'capacity'],
    var_name='data_type',
    value_name='value'
)

# Set data_type labels
ctrace_prod_gdf['data_type'] = ctrace_prod_gdf['data_type'].replace({
    'activity': 'Production',
    'capacity': 'Capacity'
})

# Concatenate units in correct order (activity first, then capacity)
ctrace_prod_gdf['unit'] = list(activity_units) + list(capacity_units)

In [131]:
ctrace_prod_gdf

,ctrace_id,year,source_id,main_id,data_type,value,unit
0,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Production,8.630000e+05,t of copper ore
1,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-63b394c3,Production,9.850000e+05,t of copper ore
2,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Production,1.457500e+07,t of copper ore
3,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Production,4.060000e+05,t of copper ore
4,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Production,6.500000e+05,t of copper ore
5,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Production,8.810000e+07,t of copper ore
6,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Production,7.288600e+07,t of copper ore
7,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Production,0.000000e+00,t of copper ore
8,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Production,1.501481e+06,t of copper ore
9,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Production,5.279710e+05,t of copper ore
10,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Production,0.000000e+00,t of copper ore
11,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Production,0.000000e+00,t of copper ore
12,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Production,2.127800e+07,t of copper ore
13,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Production,5.948239e+06,t of copper ore
14,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Production,4.500000e+04,t of copper ore
15,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Production,2.993000e+06,t of copper ore
16,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Production,6.848790e+05,t of copper ore
17,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Production,6.887709e+06,t of copper ore
18,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Production,5.180000e+05,t of copper ore
19,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Production,0.000000e+00,t of copper ore
20,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Production,1.350000e+06,t of copper ore
21,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Production,3.798000e+06,t of copper ore
22,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Production,1.578280e+07,t of iron ore
23,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Capacity,4.624000e+06,tonnes
24,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-63b394c3,Capacity,3.554700e+07,tonnes
25,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Capacity,3.670000e+08,tonnes
26,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Capacity,1.104100e+07,tonnes
27,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Capacity,4.822000e+06,tonnes
28,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Capacity,6.450000e+08,tonnes
29,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Capacity,2.631000e+08,tonnes
30,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Capacity,8.787959e+07,tonnes
31,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Capacity,1.988200e+07,tonnes
32,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Capacity,8.787959e+07,tonnes
33,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Capacity,7.413000e+06,tonnes
34,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Capacity,2.313000e+06,tonnes
35,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Capacity,2.500250e+08,tonnes
36,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Capacity,4.902900e+07,tonnes
37,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Capacity,4.110000e+06,tonnes
38,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Capacity,3.408700e+07,tonnes
39,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Capacity,1.500000e+07,tonnes
40,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Capacity,4.549000e+08,tonnes
41,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Capacity,2.453000e+06,tonnes
42,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Capacity,8.787959e+07,tonnes
43,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Capacity,2.500000e+06,tonnes
44,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Capacity,2.200000e+07,tonnes
45,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Capacity,4.789430e+08,tonnes

In [132]:
ctrace_prod_gdf.rename(columns={'ctrace_id': 'prod_id'}, inplace=True)

In [133]:
# We add the missing columns
ctrace_prod_gdf['geography'] = 'Canada'
ctrace_prod_gdf['reference_point'] = 'Crude ore'
ctrace_prod_gdf['value_tonnes'] = ctrace_prod_gdf['value'] # they are always in tonnes

In [134]:
# Add a commodity column with would be = Copper if unit column = 't of copper ore' and = 'Iron' if unit column = 't of iron ore'
ctrace_prod_gdf['commodity'] = ctrace_prod_gdf['unit'].apply(
    lambda x: 'Copper' if 'copper' in x.lower() else ('Iron' if 'iron' in x.lower() else None)
)

In [135]:
ctrace_prod_gdf

,prod_id,year,source_id,main_id,data_type,value,unit,geography,reference_point,value_tonnes,commodity
0,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Production,8.630000e+05,t of copper ore,Canada,Crude ore,8.630000e+05,Copper
1,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-63b394c3,Production,9.850000e+05,t of copper ore,Canada,Crude ore,9.850000e+05,Copper
2,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Production,1.457500e+07,t of copper ore,Canada,Crude ore,1.457500e+07,Copper
3,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Production,4.060000e+05,t of copper ore,Canada,Crude ore,4.060000e+05,Copper
4,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Production,6.500000e+05,t of copper ore,Canada,Crude ore,6.500000e+05,Copper
5,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Production,8.810000e+07,t of copper ore,Canada,Crude ore,8.810000e+07,Copper
6,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Production,7.288600e+07,t of copper ore,Canada,Crude ore,7.288600e+07,Copper
7,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
8,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Production,1.501481e+06,t of copper ore,Canada,Crude ore,1.501481e+06,Copper
9,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Production,5.279710e+05,t of copper ore,Canada,Crude ore,5.279710e+05,Copper
10,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
11,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
12,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Production,2.127800e+07,t of copper ore,Canada,Crude ore,2.127800e+07,Copper
13,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Production,5.948239e+06,t of copper ore,Canada,Crude ore,5.948239e+06,Copper
14,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Production,4.500000e+04,t of copper ore,Canada,Crude ore,4.500000e+04,Copper
15,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Production,2.993000e+06,t of copper ore,Canada,Crude ore,2.993000e+06,Copper
16,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Production,6.848790e+05,t of copper ore,Canada,Crude ore,6.848790e+05,Copper
17,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Production,6.887709e+06,t of copper ore,Canada,Crude ore,6.887709e+06,Copper
18,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Production,5.180000e+05,t of copper ore,Canada,Crude ore,5.180000e+05,Copper
19,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
20,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Production,1.350000e+06,t of copper ore,Canada,Crude ore,1.350000e+06,Copper
21,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Production,3.798000e+06,t of copper ore,Canada,Crude ore,3.798000e+06,Copper
22,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Production,1.578280e+07,t of iron ore,Canada,Crude ore,1.578280e+07,Iron
23,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Capacity,4.624000e+06,tonnes,Canada,Crude ore,4.624000e+06,None
24,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-63b394c3,Capacity,3.554700e+07,tonnes,Canada,Crude ore,3.554700e+07,None
25,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Capacity,3.670000e+08,tonnes,Canada,Crude ore,3.670000e+08,None
26,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Capacity,1.104100e+07,tonnes,Canada,Crude ore,1.104100e+07,None
27,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Capacity,4.822000e+06,tonnes,Canada,Crude ore,4.822000e+06,None
28,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Capacity,6.450000e+08,tonnes,Canada,Crude ore,6.450000e+08,None
29,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Capacity,2.631000e+08,tonnes,Canada,Crude ore,2.631000e+08,None
30,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
31,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Capacity,1.988200e+07,tonnes,Canada,Crude ore,1.988200e+07,None
32,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
33,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Capacity,7.413000e+06,tonnes,Canada,Crude ore,7.413000e+06,None
34,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Capacity,2.313000e+06,tonnes,Canada,Crude ore,2.313000e+06,None
35,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Capacity,2.500250e+08,tonnes,Canada,Crude ore,2.500250e+08,None
36,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Capacity,4.902900e+07,tonnes,Canada,Crude ore,4.902900e+07,None
37,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Capacity,4.110000e+06,tonnes,Canada,Crude ore,4.110000e+06,None
38,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Capacity,3.408700e+07,tonnes,Canada,Crude ore,3.408700e+07,None
39,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Capacity,1.500000e+07,tonnes,Canada,Crude ore,1.500000e+07,None
40,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Capacity,4.549000e+08,tonnes,Canada,Crude ore,4.549000e+08,None
41,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Capacity,2.453000e+06,tonnes,Canada,Crude ore,2.453000e+06,None
42,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
43,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Capacity,2.500000e+06,tonnes,Canada,Crude ore,2.500000e+06,None
44,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Capacity,2.200000e+07,tonnes,Canada,Crude ore,2.200000e+07,None
45,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Capacity,4.789430e+08,tonnes,Canada,Crude ore,4.789430e+08,None

### Concatenate all production data into a single table

In [136]:
# Concatenate production and ctrace data 
production_table = pd.concat([production_df, ctrace_prod_gdf], ignore_index=True)

In [137]:
production_table.columns

Index(['prod_id', 'year', 'geography', 'main_id', 'facility_group_id',
       'company_id', 'commodity', 'reference_point', 'material_type',
       'data_type', 'unit', 'value', 'comment', 'source_id', 'value_tonnes'],
      dtype='object')

In [138]:
column_order = ['prod_id', 'year', 'geography', 
                'commodity', 'reference_point', 'material_type', 'data_type', 
                'unit', 'value', 'value_tonnes', 'comment', 
                'main_id', 'facility_group_id','company_id', 'source_id']

In [139]:
production_table = production_table[column_order]

In [140]:
production_table

,prod_id,year,geography,commodity,reference_point,material_type,data_type,unit,value,value_tonnes,comment,main_id,facility_group_id,company_id,source_id
0,PROD-UNKNOWN-2023-1,2023,World,Copper,Refined metal produced,Refinery production,Production,kt,4.433000e+02,4.433000e+05,Includes production by Horne and CCR but also ...,-,-,NaN,SRC_Glencore_GLEN_2024-FY_ProductionReport_tables
1,PROD-UNKNOWN-2023-2,2023,World,Copper,Refined metal produced,Refinery production,Production,kt,5.073000e+02,5.073000e+05,Includes production by Horne and CCR but also ...,-,-,NaN,SRC_Glencore_GLEN_2024-FY_ProductionReport_tables
2,PROD-CMP-140e111b-2023-1,2023,World,Aluminum,Intermediate metal produced,Aluminum production,Production,kmt,2.114000e+03,2.114000e+12,NaN,-,NaN,CMP-140e111b,SRC_AlcoaCorporation_4Q23-Alcoa-Financial-Results
3,PROD-CMP-c08ac7d7-2023-1,2023,World,Iron,Usable ore,Concentrate,Production,Mt,1.416000e+01,1.416000e+01,NaN,-,-,CMP-c08ac7d7,SRC_ChampionIronLtd_cil-23sr-esg-databookvf
4,PROD-CMP-c08ac7d7-2023-2,2023,World,Iron,Total extraction,Ore mined,Production,Mt,4.087000e+01,4.087000e+01,Ore mined and hauled,-,-,CMP-c08ac7d7,SRC_ChampionIronLtd_cil-23sr-esg-databookvf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,1754104,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,2.453000e+06,2.453000e+06,NaN,ON-MAIN-28f3f0fc,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
386,1754105,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,8.787959e+07,8.787959e+07,NaN,QC-MAIN-b2148882,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
387,25486533,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,2.500000e+06,2.500000e+06,NaN,ON-MAIN-f8313ebd,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
388,25486534,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,2.200000e+07,2.200000e+07,NaN,ON-MAIN-a3c56a83,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
389,36395102,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,4.789430e+08,4.789430e+08,NaN,NL-MAIN-b64bae7a,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."

In [141]:
production_table['main_id'].value_counts()

main_id
-                   64
MB-MAIN-da0b5c3d    21
BC-MAIN-599152a0    16
MB-MAIN-0898e255    15
BC-MAIN-ed23117f    12
                    ..
QC-MAIN-a555d9b9     1
NU-MAIN-5154702a     1
ON-MAIN-aeafbb59     1
ON-MAIN-aeafbb60     1
QC-MAIN-e7e6a964     1
Name: count, Length: 89, dtype: int64

## Protected & Indigenous table

In [142]:
protected_mapping = {
    "WDPA_PID": "protected_area_id",
    "NAME": "land_name",
    "DESIG": "land_type",
    "STATUS_YR": "date"
}

indigenous_mapping = {
    "indigenous_land_id": "protected_area_id",
    "Name": "land_name",
    "Category": "land_type",
    "Data_Date": "date"
}

In [143]:
protected_clean = wpda_gdf_polygons.rename(columns=protected_mapping)[["protected_area_id", "land_name", "land_type", "distance_km", "geometry", "main_id", "source_id"]].copy()

In [144]:
indigenous_clean = indigenous_can_gdf.rename(columns=indigenous_mapping)[["protected_area_id", "land_name", "land_type", "distance_km", "geometry", "main_id", "source_id"]].copy()

In [145]:
target_crs = "EPSG:4326"
protected_clean = protected_clean.to_crs(target_crs)
indigenous_clean = indigenous_clean.to_crs(target_crs)

In [146]:
protected_land_table = pd.concat([protected_clean, indigenous_clean], ignore_index=True)
protected_land_table = gpd.GeoDataFrame(protected_land_table, geometry="geometry", crs=wpda_gdf_polygons.crs)

In [243]:
protected_land_table

,protected_area_id,land_name,land_type,distance_km,main_id,source_id
0,611_B,Wood Buffalo National Park Of Canada,National Park,27.397,NT-MAIN-b99d4cb2,https://www.protectedplanet.net
1,615,Banff National Park Of Canada,National Park,2.153,AB-MAIN-8434dce0,https://www.protectedplanet.net
2,616,Nahanni National Park Reserve Of Canada,National Park,0.000,NT-MAIN-b3681e03,https://www.protectedplanet.net
3,616,Nahanni National Park Reserve Of Canada,National Park,31.820,YT-MAIN-03a159d7,https://www.protectedplanet.net
4,620,Pukaskwa National Park Of Canada,National Park,19.001,ON-MAIN-6e9be24e,https://www.protectedplanet.net
...,...,...,...,...,...,...
8790,ZZ-IND-40a2ea30,Six Nations Indian Reserve No. 40,Indian Reserve,25.954,ON-MAIN-020a683c,http://www.landmarkmap.org
8791,ZZ-IND-40a2ea30,Six Nations Indian Reserve No. 40,Indian Reserve,20.924,ON-MAIN-b2e5c9bb,http://www.landmarkmap.org
8792,ZZ-IND-4e299f50,Mashteuiatsh,Indian Reserve,39.343,QC-MAIN-3aa117d8,http://www.landmarkmap.org
8793,ZZ-IND-74ac0e34,Nisga'a,First Nations Treaty Lands,16.458,BC-MAIN-3ef4f421,http://www.landmarkmap.org
8794,ZZ-IND-74ac0e34,Nisga'a,First Nations Treaty Lands,43.499,BC-MAIN-51068f3b,http://www.landmarkmap.org

In [361]:
protected_land_table['protected_area_id'].value_counts()

protected_area_id
555705169          27
555651780          20
ZZ-IND-2c6adbc5    16
19932              16
555515830          15
                   ..
555569718           1
555569719           1
555569722           1
555569726           1
555621605_B         1
Name: count, Length: 3938, dtype: int64

## Land cover table

In [148]:
land_cover_table = land_cover_gdf.copy()
land_cover_table['npv_biome_type'] = npv_gdf['biome_type']
land_cover_table['source_id'] = land_cover_table['source_id'].astype(str) + ';' + npv_gdf['source_id'].astype(str)

In [149]:
from db_creation_function import assign_row_id

In [150]:
land_cover_table = assign_row_id(land_cover_table,
                                 facility_id_col='main_id', 
                                 prefix='land_cover_id')

In [151]:
land_cover_table.drop(columns=['name', 'geometry'], inplace=True)
land_cover_table.rename(columns={'row_id': 'land_cover_id'}, inplace=True)
land_cover_table = land_cover_table[['land_cover_id', 'year', 'modis_land_cover',
       'esa_land_cover', 'npv_biome_type', 'main_id', 'source_id']]

In [152]:
land_cover_table

,land_cover_id,year,modis_land_cover,esa_land_cover,npv_biome_type,main_id,source_id
0,land_cover_id-5801b453-1,2021,Woody Savannas,Built-up,None,QC-MAIN-5801b453,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
1,land_cover_id-d29e0839-1,2021,Woody Savannas,Bare/Sparse Vegetation,Cool Mixed Forest,QC-MAIN-d29e0839,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
2,land_cover_id-f1ff4920-1,2021,Woody Savannas,Tree Cover,Cool Mixed Forest,QC-MAIN-f1ff4920,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
3,land_cover_id-4ea8ac9d-1,2021,Grasslands,Moss & Lichen,None,NU-MAIN-4ea8ac9d,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
4,land_cover_id-e7e6a960-1,2021,Grasslands,Bare/Sparse Vegetation,Cool Mixed Forest,QC-MAIN-e7e6a960,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
...,...,...,...,...,...,...,...
265,land_cover_id-c5fefb01-1,2021,Woody Savannas,Permanent Water Bodies,Cool Mixed Forest,ON-MAIN-c5fefb01,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
266,land_cover_id-feb13c30-1,2021,Woody Savannas,Tree Cover,Cool Evergreen Needleleaf Forest,BC-MAIN-feb13c30,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
267,land_cover_id-5e0d8b48-1,2021,Open Shrublands,Grassland,Cold Evergreen Needleleaf Forest,YT-MAIN-5e0d8b48,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
268,land_cover_id-12c68d49-1,2021,Woody Savannas,Grassland,Cool Mixed Forest,ON-MAIN-12c68d49,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...
269,land_cover_id-891d3cb5-1,2021,Evergreen Needleleaf Forest,Tree Cover,Cold Evergreen Needleleaf Forest,BC-MAIN-891d3cb5,https://doi.org/10.5067/MODIS/MCD12Q1.061 + ht...

## Environmental intensity table

In [173]:
env_int_df

,env_int_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,flow_type,substance_name,unit,value,comment,source,source_id,substance_id,compartment_pathway,compartment_id
0,ENV_INT-GRP-0a2c0d69-2023-1,2023,Facility-group,Agnico Eagle Mines Limited,Meadowbank,-,GRP-0a2c0d69,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/t of ore processed,0.252115,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
1,ENV_INT-GRP-0a2c0d69-2023-2,2023,Facility-group,Agnico Eagle Mines Limited,Meadowbank,-,GRP-0a2c0d69,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/oz of gold,2.244304,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
2,ENV_INT-4ea8ac9d-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,LaRonde,NU-MAIN-4ea8ac9d,-,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/t of ore processed,0.559341,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
3,ENV_INT-4ea8ac9d-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,LaRonde,NU-MAIN-4ea8ac9d,-,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/oz of gold,4.849037,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
4,ENV_INT-730aefe3-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Macassa,NU-MAIN-730aefe3,-,NaN,mining,Concentrator,...,Freshwater withdrawn for use intensity,-,m3 of water/t of ore processed,0.437068,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,ENV_INT-9de9bb0d-2023-2,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,scope1+2,-,tCO2eq/oz produced,0.170000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMPf3265e9fca
92,ENV_INT-9de9bb0d-2023-3,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,Water intensity,-,m3/t milled,0.130000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
93,ENV_INT-9de9bb0d-2023-4,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,Water intensity,-,m3/oz produced,0.330000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
94,ENV_INT-9de9bb0d-2023-5,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,scope1+2,-,tCO2eq/t milled,0.070000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMPf3265e9fca
95,ENV_INT-9de9bb0d-2023-6,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,scope1+2,-,tCO2eq/oz produced,0.170000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMPf3265e9fca

In [174]:
#env_int_table = env_int_df.rename(columns={'row_id': 'env_int_id'}, inplace=True)
env_int_table = env_int_df

In [175]:
env_int_table

,env_int_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,flow_type,substance_name,unit,value,comment,source,source_id,substance_id,compartment_pathway,compartment_id
0,ENV_INT-GRP-0a2c0d69-2023-1,2023,Facility-group,Agnico Eagle Mines Limited,Meadowbank,-,GRP-0a2c0d69,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/t of ore processed,0.252115,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
1,ENV_INT-GRP-0a2c0d69-2023-2,2023,Facility-group,Agnico Eagle Mines Limited,Meadowbank,-,GRP-0a2c0d69,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/oz of gold,2.244304,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
2,ENV_INT-4ea8ac9d-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,LaRonde,NU-MAIN-4ea8ac9d,-,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/t of ore processed,0.559341,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
3,ENV_INT-4ea8ac9d-2023-2,2023,Site-specific,Agnico Eagle Mines Limited,LaRonde,NU-MAIN-4ea8ac9d,-,NaN,mining,"Open-pit, underground, concentrator",...,Freshwater withdrawn for use intensity,-,m3 of water/oz of gold,4.849037,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
4,ENV_INT-730aefe3-2023-1,2023,Site-specific,Agnico Eagle Mines Limited,Macassa,NU-MAIN-730aefe3,-,NaN,mining,Concentrator,...,Freshwater withdrawn for use intensity,-,m3 of water/t of ore processed,0.437068,NaN,Agnico-Eagle-2023-Sustainability-Performance-D...,SRC_AgnicoEagleMinesLimited_Agnico-Eagle-2023-...,NaN,Unspecified,CMP68bd334352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,ENV_INT-9de9bb0d-2023-2,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,scope1+2,-,tCO2eq/oz produced,0.170000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMPf3265e9fca
92,ENV_INT-9de9bb0d-2023-3,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,Water intensity,-,m3/t milled,0.130000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
93,ENV_INT-9de9bb0d-2023-4,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,Water intensity,-,m3/oz produced,0.330000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMP68bd334352
94,ENV_INT-9de9bb0d-2023-5,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,scope1+2,-,tCO2eq/t milled,0.070000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMPf3265e9fca
95,ENV_INT-9de9bb0d-2023-6,2023,Site-specific,Wesdome Gold Mines Ltd,Eagle River,QC-MAIN-9de9bb0d,-,NaN,mining,"Underground, concentrator",...,scope1+2,-,tCO2eq/oz produced,0.170000,NaN,2023-ESG-Data-Tables.xlsx,SRC_WesdomeGoldMinesLtd_2023-ESG-Data-Tables,NaN,Unspecified,CMPf3265e9fca

In [176]:
col_to_keep = [
    'env_int_id', 'year', 'compartment_id', 'flow_type', 'substance_id', 'unit', 'value', 'comment',
    'main_id', 'facility_group_id', 'company_id', 'source_id'
]

In [177]:
env_int_table = env_int_table[col_to_keep]

## Reserves and resources table

In [335]:
reserves_table = reserves_df.rename(columns={'row_id': 'reserves_id'})

In [336]:
reserves_table

,reserves_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,facility_type,mining_processing_type,commodity,...,ore_unit,grade,grade_unit,metal_content,metal_content_unit,norm,recovery_rate,comment,source,source_id
0,RES-d29e0839-2022-1,2022,Site-specific,Abcourt Mines Inc,Sleeping Giant,QC-MAIN-d29e0839,-,mining,Concentrator,Gold,...,Mt,7.14,g/t,173300.0,oz,NaN,NaN,NaN,TR_Abcourt_Geant_Dormant_2023,SRC_AbcourtMinesInc_TR_Abcourt_Geant_Dormant_2023
1,RES-d29e0839-2022-2,2022,Site-specific,Abcourt Mines Inc,Sleeping Giant,QC-MAIN-d29e0839,-,mining,Concentrator,Gold,...,Mt,8.74,g/t,248300.0,oz,NaN,NaN,NaN,TR_Abcourt_Geant_Dormant_2023,SRC_AbcourtMinesInc_TR_Abcourt_Geant_Dormant_2023
2,RES-e7e6a960-2024-1,2024,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,-,mining,"Open-pit, concentrator",Gold,...,kt,0.81,g/t,3333.0,kOz Au,NaN,92.0,NaN,2024_MRMR,SRC_AgnicoEagleMinesLimited_2024_MRMR
3,RES-e7e6a960-2024-2,2024,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,-,mining,"Open-pit, concentrator",Gold,...,kt,0.73,g/t,15718.0,kOz Au,NaN,92.0,NaN,2024_MRMR,SRC_AgnicoEagleMinesLimited_2024_MRMR
4,RES-e7e6a960-2024-3,2024,Site-specific,Agnico Eagle Mines Limited,Detour Lake,QC-MAIN-e7e6a960,-,mining,"Open-pit, concentrator",Gold,...,kt,1.1,g/t,1201.0,kOz Au,NaN,NaN,NaN,2024_MRMR,SRC_AgnicoEagleMinesLimited_2024_MRMR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,RES-dd723db4-2023-12,2023,Site-specific,Iron Ore Company of Canada Inc.,Carol Lake,NL-MAIN-dd723db4,-,mining,"Open-pit, concentrator",Phosphorus,...,NaN,0.03,% P,NaN,NaN,NaN,NaN,Reported by Rio Tinto,rt-fact-book-addendum.xlsx,SRC_IronOreCompanyofCanadaInc._rt-fact-book-ad...
390,RES-dd723db4-2023-13,2023,Site-specific,Iron Ore Company of Canada Inc.,Carol Lake,NL-MAIN-dd723db4,-,mining,"Open-pit, concentrator",Iron,...,NaN,38.2,% Fe,NaN,NaN,NaN,NaN,Reported by Rio Tinto,rt-fact-book-addendum.xlsx,SRC_IronOreCompanyofCanadaInc._rt-fact-book-ad...
391,RES-dd723db4-2023-14,2023,Site-specific,Iron Ore Company of Canada Inc.,Carol Lake,NL-MAIN-dd723db4,-,mining,"Open-pit, concentrator",Silicon dioxide,...,NaN,37.8,%SiO2,NaN,NaN,NaN,NaN,Reported by Rio Tinto,rt-fact-book-addendum.xlsx,SRC_IronOreCompanyofCanadaInc._rt-fact-book-ad...
392,RES-dd723db4-2023-15,2023,Site-specific,Iron Ore Company of Canada Inc.,Carol Lake,NL-MAIN-dd723db4,-,mining,"Open-pit, concentrator",Aluminum oxide,...,NaN,0.2,% Al2O3,NaN,NaN,NaN,NaN,Reported by Rio Tinto,rt-fact-book-addendum.xlsx,SRC_IronOreCompanyofCanadaInc._rt-fact-book-ad...
393,RES-dd723db4-2023-16,2023,Site-specific,Iron Ore Company of Canada Inc.,Carol Lake,NL-MAIN-dd723db4,-,mining,"Open-pit, concentrator",Phosphorus,...,NaN,0.03,% P,NaN,NaN,NaN,NaN,NaN,NaN,SRC_IronOreCompanyofCanadaInc._nan

In [337]:
reserves_table = reserves_table[['reserves_id', 'year', 'commodity', 'reserves_resources', 'reserves_resources_type', 'ore', 'ore_unit', 'grade', 'grade_unit', 'metal_content', 'metal_content_unit', 'recovery_rate', 'comment', 'main_id', 'facility_group_id', 'source_id']]

## Energy table

In [187]:
#energy_table = energy_df.rename(columns={'row_id': 'nrj_id'})
energy_table = energy_table[['nrj_id', 'year', 'energy_type', 'unit', 'value', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

In [188]:
energy_table

,nrj_id,year,energy_type,unit,value,main_id,facility_group_id,company_id,source_id
0,NRJ-e7e6a960-2023-1,2023,Fuel consumption,GJ,4266454,QC-MAIN-e7e6a960,-,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
1,NRJ-e7e6a960-2023-2,2023,Diesel,GJ,3947008,QC-MAIN-e7e6a960,-,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
2,NRJ-e7e6a960-2023-3,2023,Light Fuel & Gasoline,GJ,71904,QC-MAIN-e7e6a960,-,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
3,NRJ-e7e6a960-2023-4,2023,Propane,GJ,182468,QC-MAIN-e7e6a960,-,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
4,NRJ-e7e6a960-2023-5,2023,Explosives,GJ,65074,QC-MAIN-e7e6a960,-,NaN,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
...,...,...,...,...,...,...,...,...,...
264,NRJ-c5fefb01-2023-7,2023,Energy intensity,GJ/t milled,1.07,ON-MAIN-c5fefb01,-,NaN,SRC_WesdomeGoldMinesLtd._ESG_data_2023
265,NRJ-c5fefb01-2023-8,2023,Energy intensity,GJ/oz,5.78,ON-MAIN-c5fefb01,-,NaN,SRC_WesdomeGoldMinesLtd._ESG_data_2023
266,NRJ-CMP-d5f1c66b-2023-18,2023,Energy intensity of metals mining,GJ/t Cu-eq,40.3,-,-,CMP-d5f1c66b,SRC_Glencore_2024+ESG+data+book
267,NRJ-CMP-d5f1c66b-2023-19,2023,Energy intensity of metals smelting,GJ/t Cu-eq,30.3,-,-,CMP-d5f1c66b,SRC_Glencore_2024+ESG+data+book
268,NRJ-CMP-7a096012-2024-1,2024,NaN,NaN,NaN,-,-,CMP-7a096012,SRC_RioTinto_2024-sustainability-factbook

## Tailings table

In [191]:
tailings_table = tailings_gdf.rename(columns={'row_id': 'tailing_id',
                             'current_tailings_storage': 'current_storage'})
tailings_table = tailings_table[['tailing_id', 'year', 'tsf_name', 'status', 'construction_year', 
                             'raise_type', 'current_maximum_height', 'current_storage', 'hazard_categorization', 
                             'classification_system', 'geometry', 'main_id', 'source_id']]

## Land occupation table

In [275]:
# Change the Land-use values from m2 to km2
li_canada_gdf['area_km2'] = li_canada_gdf['Land_use'].apply(lambda x: x / 1e6 if pd.notna(x) else x)

KeyError: 'Land_use'

In [193]:
li_canada_gdf.rename(columns={'li_id': 'land_occupation_id'}, inplace=True)

In [195]:
li_canada_gdf = li_canada_gdf[['land_occupation_id', 'area_km2', 'geometry', 'main_id', 'source_id']]

In [300]:
tang_gdf = polygon_gdf.rename(columns={'tang_id': 'land_occupation_id'}, inplace=True)

In [308]:
polygon_gdf = polygon_gdf.to_crs(li_canada_gdf.crs)

In [309]:
# Add the li_canada_gdf to the polygon_gdf
land_occupation_table = pd.concat([polygon_gdf, li_canada_gdf], ignore_index=True)

In [310]:
land_occupation_table

,land_occupation_id,geometry,area_km2,source_id,main_id,tailing_id,distance_km,relation_type
0,6383,"POLYGON Z ((-71.95867 45.31898 0.00000, -71.95...",0.026130,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
1,6388,"POLYGON Z ((-71.93803 45.34130 0.00000, -71.93...",0.671399,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
2,6390,"POLYGON Z ((-71.92860 45.34214 0.00000, -71.92...",0.050909,https://doi.org/10.1038/s43247-023-00805-6,NaN,NaN,NaN,NaN
3,45954,"POLYGON Z ((-62.92042 44.98666 0.00000, -62.91...",2.622800,https://doi.org/10.1038/s43247-023-00805-6,NS-MAIN-c9c77a59,NaN,0.000000,one-to-many
4,45955,"POLYGON Z ((-62.92613 44.99168 0.00000, -62.92...",0.441869,https://doi.org/10.1038/s43247-023-00805-6,NS-MAIN-c9c77a59,NaN,1.186584,one-to-many
...,...,...,...,...,...,...,...,...
1951,QC-LI-219a2e44,"MULTIPOLYGON Z (((-79.08482 48.22969 0.00000, ...",2.926809,https://www.nature.com/articles/s41597-025-052...,QC-MAIN-30c1828c,NaN,NaN,NaN
1952,BC-LI-9c3aa818,"POLYGON Z ((-130.49620 56.64851 0.00000, -130....",0.122644,https://www.nature.com/articles/s41597-025-052...,BC-MAIN-b1fe389a,NaN,NaN,NaN
1953,ON-LI-1a9a061c,"MULTIPOLYGON Z (((-81.36899 48.67882 0.00000, ...",4.202254,https://www.nature.com/articles/s41597-025-052...,ON-MAIN-f8313ebd,NaN,NaN,NaN
1954,QC-LI-94bd8222,"POLYGON Z ((-79.22196 49.57467 0.00000, -79.22...",6.202897,https://www.nature.com/articles/s41597-025-052...,QC-MAIN-b86f7d07,NaN,NaN,NaN
1955,MB-LI-3e566fc3,"MULTIPOLYGON Z (((-101.09514 56.81934 0.00000,...",0.409644,https://www.nature.com/articles/s41597-025-052...,MB-MAIN-6fca9d6d,NaN,NaN,NaN

In [311]:
land_occupation_table = land_occupation_table[['land_occupation_id', 'area_km2', 'geometry', 'distance_km', 'main_id', 'tailing_id', 'source_id']]

In [358]:
# Drop duplicates caused by tailing id, so drop duplicates only on the 
land_occupation_table = land_occupation_table.drop_duplicates(subset=['land_occupation_id'])

In [359]:
land_occupation_table

,land_occupation_id,area_km2,distance_km,main_id,tailing_id,source_id
0,6383,0.026130,NaN,NaN,NaN,https://doi.org/10.1038/s43247-023-00805-6
1,6388,0.671399,NaN,NaN,NaN,https://doi.org/10.1038/s43247-023-00805-6
2,6390,0.050909,NaN,NaN,NaN,https://doi.org/10.1038/s43247-023-00805-6
3,45954,2.622800,0.000000,NS-MAIN-c9c77a59,NaN,https://doi.org/10.1038/s43247-023-00805-6
4,45955,0.441869,1.186584,NS-MAIN-c9c77a59,NaN,https://doi.org/10.1038/s43247-023-00805-6
...,...,...,...,...,...,...
1951,QC-LI-219a2e44,2.926809,NaN,QC-MAIN-30c1828c,NaN,https://www.nature.com/articles/s41597-025-052...
1952,BC-LI-9c3aa818,0.122644,NaN,BC-MAIN-b1fe389a,NaN,https://www.nature.com/articles/s41597-025-052...
1953,ON-LI-1a9a061c,4.202254,NaN,ON-MAIN-f8313ebd,NaN,https://www.nature.com/articles/s41597-025-052...
1954,QC-LI-94bd8222,6.202897,NaN,QC-MAIN-b86f7d07,NaN,https://www.nature.com/articles/s41597-025-052...
1955,MB-LI-3e566fc3,0.409644,NaN,MB-MAIN-6fca9d6d,NaN,https://www.nature.com/articles/s41597-025-052...

## By-product

In [203]:
bth_table = bth_df.drop(columns=['facility_name'])

In [204]:
bth_table

,host,by_product,ratio,main_id,source_id
0,Pt,Te,0.007718,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
1,Pt,Se,0.322126,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
2,Pt,Pd,0.748792,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
3,Pt,Sb,0.000140,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
4,Pt,Cd,0.003384,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
5,Pt,Cu,464.022279,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
6,Pt,Ni,520.996018,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
7,Pt,Bi,0.000957,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
8,Pt,Au,0.117581,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
9,Pt,Co,44.429615,ON-MAIN-a3c56a83,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
10,Cu,Ag,0.002674,ON-MAIN-f8313ebd,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
11,Cu,In,0.002522,ON-MAIN-f8313ebd,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
12,Cu,Zn,2.558461,ON-MAIN-f8313ebd,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
13,Cu,Ag,0.000264,BC-MAIN-aa76f6f2,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
14,Cu,Au,0.000080,BC-MAIN-aa76f6f2,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
15,Au,Cu,5471.571796,BC-MAIN-ed23117f,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
16,Au,Ag,3.900797,QC-MAIN-e51eda66,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
17,Au,Cu,506.207255,QC-MAIN-e51eda66,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
18,Au,Zn,1796.149997,QC-MAIN-e51eda66,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
19,Cu,Ag,0.000293,BC-MAIN-3f490561,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
20,Cu,Au,0.000107,BC-MAIN-3f490561,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
21,Cu,Ag,0.001037,BC-MAIN-b4655afb,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
22,Cu,Au,0.000058,BC-MAIN-b4655afb,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
23,Cu,Mo,0.031455,BC-MAIN-6b4800fe,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
24,Cu,Re,0.000016,BC-MAIN-6b4800fe,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
25,Cu,Ag,0.000339,BC-MAIN-8eb8be0d,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
26,Cu,Au,0.000104,BC-MAIN-8eb8be0d,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
27,Ni,Pt,0.000029,QC-MAIN-a97821c0,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
28,Ni,Pd,0.000072,QC-MAIN-a97821c0,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
29,Ni,Cu,0.289924,QC-MAIN-a97821c0,https://pubs.acs.org/doi/10.1021/acs.est.4c05293
30,Ni,Co,0.022447,QC-MAIN-a97821c0,https://pubs.acs.org/doi/10.1021/acs.est.4c05293

## Archetypes table

In [205]:
archetype_table = archetypes_df.rename(columns={'row_id': 'archetype_id'})
archetype_table = archetype_table[['archetype_id', 'deposit_type', 'mining_depth', 'mining_method', 'processing_method', 'main_id', 'facility_group_id', 'source_id']]

In [206]:
archetype_table

,archetype_id,deposit_type,mining_depth,mining_method,processing_method,main_id,facility_group_id,source_id
0,ARCH-d29e0839-1,VMS,NaN,Shrinkage stoping\nRoom-and-pillar\nLonghole s...,NaN,QC-MAIN-d29e0839,-,SRC_AbcourtMinesInc_MDO
1,ARCH-1f126a43-1,Disseminated gold deposit,NaN,"Open pit, conventional truck and shovel; remot...","Conventional crushing, grinding, gravity conce...",ON-MAIN-1f126a43,-,SRC_AgnicoEagleMinesLimited_TR_2021
2,ARCH-e7e6a960-1,Disseminated and structurally controlled lode ...,NaN,"Open pit, conventional truck and shovel method","Crushing, grinding, gravity concentration, cya...",QC-MAIN-e7e6a960,-,SRC_AgnicoEagleMinesLimited_TR_2021
3,ARCH-8b0264c9-1,Vein / narrow vein\nSkarn\nHydrothermal,NaN,Truck & Shovel / Loader\nLonghole stoping,NaN,NU-MAIN-8b0264c9,-,SRC_AgnicoEagleMinesLimited_MDO
4,ARCH-4ea8ac9d-1,Polymetallic massive sulphide and lode gold de...,NaN,Longitudinal and transverse longhole open stop...,NaN,NU-MAIN-4ea8ac9d,-,SRC_AgnicoEagleMinesLimited_TR_2023
...,...,...,...,...,...,...,...,...
72,ARCH-63b394c3-1,Magmatic,NaN,Slot-Slash\nMechanized Cut & Fill\nTransverse ...,NaN,ON-MAIN-63b394c3,-,SRC_Vale_MDO
73,ARCH-e05ed9fe-1,Vein / narrow vein\nIntrusion related,NaN,Truck & Shovel / Loader,NaN,YT-MAIN-e05ed9fe,-,SRC_VictoriaGoldCorporation_MDO
74,ARCH-9de9bb0d-1,Mesothermal\nVein / narrow vein,NaN,Longhole stoping\nAlimak\nSub-level open stopi...,NaN,QC-MAIN-9de9bb0d,-,SRC_WesdomeGoldMinesLtd_MDO
75,ARCH-c5fefb01-1,Vein / narrow vein\nBreccia pipe / Stockwork\n...,NaN,Longhole stoping\nLongitudinal retreat,NaN,ON-MAIN-c5fefb01,-,SRC_WesdomeGoldMinesLtd_MDO
76,ARCH-cb85213a-1,Vein / narrow vein\nMesothermal,NaN,Truck & Shovel / Loader,NaN,ON-MAIN-cb85213a,-,SRC_WesdomeGoldMinesLtd_MDO

## Water risk table

In [207]:
water_risk_table = water_risk_gdf.rename(columns={'row_id': 'water_risk_id'})
water_risk_table = water_risk_table[['water_risk_id', 'indicator', 'value', 'year', 'scenario', 'value', 'main_id', 'source_id']]

In [208]:
water_risk_table

,water_risk_id,indicator,value,year,scenario,value,main_id,source_id
0,water_risk-5801b453-2020-baseline-1,Water Stress Label,Low (<10%),2020,baseline,Low (<10%),QC-MAIN-5801b453,https://www.wri.org/data/aqueduct-global-maps-...
1,water_risk-5801b453-2020-baseline-2,Water Depletion Label,Low (<5%),2020,baseline,Low (<5%),QC-MAIN-5801b453,https://www.wri.org/data/aqueduct-global-maps-...
2,water_risk-5801b453-2020-baseline-3,Interannual Variability Label,Medium - High (0.50-0.75),2020,baseline,Medium - High (0.50-0.75),QC-MAIN-5801b453,https://www.wri.org/data/aqueduct-global-maps-...
3,water_risk-5801b453-2020-baseline-4,Groundwater Table Decline Label,Insignificant Trend,2020,baseline,Insignificant Trend,QC-MAIN-5801b453,https://www.wri.org/data/aqueduct-global-maps-...
4,water_risk-5801b453-2020-baseline-5,Coastal Eutrophication Potential Label,Low (<-5),2020,baseline,Low (<-5),QC-MAIN-5801b453,https://www.wri.org/data/aqueduct-global-maps-...
...,...,...,...,...,...,...,...,...
8635,water_risk-891d3cb5-2080-pes-2,Water Depletion Label,Low (<5%),2080,pes,Low (<5%),BC-MAIN-891d3cb5,https://www.wri.org/data/aqueduct-global-maps-...
8636,water_risk-891d3cb5-2080-pes-3,Interannual Variability Label,Low - Medium (0.25-0.50),2080,pes,Low - Medium (0.25-0.50),BC-MAIN-891d3cb5,https://www.wri.org/data/aqueduct-global-maps-...
8637,water_risk-891d3cb5-2080-opt-1,Water Stress Label,Low (<10%),2080,opt,Low (<10%),BC-MAIN-891d3cb5,https://www.wri.org/data/aqueduct-global-maps-...
8638,water_risk-891d3cb5-2080-opt-2,Water Depletion Label,Low (<5%),2080,opt,Low (<5%),BC-MAIN-891d3cb5,https://www.wri.org/data/aqueduct-global-maps-...
8639,water_risk-891d3cb5-2080-opt-3,Interannual Variability Label,Low - Medium (0.25-0.50),2080,opt,Low - Medium (0.25-0.50),BC-MAIN-891d3cb5,https://www.wri.org/data/aqueduct-global-maps-...

## Climate categories table

In [209]:
climate_category_table = climate_category_gdf.rename(columns={'row_id': 'climate_category_id'})
climate_category_table = climate_category_table[['climate_category_id', 'year', 'scenario', 'category', 'main_id', 'source_id']]

In [210]:
climate_category_table

,climate_category_id,year,scenario,category,main_id,source_id
0,CC-5801b453-1991_2020-historical-1,1991_2020,historical,"Dfb - Cold, no dry season, warm summer",QC-MAIN-5801b453,https://doi.org/10.1038/s41597-023-02549-6
1,CC-d29e0839-1991_2020-historical-1,1991_2020,historical,"Dfb - Cold, no dry season, warm summer",QC-MAIN-d29e0839,https://doi.org/10.1038/s41597-023-02549-6
2,CC-f1ff4920-1991_2020-historical-1,1991_2020,historical,"Dfb - Cold, no dry season, warm summer",QC-MAIN-f1ff4920,https://doi.org/10.1038/s41597-023-02549-6
3,CC-4ea8ac9d-1991_2020-historical-1,1991_2020,historical,"Dfc - Cold, no dry season, cold summer",NU-MAIN-4ea8ac9d,https://doi.org/10.1038/s41597-023-02549-6
4,CC-e7e6a960-1991_2020-historical-1,1991_2020,historical,"Dfb - Cold, no dry season, warm summer",QC-MAIN-e7e6a960,https://doi.org/10.1038/s41597-023-02549-6
...,...,...,...,...,...,...
2425,CC-c5fefb01-2071_2099-ssp585-1,2071_2099,ssp585,"Dfb - Cold, no dry season, warm summer",ON-MAIN-c5fefb01,https://doi.org/10.1038/s41597-023-02549-6
2426,CC-feb13c30-2071_2099-ssp585-1,2071_2099,ssp585,"Dsb - Cold, dry summer, warm summer",BC-MAIN-feb13c30,https://doi.org/10.1038/s41597-023-02549-6
2427,CC-5e0d8b48-2071_2099-ssp585-1,2071_2099,ssp585,"Dfc - Cold, no dry season, cold summer",YT-MAIN-5e0d8b48,https://doi.org/10.1038/s41597-023-02549-6
2428,CC-12c68d49-2071_2099-ssp585-1,2071_2099,ssp585,"Dfa - Cold, no dry season, hot summer",ON-MAIN-12c68d49,https://doi.org/10.1038/s41597-023-02549-6
2429,CC-891d3cb5-2071_2099-ssp585-1,2071_2099,ssp585,"Dfc - Cold, no dry season, cold summer",BC-MAIN-891d3cb5,https://doi.org/10.1038/s41597-023-02549-6

## Weather table

In [211]:
weather_table = weather_gdf.rename(columns={'row_id': 'weather_id'})
weather_table = weather_table[['weather_id', 'year', 'variable', 'value', 'unit', 'scenario', 'main_id', 'source_id']]

In [212]:
weather_table

,weather_id,year,variable,value,unit,scenario,main_id,source_id
0,weather-5801b453-2025-ssp126-1,2025,Daily Temperature Range,11.632902,°C,ssp126,QC-MAIN-5801b453,https://climate-scenarios.canada.ca/?page=CanD...
1,weather-5801b453-2030-ssp126-1,2030,Daily Temperature Range,11.683678,°C,ssp126,QC-MAIN-5801b453,https://climate-scenarios.canada.ca/?page=CanD...
2,weather-5801b453-2035-ssp126-1,2035,Daily Temperature Range,11.695585,°C,ssp126,QC-MAIN-5801b453,https://climate-scenarios.canada.ca/?page=CanD...
3,weather-5801b453-2040-ssp126-1,2040,Daily Temperature Range,11.721719,°C,ssp126,QC-MAIN-5801b453,https://climate-scenarios.canada.ca/?page=CanD...
4,weather-5801b453-2045-ssp126-1,2045,Daily Temperature Range,11.564794,°C,ssp126,QC-MAIN-5801b453,https://climate-scenarios.canada.ca/?page=CanD...
...,...,...,...,...,...,...,...,...
34555,weather-891d3cb5-2080-ssp585-2,2080,Annual Precipitation,807.612915,mm,ssp585,BC-MAIN-891d3cb5,https://climate-scenarios.canada.ca/?page=CanD...
34556,weather-891d3cb5-2085-ssp585-2,2085,Annual Precipitation,790.696106,mm,ssp585,BC-MAIN-891d3cb5,https://climate-scenarios.canada.ca/?page=CanD...
34557,weather-891d3cb5-2090-ssp585-2,2090,Annual Precipitation,800.068237,mm,ssp585,BC-MAIN-891d3cb5,https://climate-scenarios.canada.ca/?page=CanD...
34558,weather-891d3cb5-2095-ssp585-2,2095,Annual Precipitation,817.156982,mm,ssp585,BC-MAIN-891d3cb5,https://climate-scenarios.canada.ca/?page=CanD...
34559,weather-891d3cb5-2100-ssp585-2,2100,Annual Precipitation,841.397217,mm,ssp585,BC-MAIN-891d3cb5,https://climate-scenarios.canada.ca/?page=CanD...

## Conflict table

In [227]:
conflict_table = conflict_gdf

In [229]:
conflict_table = conflict_table[['ej_atlas_id', 'case_name', 'start_date', 'end_date', 
                             'conflict_description', 'conflict_details', 'population_affected',
                             'conflict_intensity', 'project_status', 'main_id', 'source_id']]

In [230]:
conflict_table

,ej_atlas_id,case_name,start_date,end_date,conflict_description,conflict_details,population_affected,conflict_intensity,project_status,main_id,source_id
9,4135,"Vale Mining in Voisey's Bay, Labrador, Canada",11/1994,None,<p>Voiseyâ€™s Bay nickel mine in Labrador was ...,"Voiseyâ€™s Bay is a â€œ6,000 tonnes-per-day fa...",Rural,"MEDIUM (street protests, visible mobilization)",In operation,NL-MAIN-2d8801d6,http://journals.librarypublishing.arizona.edu/...
10,4145,Port Colborne Class Action Lawsuit Against Val...,06/2000,04/2012,"<p>In Pearson (later Smith) v. Inco, the large...",Raw materials from Valeâ€™s Sudbury mining ope...,Urban,LOW (some local organising),In operation,ON-MAIN-2e13aaa0,http://journals.librarypublishing.arizona.edu/...
15,5599,Nouveau Mondeâ€™s Matawinie graphite mine in Q...,01/01/2017,None,<p>Five kilometers southwest of the municipali...,The project includes 319 mining concessions (c...,Rural,"MEDIUM (street protests, visible mobilization)",Under construction,QC-MAIN-d6748d40,http://journals.librarypublishing.arizona.edu/...

## Population table

In [231]:
population_table = population_gdf.rename(columns={'row_id': 'population_id'})
population_table = population_table[['population_id', 'year', 'buffer_size', 'total_population', 'main_id', 'source_id']]

In [232]:
population_table

,population_id,year,buffer_size,total_population,main_id,source_id
0,population-5801b453-2025-1,2025,10km,1305.901860,QC-MAIN-5801b453,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
1,population-5801b453-2025-2,2025,50km,63977.830574,QC-MAIN-5801b453,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
2,population-5801b453-2030-1,2030,10km,1338.088985,QC-MAIN-5801b453,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
3,population-5801b453-2030-2,2030,50km,65434.154098,QC-MAIN-5801b453,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
4,population-d29e0839-2025-1,2025,10km,0.000000,QC-MAIN-d29e0839,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
...,...,...,...,...,...,...
1075,population-12c68d49-2030-2,2030,50km,0.000000,ON-MAIN-12c68d49,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
1076,population-891d3cb5-2025-1,2025,10km,0.000000,BC-MAIN-891d3cb5,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
1077,population-891d3cb5-2025-2,2025,50km,297.622460,BC-MAIN-891d3cb5,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
1078,population-891d3cb5-2030-1,2030,10km,0.000000,BC-MAIN-891d3cb5,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...
1079,population-891d3cb5-2030-2,2030,50km,309.797150,BC-MAIN-891d3cb5,https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F4...

## Peatland table

In [233]:
peatland_table = peatland_gdf[['peatland_presence', 'main_id', 'source_id']]

In [234]:
peatland_table

,peatland_presence,main_id,source_id
0,No data,QC-MAIN-5801b453,https://greifswaldmoor.de/global-peatland-data...
1,peat in soil mosaic,QC-MAIN-d29e0839,https://greifswaldmoor.de/global-peatland-data...
2,peat dominated,QC-MAIN-f1ff4920,https://greifswaldmoor.de/global-peatland-data...
3,No data,NU-MAIN-4ea8ac9d,https://greifswaldmoor.de/global-peatland-data...
4,No data,QC-MAIN-e7e6a960,https://greifswaldmoor.de/global-peatland-data...
...,...,...,...
265,No data,ON-MAIN-c5fefb01,https://greifswaldmoor.de/global-peatland-data...
266,No data,BC-MAIN-feb13c30,https://greifswaldmoor.de/global-peatland-data...
267,No data,YT-MAIN-5e0d8b48,https://greifswaldmoor.de/global-peatland-data...
268,peat dominated,ON-MAIN-12c68d49,https://greifswaldmoor.de/global-peatland-data...
269,No data,BC-MAIN-891d3cb5,https://greifswaldmoor.de/global-peatland-data...

## Prioritization area table

In [235]:
prioritization_area_gdf

,main_id,facility_name,geometry,jung_priority_point,jung_priority_mean_50km,source_id
0,QC-MAIN-5801b453,Abcourt-Barvue,POINT (-77.67901 48.52154),25.926612,22.025641,https://doi.org/10.5281/zenodo.5006332
1,QC-MAIN-d29e0839,Sleeping Giant,POINT (-77.97434 49.13259),13.000000,15.775000,https://doi.org/10.5281/zenodo.5006332
2,QC-MAIN-f1ff4920,Akasaba West,POINT (-77.58000 48.04000),20.618888,21.125000,https://doi.org/10.5281/zenodo.5006332
3,NU-MAIN-4ea8ac9d,Amaruq,POINT (-96.69700 65.41500),63.927000,58.076923,https://doi.org/10.5281/zenodo.5006332
4,QC-MAIN-e7e6a960,Canadian Malartic,POINT (-78.13082 48.12222),21.186758,21.166667,https://doi.org/10.5281/zenodo.5006332
...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,POINT (-85.45250 48.11028),21.298652,19.614286,https://doi.org/10.5281/zenodo.5006332
266,BC-MAIN-feb13c30,Record Ridge,POINT (-117.88400 49.08200),47.846798,41.093333,https://doi.org/10.5281/zenodo.5006332
267,YT-MAIN-5e0d8b48,Casino,POINT (-138.83333 62.73333),67.371530,66.961039,https://doi.org/10.5281/zenodo.5006332
268,ON-MAIN-12c68d49,Eagle's Nest,POINT (-86.30380 52.74202),14.300865,14.189873,https://doi.org/10.5281/zenodo.5006332
269,BC-MAIN-891d3cb5,Akie,POINT (-124.86599 57.38088),35.079117,35.333333,https://doi.org/10.5281/zenodo.5006332

In [236]:
prioritization_conservation_area_table = prioritization_area_gdf.rename(columns={
    'jung_priority_point': 'score_1_km',
    'jung_priority_mean_50km': 'mean_score_50_km',})
prioritization_conservation_area_table = prioritization_conservation_area_table[['score_1_km', 'mean_score_50_km', 'main_id', 'source_id']]

In [237]:
prioritization_conservation_area_table

,score_1_km,mean_score_50_km,main_id,source_id
0,25.926612,22.025641,QC-MAIN-5801b453,https://doi.org/10.5281/zenodo.5006332
1,13.000000,15.775000,QC-MAIN-d29e0839,https://doi.org/10.5281/zenodo.5006332
2,20.618888,21.125000,QC-MAIN-f1ff4920,https://doi.org/10.5281/zenodo.5006332
3,63.927000,58.076923,NU-MAIN-4ea8ac9d,https://doi.org/10.5281/zenodo.5006332
4,21.186758,21.166667,QC-MAIN-e7e6a960,https://doi.org/10.5281/zenodo.5006332
...,...,...,...,...
265,21.298652,19.614286,ON-MAIN-c5fefb01,https://doi.org/10.5281/zenodo.5006332
266,47.846798,41.093333,BC-MAIN-feb13c30,https://doi.org/10.5281/zenodo.5006332
267,67.371530,66.961039,YT-MAIN-5e0d8b48,https://doi.org/10.5281/zenodo.5006332
268,14.300865,14.189873,ON-MAIN-12c68d49,https://doi.org/10.5281/zenodo.5006332
269,35.079117,35.333333,BC-MAIN-891d3cb5,https://doi.org/10.5281/zenodo.5006332

# Exports

## Exports tables to CSV

In [338]:
# Export all the tables to CSV
main_gdf.to_csv(r'database/CSV/main_table.csv', index=False, encoding="utf-8-sig")
production_table.to_csv(r'database/CSV/production_table.csv', index=False, encoding="utf-8-sig")
env_table.to_csv(r'database/CSV/env_table.csv', index=False, encoding="utf-8-sig")
land_cover_table.to_csv(r'database/CSV/land_cover_table.csv', index=False, encoding="utf-8-sig")
env_int_df.to_csv(r'database/CSV/env_int_table.csv', index=False, encoding="utf-8-sig")
reserves_df.to_csv(r'database/CSV/reserves_table.csv', index=False, encoding="utf-8-sig")
energy_df.to_csv(r'database/csv/energy_table.csv', index=False, encoding="utf-8-sig")
tailings_gdf.to_csv(r'database/CSV/tailings_table.csv', index=False, encoding="utf-8-sig")
polygon_gdf.to_csv(r'database/CSV/land_occupation_table.csv', index=False, encoding="utf-8-sig")
archetypes_df.to_csv(r'database/CSV/archetypes_table.csv', index=False, encoding="utf-8-sig")
water_risk_gdf.to_csv(r'database/CSV/water_risk_table.csv', index=False, encoding="utf-8-sig")
climate_category_gdf.to_csv(r'database/CSV/climate_category_table.csv', index=False, encoding="utf-8-sig")
weather_gdf.to_csv(r'database/CSV/weather_table.csv', index=False, encoding="utf-8-sig")
conflict_gdf.to_csv(r'database/CSV/conflict_table.csv', index=False, encoding="utf-8-sig")
population_gdf.to_csv(r'database/CSV/population_table.csv', index=False, encoding="utf-8-sig")
peatland_gdf.to_csv(r'database/CSV/peatland_table.csv', index=False, encoding="utf-8-sig")
prioritization_area_gdf.to_csv(r'database/CSV/prioritization_area_table.csv', index=False, encoding="utf-8-sig")
bth_df.to_csv(r'database/CSV/bth_table.csv', index=False, encoding="utf-8-sig")
protected_land_table.to_csv(r'database/CSV/protected_land_table.csv', index=False, encoding="utf-8-sig")

In [339]:
# We remove the geometry column to avoid issues with large file size
#protected_land_table.drop(columns=['geometry'], inplace=True)
protected_land_table.to_csv(r'database/CSV/protected_land_table.csv', index=False, encoding="utf-8-sig")

## Export DB to SQLite

In [254]:
from matching_functions import create_and_populate_database

In [367]:
tables_dict = {
    "Main": main_gdf,
    
    "Sources": source_table, 
    "Substances": substance_table,
    "Compartments": compartment_table,
    
    "Reserves_resources": reserves_table,
    "Production": production_table,
    "Energy": energy_table,
    "Environmental_flows": env_table,
    "Environmental_intensity": env_int_table,
    "Archetypes": archetype_table,
    
    "Tailings": tailings_table,
    "Land_occupation": land_occupation_table,
    "By_products": bth_table,
    
    "Water_risk": water_risk_table,
    "Climate_category": climate_category_table,
    "Weather": weather_table,
    "Land_cover": land_cover_table,
    "Conflict": conflict_table,
    "Population": population_table,
    "Peatland": peatland_table,
    "Prioritization_conservation_areas": prioritization_conservation_area_table,
    "Protected_indigenous_lands": protected_land_table,
    
}

# Run the function
create_and_populate_database(
    db_path="database/metallican.sqlite",
    schema_path="database/schema.sql",
    tables_dict=tables_dict,
    keep_geometry_tables=["main", "tailings", "polygons"]
)

✅ Old database 'database/metallican11.sqlite' deleted
✅ Empty database structure created at 'database/metallican11.sqlite'
🔄 Converting geometries...
✅ Geometries handled (kept only where needed)
✅ New connection opened
✅ Inserted 270 rows into 'Main'
✅ Inserted 205 rows into 'Sources'
✅ Inserted 174 rows into 'Substances'
✅ Inserted 41 rows into 'Compartments'
✅ Inserted 394 rows into 'Reserves_resources'
✅ Inserted 390 rows into 'Production'
✅ Inserted 269 rows into 'Energy'
✅ Inserted 14525 rows into 'Environmental_flows'
✅ Inserted 96 rows into 'Environmental_intensity'
✅ Inserted 77 rows into 'Archetypes'
✅ Inserted 86 rows into 'Tailings'
✅ Inserted 1920 rows into 'Land_occupation'
✅ Inserted 31 rows into 'By_products'
✅ Inserted 8640 rows into 'Water_risk'
✅ Inserted 2430 rows into 'Climate_category'
✅ Inserted 34560 rows into 'Weather'
✅ Inserted 270 rows into 'Land_cover'
✅ Inserted 3 rows into 'Conflict'
✅ Inserted 1080 rows into 'Population'
✅ Inserted 270 rows into 'Peatland'
✅ Inserted 270 rows into 'Prioritization_conservation_areas'
✅ Inserted 8795 rows into 'Protected_indigenous_lands'
✅ No foreign key problems found!
✅ Connection closed properly