In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

# Imports

In [2]:
main_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/main_gdf.parquet")
tailings_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/tailings_gdf.parquet")
cmmi_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/cmmi_gdf.parquet")
min_can_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/min_can_gdf.parquet")
ctrace_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/ctrace_gdf.parquet")
conflict_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/conflict_gdf.parquet")
ghg_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/ghg_gdf.parquet")
npri_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/pollutant_gdf.parquet")
climate_category_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/climate_category_gdf.parquet")
weather_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/weather_gdf.parquet")
peatland_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/peatland_gdf.parquet")
prioritization_area_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/prioritization_area_gdf.parquet")
population_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/population_gdf.parquet")
water_risk_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/water_risk_gdf.parquet")
land_cover_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/land_cover_gdf.parquet")
npv_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/npv_gdf.parquet")
indigenous_can_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/indigenous_can_gdf.parquet")
wpda_gdf_polygons = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/wpda_gdf_polygons.parquet")
tang_canada_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/tang_canada_gdf.parquet")
li_canada_gdf = gpd.read_parquet("data/Tables/Raw_datasets/GeoParquet/li_canada_gdf.parquet")

In [3]:
bth_df = pd.read_excel(r'data/Mappings/BtH_mapped_sites.xlsx')

In [4]:
# From manually collected data
production_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Production')
tech_attributes_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Technical_attributes')
reserves_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Reserves')
technosphere_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='NRJ_mat')
env_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Env')
waste_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Waste')                       
intensity_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Intensity')
archetypes_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Archetype')

In [5]:
from db_creation_function import assign_row_id_to_collected_data

In [6]:
# We need to assign row_ids to the manually collected data
production_df = assign_row_id_to_collected_data(production_df, 
                  facility_id_col='main_id',
                  prefix='PROD',
                  year_col='year'           
                  )

tech_attributes_df = assign_row_id_to_collected_data(tech_attributes_df, 
                  facility_id_col='main_id',
                  prefix='TA',
                  year_col='year'           
                  )
reserves_df = assign_row_id_to_collected_data(reserves_df, 
                  facility_id_col='main_id',
                  prefix='RES',
                  year_col='year'           
                  )

technosphere_df = assign_row_id_to_collected_data(technosphere_df, 
                  facility_id_col='main_id',
                  prefix='TECH',
                  year_col='year'           
                  )

env_df = assign_row_id_to_collected_data(env_df, 
                  facility_id_col='main_id',
                  prefix='ENV',
                  year_col='year'           
                  )

waste_df = assign_row_id_to_collected_data(waste_df, 
                  facility_id_col='main_id',
                  prefix='WASTE',
                  year_col='year'           
                  )

intensity_df = assign_row_id_to_collected_data(intensity_df, 
                  facility_id_col='main_id',
                  prefix='INT',
                  year_col='year'           
                  )

archetypes_df = assign_row_id_to_collected_data(archetypes_df, 
                  facility_id_col='main_id',
                  prefix='ARCH',
                  )

# Create auxiliary tables

## Source table

In [7]:
# For the main table
source_map = {
    "project": "https://open.canada.ca/data/en/dataset/22b2db8a-dc12-47f2-9737-99d3da921751",
    "mining": "https://open.canada.ca/data/en/dataset/000183ed-8864-42f0-ae43-c4313a860720",
    "manufacturing": "https://open.canada.ca/data/en/dataset/000183ed-8864-42f0-ae43-c4313a860720"
}
main_gdf["source_id"] = main_gdf["facility_type"].map(source_map)
main_gdf

,main_id,facility_name,facility_group_name,facility_group_id,reported_company,company_name_folder,company_id,longitude,latitude,geometry,...,province,status,activity_status,development_stage,facility_type,mining_processing_type,commodity_group,primary_commodity,commodities,source_id
0,QC-MAIN-5801b453,Abcourt-Barvue,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.679010,48.521540,POINT (-77.67901 48.52154),...,Quebec,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, silver",https://open.canada.ca/data/en/dataset/22b2db8...
1,QC-MAIN-d29e0839,Sleeping Giant,None,None,Abcourt Mines Inc.,Abcourt Mines Inc,CMP-0a6a3062,-77.974340,49.132590,POINT (-77.97434 49.13259),...,Quebec,active_facility,None,None,mining,Concentrator,Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...
2,QC-MAIN-f1ff4920,Akasaba West,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-77.580000,48.040000,POINT (-77.58000 48.04000),...,Quebec,project_facility,Active,Advanced project,project,None,None,Gold,"Gold, copper",https://open.canada.ca/data/en/dataset/22b2db8...
3,NU-MAIN-4ea8ac9d,Amaruq,Meadowbank complex,GRP-0a2c0d69,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-96.697000,65.415000,POINT (-96.69700 65.41500),...,Nunavut,active_facility,None,None,mining,"Open-pit, underground",Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...
4,QC-MAIN-e7e6a960,Canadian Malartic,None,None,Agnico Eagle Mines Limited,Agnico Eagle Mines Limited,CMP-6265c407,-78.130824,48.122223,POINT (-78.13082 48.12222),...,Quebec,active_facility,None,None,mining,"Open-pit, concentrator",Precious metals,Gold,"Gold, silver",https://open.canada.ca/data/en/dataset/000183e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,ON-MAIN-c5fefb01,Mishi,None,None,Wesdome Gold Mines Ltd.,Wesdome Gold Mines Ltd,CMP-3d2c4955,-85.452500,48.110280,POINT (-85.45250 48.11028),...,Ontario,active_facility,None,None,mining,Open-pit,Precious metals,Gold,Gold,https://open.canada.ca/data/en/dataset/000183e...
266,BC-MAIN-feb13c30,Record Ridge,None,None,West High Yield Resources Ltd.,West High Yield Resources Ltd,CMP-1023f9c0,-117.884000,49.082000,POINT (-117.88400 49.08200),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Magnesium,Magnesium,https://open.canada.ca/data/en/dataset/22b2db8...
267,YT-MAIN-5e0d8b48,Casino,None,None,Western Copper and Gold Corporation,Western Copper and Gold Corporation,CMP-2dac9896,-138.833330,62.733330,POINT (-138.83333 62.73333),...,Yukon,project_facility,Active,Advanced project,project,None,None,Copper,"Copper, gold, molybdenum, silver",https://open.canada.ca/data/en/dataset/22b2db8...
268,ON-MAIN-12c68d49,Eagle's Nest,None,None,Wyloo,Wyloo,CMP-65b36728,-86.303800,52.742020,POINT (-86.30380 52.74202),...,Ontario,project_facility,Active,Advanced project,project,None,None,Nickel,"Nickel, copper, gold, platinum, palladium",https://open.canada.ca/data/en/dataset/22b2db8...
269,BC-MAIN-891d3cb5,Akie,None,None,ZincX Resources Corp.,ZincX Resources Corp,CMP-3416049b,-124.865990,57.380880,POINT (-124.86599 57.38088),...,British Columbia,project_facility,Active,Advanced project,project,None,None,Zinc,"Zinc, lead, silver",https://open.canada.ca/data/en/dataset/22b2db8...

In [8]:
# For the datasets
tailings_gdf["source_id"] = 'https://tailing.grida.no/'
min_can_gdf["source_id"] = '10.1038/s41597-024-03116-3'
ctrace_gdf["source_id"] = 'Jolleys, M. et al (2024). Mineral Extraction sector: Mining and Quarrying Emissions from Copper, Iron, Bauxite, Rock and Sand, Hypervine, UK, Climate TRACE Emissions Inventory'
conflict_gdf["source_id"] = 'http://journals.librarypublishing.arizona.edu/jpe/article/id/1932/'
ghg_gdf["source_id"] = 'https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions/large-facilities.html'
npri_gdf["source_id"] = 'https://www.canada.ca/en/environment-climate-change/services/national-pollutant-release-inventory/tools-resources-data/exploredata.html' 
prioritization_area_gdf['source_id'] = 'https://doi.org/10.5281/zenodo.5006332'
climate_category_gdf['source_id'] = 'https://doi.org/10.1038/s41597-023-02549-6'
weather_gdf['source_id'] = 'https://climate-scenarios.canada.ca/?page=CanDCS6-indices'
peatland_gdf['source_id'] = 'https://greifswaldmoor.de/global-peatland-database-en.html'
population_gdf['source_id'] = 'https://doi.org/10.2905/2FF68A52-5B5B-4A22-8F40-C41DA8332CFE' 
water_risk_gdf['source_id'] = 'https://www.wri.org/data/aqueduct-global-maps-40-data'
land_cover_gdf['source_id'] = 'https://doi.org/10.5067/MODIS/MCD12Q1.061 + https://doi.org/10.5281/zenodo.7254221'
npv_gdf['source_id'] = 'https://doi.org/10.7717/peerj.5457'
indigenous_can_gdf['source_id'] = 'http://www.landmarkmap.org'
wpda_gdf_polygons['source_id'] = 'https://www.protectedplanet.net'
tang_canada_gdf['source_id'] = 'https://doi.org/10.1038/s43247-023-00805-6'
#maus_canada_gdf['source_id'] = 'https://doi.org/10.1038/s41597-022-01547-4'
li_canada_gdf['source_id'] = 'https://www.nature.com/articles/s41597-025-05296-y'
bth_df['source_id'] = 'https://pubs.acs.org/doi/10.1021/acs.est.4c05293'

In [9]:
from db_creation_function import add_source_id_to_collected_data

In [10]:
production_df = add_source_id_to_collected_data(production_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

tech_attributes_df = add_source_id_to_collected_data(tech_attributes_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

reserves_df = add_source_id_to_collected_data(reserves_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

technosphere_df = add_source_id_to_collected_data(technosphere_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

env_df = add_source_id_to_collected_data(env_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

waste_df = add_source_id_to_collected_data(waste_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

intensity_df = add_source_id_to_collected_data(intensity_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

archetypes_df = add_source_id_to_collected_data(archetypes_df, 
                                    company_col="reported_company_nrcan", 
                                    facility_col="name", 
                                    source_col="source")

In [11]:
from db_creation_function import create_source_table_from_datasets

In [12]:
dataset_dict = {
    "Global Tailings Portal": tailings_gdf,
    "A Comprehensive Historical and Geolocalized Database of Mining Activities in Canada": min_can_gdf,
    "ClimateTRACE mineral extraction sector": ctrace_gdf,
    "Environmental Justice Atlas": conflict_gdf,
    "GHG from large facilities": ghg_gdf,
    "National Pollutant Inventory Report (NPRI)": npri_gdf,
    "Areas of global importance for conserving terrestrial biodiversity, carbon and water": prioritization_area_gdf,
    "High-Resolution (1 km) Koppen-Geiger Maps for 1901–2099 Based on Constrained CMIP6 Projections": climate_category_gdf,
    "CMIP6 statistically downscaled climate indices (CanDCS-M6)": weather_gdf,
    "Global Peatland Database": peatland_gdf,
    "Global Human Settlement Layer (GHSL)": population_gdf,
    "Aqueduct 4.0": water_risk_gdf,
    "Modis Land Cover and ESA World Cover": land_cover_gdf,
    "Potential Natural Vegetation (NPV)": npv_gdf,
    "Indigenous Peoples’ and Local Community Lands and Territories": indigenous_can_gdf,
    "World Database on Protected Areas (WDPA)": wpda_gdf_polygons,
    "Global Mining Footprint Mapped from High-Resolution Satellite Imagery": tang_canada_gdf,
    "Machine learning-enhanced monitoring of global copper mining areas": li_canada_gdf,
    "Byproduct-to-Host Ratios for Assessing the Accessibility of Mineral Resources": bth_df,
}

manual_dfs = [production_df, tech_attributes_df, reserves_df, technosphere_df, env_df, waste_df, intensity_df, archetypes_df] 

source_table = create_source_table_from_datasets(dataset_dict, manual_dfs)

In [13]:
source_table

,source_id,source_provenance,source_name
0,https://tailing.grida.no/,dataset,Global Tailings Portal
18,https://pubs.acs.org/doi/10.1021/acs.est.4c05293,dataset,Byproduct-to-Host Ratios for Assessing the Acc...
17,https://www.nature.com/articles/s41597-025-052...,dataset,Machine learning-enhanced monitoring of global...
16,https://doi.org/10.1038/s43247-023-00805-6,dataset,Global Mining Footprint Mapped from High-Resol...
15,https://www.protectedplanet.net,dataset,World Database on Protected Areas (WDPA)
...,...,...,...
100,SRC_AgnicoEagleMinesLimited_2024_MRMR,report,2024_MRMR
101,SRC_IronOreCompanyofCanadaInc._rt-fact-book-ad...,report,rt-fact-book-addendum.xlsx
102,SRC_IronOreCompanyofCanadaInc._nan,report,nan
134,SRC_HeclaMiningCompany_SR_2023,report,SR_2023.pdf
272,SRC_SSRMiningInc_nan,report,nan

In [14]:
source_table.to_csv(r'database/CSV/sources_table.csv', index=False)

## Substance table

In [15]:
# Get unique substance name and cas number in a new df
npri_substance_df = npri_gdf[['substance_name_npri', 'cas_number']].drop_duplicates().copy()

In [16]:
# Add a type column = 'Group of substances' if the cas_number starts with 'NA' and = 'Substance' if not 
npri_substance_df = npri_substance_df.assign(
    type=lambda x: np.where(x['cas_number'].str.startswith('NA'), 'Group of substances', 'Substance')
)

In [17]:
npri_substance_df.rename(columns={
    'substance_name_npri': 'substance_name',
    'cas_number': 'substance_id',
    'type': 'substance_type'
}, inplace=True)

In [18]:
# Reorganize the columns
npri_substance_df = npri_substance_df[['substance_id', 'substance_type', 'substance_name']].copy()

In [19]:
npri_substance_df

     substance_id       substance_type                substance_name
0         NA - 16  Group of substances               Ammonia (total)
1         NA - 02  Group of substances   Arsenic (and its compounds)
2        630-08-0            Substance               Carbon monoxide
3         NA - 04  Group of substances  Chromium (and its compounds)
4         NA - 05  Group of substances    Cobalt (and its compounds)
...           ...                  ...                           ...
6661     189-64-0            Substance            Dibenzo[a,h]pyrene
7179      71-43-2            Substance       Speciated VOC - Benzene
7677    1332-21-4            Substance  Asbestos (friable form only)
7900    7681-49-4            Substance               Sodium fluoride
8210      NA - 46  Group of substances             Azo disperse dyes

[104 rows x 3 columns]

In [20]:
env_substance_df = env_df[['substance_type', 'substance_name', 'cas_number']].drop_duplicates().copy()

In [21]:
env_substance_df = env_substance_df.dropna(how='all').copy()

In [22]:
env_substance_df.rename(columns={'cas_number': 'substance_id'}, inplace=True)

In [23]:
# Reorganize the columns
env_substance_df = env_substance_df[['substance_id', 'substance_type', 'substance_name']].copy()

In [24]:
# Put the two dataframes together
substance_table = pd.concat([npri_substance_df, env_substance_df], ignore_index=True).drop_duplicates().reset_index(drop=True)

In [25]:
substance_table

         substance_id       substance_type                substance_name
0             NA - 16  Group of substances               Ammonia (total)
1             NA - 02  Group of substances   Arsenic (and its compounds)
2            630-08-0            Substance               Carbon monoxide
3             NA - 04  Group of substances  Chromium (and its compounds)
4             NA - 05  Group of substances    Cobalt (and its compounds)
..                ...                  ...                           ...
120        10024-97-2            Substance                           N2O
121         NA - PFCs  Group of substances                          PFCs
122           NA - 02            Substance                       Arsenic
123           NA - 12  Group of substances                      Selenium
124  NA - Particulate  Group of substances                   Particulate

[125 rows x 3 columns]

In [26]:
# For CTrace and GHG datasets, put the substance_id as 'NA - GHG'
ctrace_gdf['substance_id'] = 'NA - GHG'
ghg_gdf['substance_id'] = 'NA - GHG'

In [28]:
substance_table.to_csv(r'database/CSV/substances_table.csv', index=False)

## Compartment table

In [29]:
npri_gdf['emission_type'] = npri_gdf['emission_type'].replace({
    'Air Emissions / Émissions à l\'air': 'Air',
    'Water Releases / Rejets à l\'eau': 'Water',
    'Land Releases /  Rejets au sol': 'Land',
    'On-Site Disposal / Élimination sur le site': 'On-Site Disposal',
    'Off-Site Disposal / Élimination hors site': 'Off-Site Disposal',
    'Transfers for Treatment / Transferts pour traitement': 'Transfers for Treatment',
    'Transfers for Recycling / Transferts pour recyclage': 'Transfers for Recycling',
})

In [30]:
npri_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,cas_number,substance_name_npri,substance_unit,emission_type,emission_subtype,value,source_id,geometry
0,npri-1568-2023-1,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.087340,48.130320,Boreal Shield,St. Lawrence Drainage Area,NA - 16,Ammonia (total),tonnes,Air,Stack Emissions,0.636,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032)
1,npri-1568-2023-2,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.087340,48.130320,Boreal Shield,St. Lawrence Drainage Area,NA - 02,Arsenic (and its compounds),kg,Air,Stack Emissions,0.116,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032)
2,npri-1568-2023-3,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.087340,48.130320,Boreal Shield,St. Lawrence Drainage Area,630-08-0,Carbon monoxide,tonnes,Air,Stack Emissions,76.208,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032)
3,npri-1568-2023-4,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.087340,48.130320,Boreal Shield,St. Lawrence Drainage Area,NA - 04,Chromium (and its compounds),tonnes,Air,Stack Emissions,0.00105,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032)
4,npri-1568-2023-5,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.087340,48.130320,Boreal Shield,St. Lawrence Drainage Area,NA - 05,Cobalt (and its compounds),kg,Air,Stack Emissions,0.18,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8522,npri-3824-2023-206,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 11,Nickel (and its compounds),tonnes,Transfers for Recycling,Other,0.3233,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780)
8523,npri-3824-2023-207,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 22,Phosphorus (total),tonnes,Transfers for Recycling,Other,1.7886,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780)
8524,npri-3824-2023-208,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 14,Zinc (and its compounds),tonnes,Transfers for Recycling,Other,4.6224,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780)
8525,npri-3812-2023-34,2023,3812,Sivaco Québec,None,manufacturing,-73.167875,45.429756,Mixedwood Plain,St. Lawrence Drainage Area,7647-01-0,Hydrochloric acid,tonnes,Transfers for Recycling,Other,23.27,https://www.canada.ca/en/environment-climate-c...,POINT (-73.16787 45.42976)
8526,npri-2256-2023-54,2023,2256,Tonolli Canada,None,manufacturing,-79.579990,43.603780,Mixedwood Plain,St. Lawrence Drainage Area,7664-93-9,Sulphuric acid,tonnes,Transfers for Recycling,Other,328.5,https://www.canada.ca/en/environment-climate-c...,POINT (-79.57999 43.60378)

In [31]:
npri_gdf['emission_subtype'] = npri_gdf['emission_subtype'].replace({
    'Receiving Waterbody (French)': 'Waterbody',
    'Receiving Waterbody (English)': 'Waterbody'})

In [32]:
# Differentiate between biosphere and technosphere compartments
biosphere = ["Air", "Water", 'Land']
technosphere = ['On-Site Disposal', 'Off-Site Disposal', 'Transfers for Treatment', 'Transfers for Recycling']
                            
pollutant_npri_gdf = npri_gdf[npri_gdf['emission_type'].isin(biosphere)].copy()
waste_npri_gdf = npri_gdf[npri_gdf['emission_type'].isin(technosphere)].copy()

In [33]:
pollutant_npri_gdf.rename(columns={
    'emission_type': 'compartment_name',
    'emission_subtype': 'release_pathway'
}, inplace=True)

In [34]:
waste_npri_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,cas_number,substance_name_npri,substance_unit,emission_type,emission_subtype,value,source_id,geometry
4058,npri-2000-2023-156,2023,2000,Usine de Bouletage de Port-Cartier,ArcelorMittal Exploitation Minière Canada s.e....,mining,-66.791000,50.033400,Boreal Shield,St. Lawrence Drainage Area,NA - 04,Chromium (and its compounds),tonnes,On-Site Disposal,Land Fill,21.075,https://www.canada.ca/en/environment-climate-c...,POINT (-66.79100 50.03340)
4059,npri-5448-2023-181,2023,5448,Mine Raglan,Glencore,mining,-73.666600,61.691600,Northern Arctic,Northern Québec and Labrador Drainage Area,NA - 06,Copper (and its compounds),tonnes,On-Site Disposal,Land Fill,27.466,https://www.canada.ca/en/environment-climate-c...,POINT (-73.66660 61.69160)
4060,npri-34791-2023-58,2023,34791,Sullivan Mine,Teck Metals Limited,mining,-115.962100,49.667480,Montane Cordillera,Pacific Drainage Area,NA - 09,Manganese (and its compounds),tonnes,On-Site Disposal,Land Treatment,18.8,https://www.canada.ca/en/environment-climate-c...,POINT (-115.96210 49.66748)
4061,npri-34791-2023-59,2023,34791,Sullivan Mine,Teck Metals Limited,mining,-115.962100,49.667480,Montane Cordillera,Pacific Drainage Area,NA - 14,Zinc (and its compounds),tonnes,On-Site Disposal,Land Treatment,43.8,https://www.canada.ca/en/environment-climate-c...,POINT (-115.96210 49.66748)
4062,npri-1568-2023-171,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.087340,48.130320,Boreal Shield,St. Lawrence Drainage Area,NA - 16,Ammonia (total),tonnes,On-Site Disposal,Tailings,13.733,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8522,npri-3824-2023-206,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 11,Nickel (and its compounds),tonnes,Transfers for Recycling,Other,0.3233,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780)
8523,npri-3824-2023-207,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 22,Phosphorus (total),tonnes,Transfers for Recycling,Other,1.7886,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780)
8524,npri-3824-2023-208,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 14,Zinc (and its compounds),tonnes,Transfers for Recycling,Other,4.6224,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780)
8525,npri-3812-2023-34,2023,3812,Sivaco Québec,None,manufacturing,-73.167875,45.429756,Mixedwood Plain,St. Lawrence Drainage Area,7647-01-0,Hydrochloric acid,tonnes,Transfers for Recycling,Other,23.27,https://www.canada.ca/en/environment-climate-c...,POINT (-73.16787 45.42976)
8526,npri-2256-2023-54,2023,2256,Tonolli Canada,None,manufacturing,-79.579990,43.603780,Mixedwood Plain,St. Lawrence Drainage Area,7664-93-9,Sulphuric acid,tonnes,Transfers for Recycling,Other,328.5,https://www.canada.ca/en/environment-climate-c...,POINT (-79.57999 43.60378)

In [35]:
waste_npri_gdf.rename(
    columns={
        'emission_type': 'flow_direction',
        'emission_subtype': 'release_pathway'
    }, inplace=True
)

In [36]:
# Get unique substance name and cas number in a new df
npri_compartment_df = pollutant_npri_gdf[['compartment_name']].drop_duplicates().copy().reset_index(drop=True)

In [37]:
env_compartment_df = env_df[['compartment_name']].drop_duplicates().copy().reset_index(drop=True)

In [38]:
compartment_table = pd.concat([npri_compartment_df, env_compartment_df], ignore_index=True).drop_duplicates().reset_index(drop=True)

In [39]:
compartment_table

  compartment_name
0              Air
1            Water
2             Land

In [40]:
import hashlib
import pandas as pd

def assign_deterministic_id(df, prefix, columns, id_column):
    """
    Assign deterministic IDs based on one or more string columns.

    Parameters:
        df (pd.DataFrame): The DataFrame to modify.
        prefix (str): Prefix for the ID (e.g., 'CMP').
        columns (list): List of column names to combine and hash.
        id_column (str): Name of the new ID column.

    Returns:
        pd.DataFrame: Updated DataFrame with the new ID column.
    """
    def generate_id(row):
        key = '|'.join(str(row[col]).strip().lower() for col in columns)
        return f"{prefix}{hashlib.md5(key.encode()).hexdigest()[:8]}"
    
    df[id_column] = df.apply(generate_id, axis=1)
    return df

In [41]:
compartment_table = assign_deterministic_id(
    compartment_table,
    prefix="comp",
    columns=["compartment_name"],
    id_column="compartment_id"
)

In [42]:
compartment_table

  compartment_name compartment_id
0              Air   comp3c458811
1            Water   comp9460370b
2             Land   comp87cf962b

In [43]:
compartment_table.to_csv(r'database/CSV/compartments_table_new_new.csv', index=False)

### Assign compartment_id to the relevant datasets

In [44]:
pollutant_npri_gdf = pollutant_npri_gdf.merge(
    compartment_table[['compartment_id', 'compartment_name']],
    how='left',
    on=['compartment_name']
)

In [45]:
env_df = env_df.merge(
    compartment_table[['compartment_id', 'compartment_name']],
    how='left',
    on=['compartment_name']
)

In [46]:
# For CTrace and GHG datasets, we assign the compartment_id corresponding to 'Air' and 'Unspecified' pathway
# For land occupation datasets, we will assign the compartment_id corresponding to 'Land' and 'Unspecified' pathway
ctrace_gdf['compartment_id'] = 'comp3c458811'
ghg_gdf['compartment_id'] = 'comp3c458811'
li_canada_gdf['compartment_id']= 'comp87cf962b'
tang_canada_gdf['compartment_id'] = 'comp87cf962b'

# Matching

## Point to point matching

In [ ]:
from matching_functions import match_facilities, one_to_many_relationships

### MinCan

In [ ]:
# Let's keep only Active mines
min_can_gdf = min_can_gdf[min_can_gdf['mine_status'] == 'Active'].copy()

Some mines in MinCan dataset have very slightly different name (e.g. LaRonde - Zone 5 and LaRonde), the same name but one without town (e.g. Detour Lake) or several companies for the same mines.

In [ ]:
# min_can_id = ON-MINCAN-6316d452 = Detour Lake = 2013 - open
# min_can_id = ON-MINCAN-7b832414 = Detour Lake = 1983 - open
# min_can_id = QC-MINCAN-775312a1 = LaRonde - Zone 5 = 2018 - open
# min_can_id = QC-MINCAN-8321e85e = LaRonde = 1988 - open

In [ ]:
# We delete the duplicates, aligned with information from MDO for Detour Lake and LaRonde
min_can_gdf = min_can_gdf[~min_can_gdf['mincan_id'].isin(['ON-MINCAN-6316d452', 'QC-MINCAN-775312a1'])].copy()

In [ ]:
min_can_gdf

In [ ]:
lt_main_mincan = match_facilities(main_gdf, min_can_gdf,
                     id_col1='main_id', id_col2='mincan_id',
                     name_col1='facility_name', name_col2='namemine'
                     )

In [ ]:
lt_main_mincan.to_csv(r'data/Mappings/LT/lt_main_mincan.csv', index=False)

In [ ]:
matches_main_mincan = one_to_many_relationships(
    lt_main_mincan,
    id_main_col='main_id',
    id_sat_col='mincan_id',
    distance_threshold_m=2000,
    similarity_threshold=80,
    similarity_metric="token_set"  
)

In [ ]:
min_can_gdf = min_can_gdf.merge(
    matches_main_mincan,
    on="mincan_id", 
    how="left"
)

In [ ]:
# For SQL
min_can_gdf = min_can_gdf[min_can_gdf["main_id"].notna()].copy()

In [ ]:
col_to_keep = ["mincan_id", "main_id", "mine_status", "operation_periods"]
min_can_gdf = min_can_gdf[col_to_keep]
min_can_gdf

### CTrace

In [ ]:
lt_main_ctrace = match_facilities(main_gdf, ctrace_gdf,
                     id_col1='main_id', id_col2='ctrace_id',
                     name_col1='facility_name', name_col2='source_name'
                     )

In [ ]:
lt_main_ctrace.to_csv(r'data/Mappings/LT/lt_main_ctrace.csv', index=False)

In [47]:
# matches_main_ctrace = one_to_many_relationships(
#     lt_main_ctrace,
#     id_main_col='main_id',
#     id_sat_col='ctrace_id',
#     distance_threshold_m=2000,
#     similarity_threshold=80,
#     similarity_metric="token_set"
# )
matches_main_ctrace = pd.read_excel(r'data/Mappings/mapping_ctrace.xlsx', sheet_name='mapping')

In [48]:
matches_main_ctrace

    ctrace_id           main_id
0     1754077  QC-MAIN-e51eda66
1     1754071  BC-MAIN-e34feb4d
2     1754084  BC-MAIN-ed23117f
3     1754082  NL-MAIN-c139de6d
4     1754067  QC-MAIN-30c1828c
5    25486533  ON-MAIN-f8313ebd
6     1754096  QC-MAIN-a97821c0
7     1754102  ON-MAIN-40ce0593
8     1754057  BC-MAIN-599152a0
9    25486534  ON-MAIN-a3c56a83
10    1754085  BC-MAIN-3f490561
11    1754081  ON-MAIN-7001a391
12    1754083  YT-MAIN-752fbcae
13    1754087  BC-MAIN-aa76f6f2
14    1754097  BC-MAIN-8eb8be0d
15   36395102  NL-MAIN-b64bae7a
16   36395102  NL-MAIN-18695c6d
17    1754061  BC-MAIN-6b4800fe
18    1754066  BC-MAIN-bf503b6b
19    1754086  BC-MAIN-23155c25
20    1754105  QC-MAIN-b2148882
21    1754055  ON-MAIN-6e9b2449
22    1754058  ON-MAIN-52224e1e
23    1754060  ON-MAIN-48fe2205
24    1754104  ON-MAIN-28f3f0fc
25    1754056  ON-MAIN-f080c409
26    1754103  MB-MAIN-e0a6250e
27    1754106  NL-MAIN-2d8801d6
28    1754075  MB-MAIN-be5b3dc8

In [49]:
ctrace_gdf = ctrace_gdf.merge(
    matches_main_ctrace,
    on="ctrace_id", 
    how="left"
)

In [50]:
# For SQL
ctrace_gdf = ctrace_gdf[ctrace_gdf["main_id"].notna()].copy()

In [51]:
col_to_keep = [
'ctrace_id', 
'year',
'emissions_quantity', 
'gas',
'activity', 'activity_units', 
'capacity', 'capacity_units', 
'source_id',  'substance_id', 'compartment_id',
'main_id'           
]
ctrace_gdf = ctrace_gdf[col_to_keep]
ctrace_gdf

,ctrace_id,year,emissions_quantity,gas,activity,activity_units,capacity,capacity_units,source_id,substance_id,compartment_id,main_id
6,1754055,2023,5.610000e+03,co2e_100yr,8.630000e+05,t of copper ore,4.624000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449
7,1754056,2023,6.403000e+03,co2e_100yr,9.850000e+05,t of copper ore,3.554700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409
8,1754057,2023,2.299160e+05,co2e_100yr,1.457500e+07,t of copper ore,3.670000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0
9,1754058,2023,2.639000e+03,co2e_100yr,4.060000e+05,t of copper ore,1.104100e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e
11,1754060,2023,4.225000e+03,co2e_100yr,6.500000e+05,t of copper ore,4.822000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205
12,1754061,2023,1.316380e+05,co2e_100yr,8.810000e+07,t of copper ore,6.450000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-6b4800fe
16,1754066,2023,2.412130e+06,co2e_100yr,7.288600e+07,t of copper ore,2.631000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-30c1828c
21,1754071,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,1.073810e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-e34feb4d
23,1754075,2023,2.408400e+04,co2e_100yr,1.526729e+06,t of copper ore,1.357000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-be5b3dc8
25,1754077,2023,6.711600e+04,co2e_100yr,1.501481e+06,t of copper ore,1.988200e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-e51eda66
29,1754081,2023,7.782000e+03,co2e_100yr,5.279710e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,7.413000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,2.313000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,YT-MAIN-752fbcae
32,1754084,2023,7.956600e+04,co2e_100yr,2.127800e+07,t of copper ore,2.500250e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-ed23117f
33,1754085,2023,7.137900e+04,co2e_100yr,5.948239e+06,t of copper ore,4.902900e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-3f490561
34,1754086,2023,5.400000e+02,co2e_100yr,4.500000e+04,t of copper ore,4.110000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-23155c25
35,1754087,2023,1.590800e+04,co2e_100yr,2.993000e+06,t of copper ore,3.408700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-aa76f6f2
43,1754096,2023,8.219000e+03,co2e_100yr,6.848790e+05,t of copper ore,1.500000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-a97821c0
44,1754097,2023,8.451100e+04,co2e_100yr,6.887709e+06,t of copper ore,4.549000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-8eb8be0d
49,1754102,2023,1.593900e+04,co2e_100yr,1.431680e+06,t of copper ore,1.690000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-40ce0593
50,1754103,2023,4.433000e+03,co2e_100yr,6.820000e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-e0a6250e
51,1754104,2023,3.367000e+03,co2e_100yr,5.180000e+05,t of copper ore,2.453000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,co2e_100yr,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-b2148882
53,1754106,2023,1.144000e+04,co2e_100yr,1.760000e+06,t of copper ore,3.110000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-2d8801d6
54,25486533,2023,1.620000e+04,co2e_100yr,1.350000e+06,t of copper ore,2.500000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f8313ebd
55,25486534,2023,5.914500e+04,co2e_100yr,3.798000e+06,t of copper ore,2.200000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-a3c56a83
56,36395102,2023,5.760720e+05,co2e_100yr,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-b64bae7a
57,36395102,2023,5.760720e+05,co2e_100yr,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-18695c6d

In [52]:
# We separate emissions and production data
ctrace_ghg_gdf = ctrace_gdf.drop(columns=['activity', 'activity_units', 'capacity', 'capacity_units'])
ctrace_prod_gdf = ctrace_gdf.drop(columns=['emissions_quantity', 'gas'])

### Conflict

In [ ]:
lt_main_conflict = match_facilities(main_gdf, conflict_gdf,
                     id_col1='main_id', id_col2='ej_atlas_id',
                     name_col1='facility_name', name_col2='facility_name_ejatlas'
                     )

In [ ]:
matches_main_conflict = one_to_many_relationships(
    lt_main_conflict,
    id_main_col='main_id',
    id_sat_col='ej_atlas_id',
    distance_threshold_m=20000,
    similarity_threshold=80,
    similarity_metric="token_set"  # "partial" or "token_set"
)

In [ ]:
conflict_gdf = conflict_gdf.merge(
    matches_main_conflict,
    on="ej_atlas_id",  
    how="left"
)

In [ ]:
# For SQL
conflict_gdf = conflict_gdf[conflict_gdf["main_id"].notna()].copy()

In [ ]:
col_to_keep = ["ej_atlas_id",
  "main_id",
  "case_name",
  "start_date",
  "end_date",
  "conflict_description",
  "conflict_details",
  "population_affected",
  "conflict_intensity",
  "project_status",
  "source_id"             
               ]
conflict_gdf = conflict_gdf[col_to_keep]
conflict_gdf

### Tailings

In [ ]:
lt_main_tailings = match_facilities(main_gdf, tailings_gdf,
                     id_col1='main_id', id_col2='tailing_id',
                     name_col1='facility_name', name_col2='related_mine'
                     )

In [ ]:
lt_main_tailings.to_csv(r'data/Mappings/LT/lt_main_tailings.csv', index=False)

In [ ]:
# matches_main_tailings = one_to_many_relationships(
#     lt_main_tailings,
#     id_main_col='main_id',
#     id_sat_col='tailing_id',
#     distance_threshold_m=20000,
#     similarity_threshold=80,
#     similarity_metric="token_set"  # "partial" or "token_set"
# )
matches_main_tailings = pd.read_excel(r'data/Mappings/mapping_tailing.xlsx', sheet_name='mapping')

In [ ]:
tailings_gdf = tailings_gdf.merge(
    matches_main_tailings,
    on="tailing_id",  
    how="left"
)

In [ ]:
# For SQL
tailings_gdf = tailings_gdf[tailings_gdf["main_id"].notna()].copy()

In [ ]:
col_to_keep = [
  "row_id",
  "main_id",
  "year",
  "tailing_id",
  "tsf_name",
  "status",
  "construction_year",
  "raise_type",
  "current_maximum_height",
  "current_tailings_storage",
  "planned_storage_5_years",
  "hazard_categorization",
  "classification_system",
  "geometry", 
  "source_id"             
               ]
tailings_gdf = tailings_gdf[col_to_keep]
tailings_gdf

### GHG

In [ ]:
lt_main_ghg = match_facilities(main_gdf, ghg_gdf,
                     id_col1='main_id', id_col2='ghg_id',
                     name_col1='facility_name', name_col2='facility_name_ghg'
                     )

In [ ]:
lt_main_ghg.to_csv(r'data/Mappings/LT/lt_main_ghg.csv', index=False)

In [73]:
# matches_main_ghg = one_to_many_relationships(
#     lt_main_ghg,
#     id_main_col='main_id',
#     id_sat_col='ghg_id',
#     distance_threshold_m=10000,
#     similarity_threshold=80,
#     similarity_metric="token_set"  # "partial" or "token_set"
# )
matches_main_ghg = pd.read_excel(r'data/Mappings/mapping_ghg.xlsx', sheet_name='mapping')

In [74]:
ghg_gdf = ghg_gdf.merge(
    matches_main_ghg,
    on="ghg_id",  
    how="left"
)

In [75]:
# For SQL
ghg_gdf = ghg_gdf[ghg_gdf["main_id"].notna()].copy()

In [76]:
col_to_keep = [
  "row_id",
  "main_id",
  "year",
  "value",
  "unit",
  "compartment_id",
  "substance_id",
  "source_id"             
               ]
ghg_gdf = ghg_gdf[col_to_keep]
ghg_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
0,GHG-10052-2023-1,NL-MAIN-dd723db4,2023,780.52,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
1,GHG-10101-2023-1,NT-MAIN-6c1d6ee6,2023,170.09,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
3,GHG-10188-2023-1,QC-MAIN-084bd95c,2023,274.90,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
5,GHG-10240-2023-1,QC-MAIN-a97821c0,2023,158.00,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
6,GHG-10299-2023-1,QC-MAIN-e25eed27,2023,804.49,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
138,GHG-11730-2023-1,QC-MAIN-92628f16,2023,406.65,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
141,GHG-11765-2023-1,ON-MAIN-4c35e094,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
142,GHG-11765-2023-1,ON-MAIN-020a683c,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
144,GHG-11989-2023-1,QC-MAIN-1eee4ace,2023,952.95,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
146,GHG-12298-2023-1,ON-MAIN-63b394c3,2023,325.43,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...

### NPRI - pollutants

In [ ]:
lt_main_pollution = match_facilities(main_gdf, pollutant_npri_gdf,
                     id_col1='main_id', id_col2='npri_id',
                     name_col1='facility_name', name_col2='facility_name_npri'
                     )

In [ ]:
lt_main_pollution.to_csv(r'data/Mappings/LT/lt_main_pollution.csv', index=False)

In [ ]:
# matches_main_pollution = one_to_many_relationships(
#     lt_main_pollution,
#     id_main_col='main_id',
#     id_sat_col='npri_id',
#     distance_threshold_m=10000,
#     similarity_threshold=80,
#     similarity_metric="token_set"  # "partial" or "token_set"
# )
matches_main_pollution = pd.read_excel(r'data/Mappings/mapping_npri.xlsx', sheet_name='mapping')

In [ ]:
pollutant_npri_gdf = pollutant_npri_gdf.merge(
    matches_main_pollution,
    on="npri_id",  
    how="left"
)

In [ ]:
pollutant_npri_gdf

In [ ]:
pollutant_npri_gdf.rename(columns={'cas_number': 'substance_id'}, inplace=True)

In [ ]:
# For SQL
pollutant_npri_gdf = pollutant_npri_gdf[pollutant_npri_gdf["main_id"].notna()].copy()

In [ ]:
pollutant_npri_gdf

In [ ]:
col_to_keep = [
  "row_id",
  #"npri_id",
  "main_id",
  "year",
  "value",
  "substance_unit",
  "compartment_id",
  "substance_id",
  "release_pathway",  
  "source_id"
 ]
pollutant_npri_gdf = pollutant_npri_gdf[col_to_keep]
pollutant_npri_gdf.rename(columns={'substance_unit': 'unit'}, inplace=True)
pollutant_npri_gdf

### NPRI - waste

In [77]:
matches_main_waste = pd.read_excel(r'data/Mappings/mapping_npri.xlsx', sheet_name='mapping')

In [78]:
waste_npri_gdf = waste_npri_gdf.merge(
    matches_main_waste,
    on="npri_id",
    how="left"
)

In [79]:
waste_npri_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,cas_number,substance_name_npri,substance_unit,flow_direction,release_pathway,value,source_id,geometry,main_id
0,npri-2000-2023-156,2023,2000,Usine de Bouletage de Port-Cartier,ArcelorMittal Exploitation Minière Canada s.e....,mining,-66.791000,50.033400,Boreal Shield,St. Lawrence Drainage Area,NA - 04,Chromium (and its compounds),tonnes,On-Site Disposal,Land Fill,21.075,https://www.canada.ca/en/environment-climate-c...,POINT (-66.79100 50.03340),QC-MAIN-e25eed27
1,npri-5448-2023-181,2023,5448,Mine Raglan,Glencore,mining,-73.666600,61.691600,Northern Arctic,Northern Québec and Labrador Drainage Area,NA - 06,Copper (and its compounds),tonnes,On-Site Disposal,Land Fill,27.466,https://www.canada.ca/en/environment-climate-c...,POINT (-73.66660 61.69160),QC-MAIN-a97821c0
2,npri-34791-2023-58,2023,34791,Sullivan Mine,Teck Metals Limited,mining,-115.962100,49.667480,Montane Cordillera,Pacific Drainage Area,NA - 09,Manganese (and its compounds),tonnes,On-Site Disposal,Land Treatment,18.8,https://www.canada.ca/en/environment-climate-c...,POINT (-115.96210 49.66748),NaN
3,npri-34791-2023-59,2023,34791,Sullivan Mine,Teck Metals Limited,mining,-115.962100,49.667480,Montane Cordillera,Pacific Drainage Area,NA - 14,Zinc (and its compounds),tonnes,On-Site Disposal,Land Treatment,43.8,https://www.canada.ca/en/environment-climate-c...,POINT (-115.96210 49.66748),NaN
4,npri-1568-2023-171,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.087340,48.130320,Boreal Shield,St. Lawrence Drainage Area,NA - 16,Ammonia (total),tonnes,On-Site Disposal,Tailings,13.733,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),ON-MAIN-1f126a43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1945,npri-3824-2023-206,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 11,Nickel (and its compounds),tonnes,Transfers for Recycling,Other,0.3233,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35
1946,npri-3824-2023-207,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 22,Phosphorus (total),tonnes,Transfers for Recycling,Other,1.7886,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35
1947,npri-3824-2023-208,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.909700,43.857800,Mixedwood Plain,St. Lawrence Drainage Area,NA - 14,Zinc (and its compounds),tonnes,Transfers for Recycling,Other,4.6224,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35
1948,npri-3812-2023-34,2023,3812,Sivaco Québec,None,manufacturing,-73.167875,45.429756,Mixedwood Plain,St. Lawrence Drainage Area,7647-01-0,Hydrochloric acid,tonnes,Transfers for Recycling,Other,23.27,https://www.canada.ca/en/environment-climate-c...,POINT (-73.16787 45.42976),NaN
1949,npri-2256-2023-54,2023,2256,Tonolli Canada,None,manufacturing,-79.579990,43.603780,Mixedwood Plain,St. Lawrence Drainage Area,7664-93-9,Sulphuric acid,tonnes,Transfers for Recycling,Other,328.5,https://www.canada.ca/en/environment-climate-c...,POINT (-79.57999 43.60378),NaN

In [80]:
waste_npri_gdf.rename(columns={'cas_number': 'substance_id'}, inplace=True)

In [81]:
# For SQL
waste_npri_gdf = waste_npri_gdf[waste_npri_gdf["main_id"].notna()].copy()

In [82]:
waste_npri_gdf

,row_id,year,npri_id,facility_name_npri,company_name_npri,facility_type,longitude,latitude,terrestrial_ecozone,watershed,substance_id,substance_name_npri,substance_unit,flow_direction,release_pathway,value,source_id,geometry,main_id
0,npri-2000-2023-156,2023,2000,Usine de Bouletage de Port-Cartier,ArcelorMittal Exploitation Minière Canada s.e....,mining,-66.79100,50.03340,Boreal Shield,St. Lawrence Drainage Area,NA - 04,Chromium (and its compounds),tonnes,On-Site Disposal,Land Fill,21.075,https://www.canada.ca/en/environment-climate-c...,POINT (-66.79100 50.03340),QC-MAIN-e25eed27
1,npri-5448-2023-181,2023,5448,Mine Raglan,Glencore,mining,-73.66660,61.69160,Northern Arctic,Northern Québec and Labrador Drainage Area,NA - 06,Copper (and its compounds),tonnes,On-Site Disposal,Land Fill,27.466,https://www.canada.ca/en/environment-climate-c...,POINT (-73.66660 61.69160),QC-MAIN-a97821c0
4,npri-1568-2023-171,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 16,Ammonia (total),tonnes,On-Site Disposal,Tailings,13.733,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),ON-MAIN-1f126a43
5,npri-1568-2023-172,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 02,Arsenic (and its compounds),kg,On-Site Disposal,Tailings,3166.0,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),ON-MAIN-1f126a43
6,npri-1568-2023-173,2023,1568,Macassa Mine,Agnico Eagle Mines,mining,-80.08734,48.13032,Boreal Shield,St. Lawrence Drainage Area,NA - 03,Cadmium (and its compounds),kg,On-Site Disposal,Tailings,34.0,https://www.canada.ca/en/environment-climate-c...,POINT (-80.08734 48.13032),ON-MAIN-1f126a43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1943,npri-3824-2023-204,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.90970,43.85780,Mixedwood Plain,St. Lawrence Drainage Area,NA - 09,Manganese (and its compounds),tonnes,Transfers for Recycling,Other,60.3109,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35
1944,npri-3824-2023-205,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.90970,43.85780,Mixedwood Plain,St. Lawrence Drainage Area,NA - 10,Mercury (and its compounds),kg,Transfers for Recycling,Other,0.0885,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35
1945,npri-3824-2023-206,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.90970,43.85780,Mixedwood Plain,St. Lawrence Drainage Area,NA - 11,Nickel (and its compounds),tonnes,Transfers for Recycling,Other,0.3233,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35
1946,npri-3824-2023-207,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.90970,43.85780,Mixedwood Plain,St. Lawrence Drainage Area,NA - 22,Phosphorus (total),tonnes,Transfers for Recycling,Other,1.7886,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35
1947,npri-3824-2023-208,2023,3824,"Gerdau Ameristeel Corporation, Whitby Mill",None,manufacturing,-78.90970,43.85780,Mixedwood Plain,St. Lawrence Drainage Area,NA - 14,Zinc (and its compounds),tonnes,Transfers for Recycling,Other,4.6224,https://www.canada.ca/en/environment-climate-c...,POINT (-78.90970 43.85780),ON-MAIN-21b6ab35

In [85]:
col_to_keep = [
  "row_id",
  #"npri_id",
  "main_id",
  "year",
  "value",
  "substance_unit",
  #"compartment_id",
  "substance_id",
  "flow_direction",
  "release_pathway",
  "source_id"
 ]
waste_npri_gdf = waste_npri_gdf[col_to_keep]
waste_npri_gdf.rename(columns={'substance_unit': 'unit'}, inplace=True)
waste_npri_gdf

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_6080\3382832434.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  waste_npri_gdf.rename(columns={'substance_unit': 'unit'}, inplace=True)

,row_id,main_id,year,value,unit,substance_id,flow_direction,release_pathway,source_id
0,npri-2000-2023-156,QC-MAIN-e25eed27,2023,21.075,tonnes,NA - 04,On-Site Disposal,Land Fill,https://www.canada.ca/en/environment-climate-c...
1,npri-5448-2023-181,QC-MAIN-a97821c0,2023,27.466,tonnes,NA - 06,On-Site Disposal,Land Fill,https://www.canada.ca/en/environment-climate-c...
4,npri-1568-2023-171,ON-MAIN-1f126a43,2023,13.733,tonnes,NA - 16,On-Site Disposal,Tailings,https://www.canada.ca/en/environment-climate-c...
5,npri-1568-2023-172,ON-MAIN-1f126a43,2023,3166.0,kg,NA - 02,On-Site Disposal,Tailings,https://www.canada.ca/en/environment-climate-c...
6,npri-1568-2023-173,ON-MAIN-1f126a43,2023,34.0,kg,NA - 03,On-Site Disposal,Tailings,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...,...
1943,npri-3824-2023-204,ON-MAIN-21b6ab35,2023,60.3109,tonnes,NA - 09,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1944,npri-3824-2023-205,ON-MAIN-21b6ab35,2023,0.0885,kg,NA - 10,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1945,npri-3824-2023-206,ON-MAIN-21b6ab35,2023,0.3233,tonnes,NA - 11,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1946,npri-3824-2023-207,ON-MAIN-21b6ab35,2023,1.7886,tonnes,NA - 22,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1947,npri-3824-2023-208,ON-MAIN-21b6ab35,2023,4.6224,tonnes,NA - 14,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...

### Li et al land occupation

In [ ]:
# li_canada_gdf_copy = li_canada_gdf.copy()
# li_canada_gdf_copy.rename(columns={'geometry': 'geometry_polygon'}, inplace=True)
# li_canada_gdf_copy["geometry"] = gpd.points_from_xy(li_canada_gdf_copy["Longitude"], li_canada_gdf_copy["Latitude"])
# li_canada_gdf_copy = li_canada_gdf_copy.set_geometry("geometry", crs="EPSG:4326")

In [ ]:
# lt_main_li = match_facilities(main_gdf, li_canada_gdf_copy,
#                      id_col1='main_id', id_col2='li_id',
#                      name_col1='facility_name', name_col2='Name'
#                      )
# lt_main_li.to_excel(r'data/Sources/lt_main_li.xlsx', index=False)

In [ ]:
matches_main_li = pd.read_excel(r'data/Sources/lt_main_li.xlsx', sheet_name='for_pandas')

In [ ]:
li_canada_gdf = li_canada_gdf.merge(
    matches_main_li,
    on="li_id",  
    how="left"
)

In [ ]:
li_canada_gdf

In [ ]:
# For SQL
li_canada_gdf = li_canada_gdf[li_canada_gdf["main_id"].notna()].copy()

In [ ]:
li_canada_gdf

## Point to polygon matching

### Protected lands datasets

In [ ]:
from matching_functions import associate_facilities_near_polygons

In [ ]:
wpda_gdf_polygons

In [ ]:
lt_wpda = associate_facilities_near_polygons(
    main_gdf,
    wpda_gdf_polygons,
    facility_id_col="main_id",
    polygon_id_col="WDPA_PID",
    buffer_km=50,
    crs="EPSG:3978"
)

In [ ]:
wpda_gdf_polygons = wpda_gdf_polygons.merge(lt_wpda, on="WDPA_PID", how="left")

In [ ]:
# For SQL
wpda_gdf_polygons = wpda_gdf_polygons[wpda_gdf_polygons["main_id"].notna()].copy()

In [ ]:
lt_indigenous = associate_facilities_near_polygons(
    main_gdf,
    indigenous_can_gdf,
    facility_id_col="main_id",
    polygon_id_col="indigenous_land_id",
    buffer_km=50,
    crs="EPSG:3978"
)

In [ ]:
indigenous_can_gdf = indigenous_can_gdf.merge(lt_indigenous, on="indigenous_land_id", how="left")

In [ ]:
# For SQL
indigenous_can_gdf = indigenous_can_gdf[indigenous_can_gdf["main_id"].notna()].copy()

### Land occupation footprint datasets

In [ ]:
from matching_functions import assign_polygons_to_points

In [ ]:
main_gdf

In [ ]:
assigned_df = assign_polygons_to_points(
    main_gdf,
    tailings_gdf,
    tang_canada_gdf,
    max_dist_km=10
)

In [ ]:
assigned_df

In [ ]:
assigned_df['relation_type'].value_counts()

In [ ]:
polygon_gdf = tang_canada_gdf.merge(assigned_df, on="tang_id", how="left")

In [ ]:
polygon_gdf

In [ ]:
from visualization_functions import plot_polygons_assginment

In [ ]:
plot_polygons_assginment(
    main_gdf,
    tailings_gdf,
    polygon_gdf, 
    output_html="results/data_coverage/facilities_tailings_maps.html"
)

# Create final tables

## Main table

In [ ]:
main_gdf

In [ ]:
ownership_df = pd.read_excel(r'data/Tables/extracted_data.xlsx', sheet_name='Ownership')

In [ ]:
# Integrate ownership information into the main_gdf 
main_gdf = main_gdf.merge(
    ownership_df[['main_id', 'owner(s)', 'operator(s)', 'company_URL', 'company_facility_URL', 'MDO_URL']],
    on='main_id',
    how='left'
)

In [ ]:
# # Integrate the operation_periods from min_can_gdf into the main_gdf
main_gdf = main_gdf.merge(
     min_can_gdf[['main_id', 'operation_periods']],
     on='main_id',
     how='left'
 )
# 
# # Add the source_id for MinCan only where operation_periods are not null
main_gdf['source_id'] = main_gdf.apply(
     lambda row: row['source_id'] + ';' + 'https://doi.org/10.1038/s41597-024-03116-3' if pd.notna(row['operation_periods']) else row['source_id'],
     axis=1
 )

In [ ]:
main_gdf

In [ ]:
main_gdf.rename(columns={
    'company_name_folder': 'company_name',
    'company_facility_URL': 'facility_URL'
}, inplace=True)

In [ ]:
column_order = [
       'main_id', 'facility_name', 'facility_group_id', 'facility_group_name', 'company_id', 'company_name',
       'city', 'province', 'geometry',
       'status', 'activity_status', 'development_stage', 'facility_type', 'mining_processing_type',
       'commodity_group', 'commodities',
       'owner(s)', 'operator(s)', 'operation_periods', 
       'company_URL', 'facility_URL', 'MDO_URL', 
       'source_id'
]

In [ ]:
# Fix column orders
main_gdf = main_gdf[column_order].copy()

In [ ]:
main_gdf

## Environment table

### CTrace dataset

In [86]:
ctrace_ghg_gdf.rename(columns={
    'ctrace_id': 'env_id',
    'emissions_quantity': 'value',
    'gas': 'unit'}, inplace=True)

In [87]:
ctrace_ghg_gdf['unit'] = ctrace_ghg_gdf['unit'].replace({'co2e_100yr': 'tCO2eq'})

In [88]:
ctrace_ghg_gdf

,env_id,year,value,unit,source_id,substance_id,compartment_id,main_id
6,1754055,2023,5.610000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449
7,1754056,2023,6.403000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409
8,1754057,2023,2.299160e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0
9,1754058,2023,2.639000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e
11,1754060,2023,4.225000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205
12,1754061,2023,1.316380e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-6b4800fe
16,1754066,2023,2.412130e+06,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-30c1828c
21,1754071,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-e34feb4d
23,1754075,2023,2.408400e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-be5b3dc8
25,1754077,2023,6.711600e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-e51eda66
29,1754081,2023,7.782000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,YT-MAIN-752fbcae
32,1754084,2023,7.956600e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-ed23117f
33,1754085,2023,7.137900e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-3f490561
34,1754086,2023,5.400000e+02,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-23155c25
35,1754087,2023,1.590800e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-aa76f6f2
43,1754096,2023,8.219000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-a97821c0
44,1754097,2023,8.451100e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-8eb8be0d
49,1754102,2023,1.593900e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-40ce0593
50,1754103,2023,4.433000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-e0a6250e
51,1754104,2023,3.367000e+03,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-b2148882
53,1754106,2023,1.144000e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-2d8801d6
54,25486533,2023,1.620000e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f8313ebd
55,25486534,2023,5.914500e+04,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-a3c56a83
56,36395102,2023,5.760720e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-b64bae7a
57,36395102,2023,5.760720e+05,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-18695c6d

In [89]:
ctrace_gdf['flow_direction'] = 'Emission'
ctrace_gdf['release_pathway'] = 'Unspecified'

### NPRI datasets

In [90]:
pollutant_npri_gdf.rename(columns={
    'row_id': 'env_id'}, inplace=True)

In [91]:
pollutant_npri_gdf['flow_direction'] = 'Emission'

In [92]:
waste_npri_gdf.rename(columns={
    'row_id': 'env_id'}, inplace=True)

,row_id,main_id,year,value,unit,substance_id,flow_direction,release_pathway,source_id
0,npri-2000-2023-156,QC-MAIN-e25eed27,2023,21.075,tonnes,NA - 04,On-Site Disposal,Land Fill,https://www.canada.ca/en/environment-climate-c...
1,npri-5448-2023-181,QC-MAIN-a97821c0,2023,27.466,tonnes,NA - 06,On-Site Disposal,Land Fill,https://www.canada.ca/en/environment-climate-c...
4,npri-1568-2023-171,ON-MAIN-1f126a43,2023,13.733,tonnes,NA - 16,On-Site Disposal,Tailings,https://www.canada.ca/en/environment-climate-c...
5,npri-1568-2023-172,ON-MAIN-1f126a43,2023,3166.0,kg,NA - 02,On-Site Disposal,Tailings,https://www.canada.ca/en/environment-climate-c...
6,npri-1568-2023-173,ON-MAIN-1f126a43,2023,34.0,kg,NA - 03,On-Site Disposal,Tailings,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...,...
1943,npri-3824-2023-204,ON-MAIN-21b6ab35,2023,60.3109,tonnes,NA - 09,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1944,npri-3824-2023-205,ON-MAIN-21b6ab35,2023,0.0885,kg,NA - 10,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1945,npri-3824-2023-206,ON-MAIN-21b6ab35,2023,0.3233,tonnes,NA - 11,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1946,npri-3824-2023-207,ON-MAIN-21b6ab35,2023,1.7886,tonnes,NA - 22,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...
1947,npri-3824-2023-208,ON-MAIN-21b6ab35,2023,4.6224,tonnes,NA - 14,Transfers for Recycling,Other,https://www.canada.ca/en/environment-climate-c...

In [94]:
waste_npri_gdf['compartment_id'] = ''

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_6080\3969074842.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  waste_npri_gdf['compartment_id'] = ''

### GHG dataset

In [95]:
ghg_gdf

,row_id,main_id,year,value,unit,compartment_id,substance_id,source_id
0,GHG-10052-2023-1,NL-MAIN-dd723db4,2023,780.52,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
1,GHG-10101-2023-1,NT-MAIN-6c1d6ee6,2023,170.09,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
3,GHG-10188-2023-1,QC-MAIN-084bd95c,2023,274.90,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
5,GHG-10240-2023-1,QC-MAIN-a97821c0,2023,158.00,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
6,GHG-10299-2023-1,QC-MAIN-e25eed27,2023,804.49,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
...,...,...,...,...,...,...,...,...
138,GHG-11730-2023-1,QC-MAIN-92628f16,2023,406.65,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
141,GHG-11765-2023-1,ON-MAIN-4c35e094,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
142,GHG-11765-2023-1,ON-MAIN-020a683c,2023,15.60,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
144,GHG-11989-2023-1,QC-MAIN-1eee4ace,2023,952.95,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...
146,GHG-12298-2023-1,ON-MAIN-63b394c3,2023,325.43,kilotonnes of carbon dioxide equivalents (kt C...,comp3c458811,NA - GHG,https://www.canada.ca/en/environment-climate-c...

In [96]:
ghg_gdf.rename(columns={'row_id': 'env_id'}, inplace=True)

In [97]:
ghg_gdf['unit'] = ghg_gdf['unit'].replace({'kilotonnes of carbon dioxide equivalents (kt CO2 eq)': 'ktCO2eq'})

In [98]:
ghg_gdf['flow_direction'] = 'Emission'
ghg_gdf['release_pathway'] = 'Unspecified'

### Manually collected data

In [99]:
env_df

,row_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,substance_type,substance_name,cas_number,subflow_type,unit,value,comment,source,source_id,compartment_id
0,ENV-fefeaee4-2023-1,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope1,tCO2eq,30881.462464,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
1,ENV-fefeaee4-2023-2,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope2,tCO2eq,1153.824991,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
2,ENV-fefeaee4-2023-3,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope3,tCO2eq,77581.033383,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
3,ENV-fefeaee4-2023-4,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope1,tCO2eq,3942.000000,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
4,ENV-fefeaee4-2023-5,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope2,tCO2eq,304.200000,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-687b8c8d-2023-15,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,Particulate Matter <= 10 Micrometers,NA - M09,-,t,8.600000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
320,ENV-687b8c8d-2023-16,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,PM2.5 - Particulate Matter <= 2.5 Micrometers,NA - M10,-,t,2.600000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
321,ENV-687b8c8d-2023-17,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,Polycyclic aromatic hydrocarbons (PAH),NA - PAH,-,t,38.542240,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
322,ENV-687b8c8d-2023-18,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,SOx,NA - SOx,-,t,0.243000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
323,ENV-687b8c8d-2023-19,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,VOCs,NA - M16,-,t,31.552000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811

In [100]:
env_df

,row_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,substance_type,substance_name,cas_number,subflow_type,unit,value,comment,source,source_id,compartment_id
0,ENV-fefeaee4-2023-1,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope1,tCO2eq,30881.462464,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
1,ENV-fefeaee4-2023-2,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope2,tCO2eq,1153.824991,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
2,ENV-fefeaee4-2023-3,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope3,tCO2eq,77581.033383,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
3,ENV-fefeaee4-2023-4,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope1,tCO2eq,3942.000000,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
4,ENV-fefeaee4-2023-5,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope2,tCO2eq,304.200000,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-687b8c8d-2023-15,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,Particulate Matter <= 10 Micrometers,NA - M09,-,t,8.600000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
320,ENV-687b8c8d-2023-16,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,PM2.5 - Particulate Matter <= 2.5 Micrometers,NA - M10,-,t,2.600000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
321,ENV-687b8c8d-2023-17,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,Polycyclic aromatic hydrocarbons (PAH),NA - PAH,-,t,38.542240,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
322,ENV-687b8c8d-2023-18,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,SOx,NA - SOx,-,t,0.243000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
323,ENV-687b8c8d-2023-19,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,VOCs,NA - M16,-,t,31.552000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811

In [101]:
env_df.rename(columns={'row_id': 'env_id', 'cas_number': 'substance_id'}, inplace=True)

In [102]:
env_df

,env_id,year,reporting_level,reported_company_nrcan,name,main_id,facility_group_id,company_id,facility_type,mining_processing_type,...,substance_type,substance_name,substance_id,subflow_type,unit,value,comment,source,source_id,compartment_id
0,ENV-fefeaee4-2023-1,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope1,tCO2eq,30881.462464,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
1,ENV-fefeaee4-2023-2,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope2,tCO2eq,1153.824991,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
2,ENV-fefeaee4-2023-3,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope3,tCO2eq,77581.033383,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
3,ENV-fefeaee4-2023-4,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope1,tCO2eq,3942.000000,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
4,ENV-fefeaee4-2023-5,2023,Site-specific,Newmont Corporation,Brucejack,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,mining,"Underground, concentrator",...,Group of substances,GHG,NA - GHG,scope2,tCO2eq,304.200000,NaN,Newmont-2023-Performance-Data-Tables-V4-locked...,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-687b8c8d-2023-15,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,Particulate Matter <= 10 Micrometers,NA - M09,-,t,8.600000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
320,ENV-687b8c8d-2023-16,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,PM2.5 - Particulate Matter <= 2.5 Micrometers,NA - M10,-,t,2.600000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
321,ENV-687b8c8d-2023-17,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,Polycyclic aromatic hydrocarbons (PAH),NA - PAH,-,t,38.542240,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
322,ENV-687b8c8d-2023-18,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,SOx,NA - SOx,-,t,0.243000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811
323,ENV-687b8c8d-2023-19,2023,Site-specific,Alamos Gold Inc,Young-Davidson,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,mining,"Underground, concentrator",...,Group of substances,VOCs,NA - M16,-,t,31.552000,NaN,Data_2023.xlsx,SRC_AlamosGoldInc_Data_2023,comp3c458811

In [103]:
env_df.drop(columns=['reporting_level', 'reported_company_nrcan', 'name', 'facility_type', 'mining_processing_type', 'commodity','compartment_name', 'substance_type', 'substance_name', 'subflow_type', 'source'], inplace=True)

In [104]:
env_df

,env_id,year,main_id,facility_group_id,company_id,flow_direction,substance_id,unit,value,comment,source_id,compartment_id
0,ENV-fefeaee4-2023-1,2023,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,Emission,NA - GHG,tCO2eq,30881.462464,NaN,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
1,ENV-fefeaee4-2023-2,2023,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,Emission,NA - GHG,tCO2eq,1153.824991,NaN,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
2,ENV-fefeaee4-2023-3,2023,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,Emission,NA - GHG,tCO2eq,77581.033383,NaN,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
3,ENV-fefeaee4-2023-4,2023,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,Emission,NA - GHG,tCO2eq,3942.000000,NaN,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
4,ENV-fefeaee4-2023-5,2023,ON-MAIN-fefeaee4,NaN,CMP-4a434d72,Emission,NA - GHG,tCO2eq,304.200000,NaN,SRC_NewmontCorporation_Newmont-2023-Performanc...,comp3c458811
...,...,...,...,...,...,...,...,...,...,...,...,...
319,ENV-687b8c8d-2023-15,2023,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Emission,NA - M09,t,8.600000,NaN,SRC_AlamosGoldInc_Data_2023,comp3c458811
320,ENV-687b8c8d-2023-16,2023,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Emission,NA - M10,t,2.600000,NaN,SRC_AlamosGoldInc_Data_2023,comp3c458811
321,ENV-687b8c8d-2023-17,2023,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Emission,NA - PAH,t,38.542240,NaN,SRC_AlamosGoldInc_Data_2023,comp3c458811
322,ENV-687b8c8d-2023-18,2023,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Emission,NA - SOx,t,0.243000,NaN,SRC_AlamosGoldInc_Data_2023,comp3c458811
323,ENV-687b8c8d-2023-19,2023,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,Emission,NA - M16,t,31.552000,NaN,SRC_AlamosGoldInc_Data_2023,comp3c458811

### Concatenate all environment data into a single table

In [105]:
env_table = pd.concat(
    [ctrace_ghg_gdf, pollutant_npri_gdf, ghg_gdf, env_df],
    ignore_index=True
)

In [106]:
env_table

,env_id,year,value,unit,source_id,substance_id,compartment_id,main_id,npri_id,facility_name_npri,...,cas_number,substance_name_npri,substance_unit,compartment_name,release_pathway,geometry,flow_direction,facility_group_id,company_id,comment
0,1754055,2023,5610.000024,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
1,1754056,2023,6403.000027,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
2,1754057,2023,229916.000984,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
3,1754058,2023,2639.000011,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
4,1754060,2023,4225.000018,tCO2eq,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7010,ENV-687b8c8d-2023-15,2023,8.6,t,SRC_AlamosGoldInc_Data_2023,NA - M09,comp3c458811,ON-MAIN-687b8c8d,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,Emission,NaN,CMP-3a4ccc7f,NaN
7011,ENV-687b8c8d-2023-16,2023,2.6,t,SRC_AlamosGoldInc_Data_2023,NA - M10,comp3c458811,ON-MAIN-687b8c8d,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,Emission,NaN,CMP-3a4ccc7f,NaN
7012,ENV-687b8c8d-2023-17,2023,38.54224,t,SRC_AlamosGoldInc_Data_2023,NA - PAH,comp3c458811,ON-MAIN-687b8c8d,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,Emission,NaN,CMP-3a4ccc7f,NaN
7013,ENV-687b8c8d-2023-18,2023,0.243,t,SRC_AlamosGoldInc_Data_2023,NA - SOx,comp3c458811,ON-MAIN-687b8c8d,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,Emission,NaN,CMP-3a4ccc7f,NaN
7014,ENV-687b8c8d-2023-19,2023,31.552,t,SRC_AlamosGoldInc_Data_2023,NA - M16,comp3c458811,ON-MAIN-687b8c8d,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,Emission,NaN,CMP-3a4ccc7f,NaN

In [107]:
env_table.columns

Index(['env_id', 'year', 'value', 'unit', 'source_id', 'substance_id',
       'compartment_id', 'main_id', 'npri_id', 'facility_name_npri',
       'company_name_npri', 'facility_type', 'longitude', 'latitude',
       'terrestrial_ecozone', 'watershed', 'cas_number', 'substance_name_npri',
       'substance_unit', 'compartment_name', 'release_pathway', 'geometry',
       'flow_direction', 'facility_group_id', 'company_id', 'comment'],
      dtype='object')

In [108]:
column_order = ['env_id', 'year', 'compartment_id', 'substance_id', 'flow_direction', 'release_pathway', 'unit', 'value', 'comment', 'main_id','facility_group_id', 'company_id', 'source_id']

In [109]:
env_table = env_table[column_order]

In [110]:
env_table

,env_id,year,compartment_id,substance_id,flow_direction,release_pathway,unit,value,comment,main_id,facility_group_id,company_id,source_id
0,1754055,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,5610.000024,NaN,ON-MAIN-6e9b2449,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
1,1754056,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,6403.000027,NaN,ON-MAIN-f080c409,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
2,1754057,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,229916.000984,NaN,BC-MAIN-599152a0,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
3,1754058,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,2639.000011,NaN,ON-MAIN-52224e1e,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
4,1754060,2023,comp3c458811,NA - GHG,NaN,NaN,tCO2eq,4225.000018,NaN,ON-MAIN-48fe2205,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7010,ENV-687b8c8d-2023-15,2023,comp3c458811,NA - M09,Emission,NaN,t,8.6,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
7011,ENV-687b8c8d-2023-16,2023,comp3c458811,NA - M10,Emission,NaN,t,2.6,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
7012,ENV-687b8c8d-2023-17,2023,comp3c458811,NA - PAH,Emission,NaN,t,38.54224,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
7013,ENV-687b8c8d-2023-18,2023,comp3c458811,NA - SOx,Emission,NaN,t,0.243,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
7014,ENV-687b8c8d-2023-19,2023,comp3c458811,NA - M16,Emission,NaN,t,31.552,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023

## Production table

### Manually collected data

In [53]:
production_df.rename(columns={'row_id': 'prod_id'}, inplace=True)
production_df.drop(columns=['level', 'reported_company_nrcan', 'name', 
                            'facility_type', 'mining_processing_type', 'commodities_nrcan', 'source'], inplace=True)

In [55]:
# Put the unit in lower case for conversion
production_df['unit'] = production_df['unit'].str.lower()

In [56]:
from constants import unit_conversion

In [57]:
# Apply a function to convert the 'value' column to tonnes
# But we need to do that only for the 'Production' data_type and don't do it for any other data_type
production_df['value_tonnes'] = production_df.apply(
    lambda row: row['value'] * unit_conversion.get(row['unit'], 1) if row['data_type'] == 'Production' else np.nan, 
    axis=1
)

### CTrace dataset

In [58]:
ctrace_prod_gdf

,ctrace_id,year,activity,activity_units,capacity,capacity_units,source_id,substance_id,compartment_id,main_id
6,1754055,2023,8.630000e+05,t of copper ore,4.624000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-6e9b2449
7,1754056,2023,9.850000e+05,t of copper ore,3.554700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f080c409
8,1754057,2023,1.457500e+07,t of copper ore,3.670000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-599152a0
9,1754058,2023,4.060000e+05,t of copper ore,1.104100e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-52224e1e
11,1754060,2023,6.500000e+05,t of copper ore,4.822000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-48fe2205
12,1754061,2023,8.810000e+07,t of copper ore,6.450000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-6b4800fe
16,1754066,2023,7.288600e+07,t of copper ore,2.631000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-bf503b6b
17,1754067,2023,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-30c1828c
21,1754071,2023,0.000000e+00,t of copper ore,1.073810e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-e34feb4d
23,1754075,2023,1.526729e+06,t of copper ore,1.357000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-be5b3dc8
25,1754077,2023,1.501481e+06,t of copper ore,1.988200e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-e51eda66
29,1754081,2023,5.279710e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-7001a391
30,1754082,2023,0.000000e+00,t of copper ore,7.413000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-c139de6d
31,1754083,2023,0.000000e+00,t of copper ore,2.313000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,YT-MAIN-752fbcae
32,1754084,2023,2.127800e+07,t of copper ore,2.500250e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-ed23117f
33,1754085,2023,5.948239e+06,t of copper ore,4.902900e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-3f490561
34,1754086,2023,4.500000e+04,t of copper ore,4.110000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-23155c25
35,1754087,2023,2.993000e+06,t of copper ore,3.408700e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-aa76f6f2
43,1754096,2023,6.848790e+05,t of copper ore,1.500000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-a97821c0
44,1754097,2023,6.887709e+06,t of copper ore,4.549000e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,BC-MAIN-8eb8be0d
49,1754102,2023,1.431680e+06,t of copper ore,1.690000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-40ce0593
50,1754103,2023,6.820000e+05,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,MB-MAIN-e0a6250e
51,1754104,2023,5.180000e+05,t of copper ore,2.453000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-28f3f0fc
52,1754105,2023,0.000000e+00,t of copper ore,8.787959e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,QC-MAIN-b2148882
53,1754106,2023,1.760000e+06,t of copper ore,3.110000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-2d8801d6
54,25486533,2023,1.350000e+06,t of copper ore,2.500000e+06,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-f8313ebd
55,25486534,2023,3.798000e+06,t of copper ore,2.200000e+07,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,ON-MAIN-a3c56a83
56,36395102,2023,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-b64bae7a
57,36395102,2023,1.578280e+07,t of iron ore,4.789430e+08,tonnes,"Jolleys, M. et al (2024). Mineral Extraction s...",NA - GHG,comp3c458811,NL-MAIN-18695c6d

In [59]:
# Save units before melting
activity_units = ctrace_prod_gdf['activity_units']
capacity_units = ctrace_prod_gdf['capacity_units']

# Melt
ctrace_prod_gdf = pd.melt(
    ctrace_prod_gdf,
    id_vars=['ctrace_id', 'year', 'source_id', 'main_id'],
    value_vars=['activity', 'capacity'],
    var_name='data_type',
    value_name='value'
)

# Set data_type labels
ctrace_prod_gdf['data_type'] = ctrace_prod_gdf['data_type'].replace({
    'activity': 'Production',
    'capacity': 'Capacity'
})

# Concatenate units in correct order (activity first, then capacity)
ctrace_prod_gdf['unit'] = list(activity_units) + list(capacity_units)

In [60]:
ctrace_prod_gdf

,ctrace_id,year,source_id,main_id,data_type,value,unit
0,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Production,8.630000e+05,t of copper ore
1,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Production,9.850000e+05,t of copper ore
2,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Production,1.457500e+07,t of copper ore
3,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Production,4.060000e+05,t of copper ore
4,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Production,6.500000e+05,t of copper ore
5,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Production,8.810000e+07,t of copper ore
6,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Production,7.288600e+07,t of copper ore
7,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Production,0.000000e+00,t of copper ore
8,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Production,0.000000e+00,t of copper ore
9,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Production,1.526729e+06,t of copper ore
10,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Production,1.501481e+06,t of copper ore
11,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Production,5.279710e+05,t of copper ore
12,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Production,0.000000e+00,t of copper ore
13,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Production,0.000000e+00,t of copper ore
14,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Production,2.127800e+07,t of copper ore
15,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Production,5.948239e+06,t of copper ore
16,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Production,4.500000e+04,t of copper ore
17,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Production,2.993000e+06,t of copper ore
18,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Production,6.848790e+05,t of copper ore
19,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Production,6.887709e+06,t of copper ore
20,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Production,1.431680e+06,t of copper ore
21,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Production,6.820000e+05,t of copper ore
22,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Production,5.180000e+05,t of copper ore
23,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Production,0.000000e+00,t of copper ore
24,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Production,1.760000e+06,t of copper ore
25,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Production,1.350000e+06,t of copper ore
26,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Production,3.798000e+06,t of copper ore
27,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Production,1.578280e+07,t of iron ore
28,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Production,1.578280e+07,t of iron ore
29,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Capacity,4.624000e+06,tonnes
30,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Capacity,3.554700e+07,tonnes
31,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Capacity,3.670000e+08,tonnes
32,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Capacity,1.104100e+07,tonnes
33,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Capacity,4.822000e+06,tonnes
34,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Capacity,6.450000e+08,tonnes
35,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Capacity,2.631000e+08,tonnes
36,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Capacity,8.787959e+07,tonnes
37,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Capacity,1.073810e+08,tonnes
38,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Capacity,1.357000e+07,tonnes
39,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Capacity,1.988200e+07,tonnes
40,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Capacity,8.787959e+07,tonnes
41,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Capacity,7.413000e+06,tonnes
42,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Capacity,2.313000e+06,tonnes
43,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Capacity,2.500250e+08,tonnes
44,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Capacity,4.902900e+07,tonnes
45,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Capacity,4.110000e+06,tonnes
46,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Capacity,3.408700e+07,tonnes
47,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Capacity,1.500000e+07,tonnes
48,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Capacity,4.549000e+08,tonnes
49,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Capacity,1.690000e+07,tonnes
50,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Capacity,8.787959e+07,tonnes
51,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Capacity,2.453000e+06,tonnes
52,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Capacity,8.787959e+07,tonnes
53,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Capacity,3.110000e+07,tonnes
54,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Capacity,2.500000e+06,tonnes
55,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Capacity,2.200000e+07,tonnes
56,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Capacity,4.789430e+08,tonnes
57,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Capacity,4.789430e+08,tonnes

In [61]:
ctrace_prod_gdf['data_type'].value_counts()

data_type
Production    29
Capacity      29
Name: count, dtype: int64

In [62]:
ctrace_prod_gdf['unit'].value_counts()

unit
tonnes             29
t of copper ore    27
t of iron ore       2
Name: count, dtype: int64

In [63]:
ctrace_prod_gdf.rename(columns={'ctrace_id': 'prod_id'}, inplace=True)

In [64]:
# We add the missing columns
ctrace_prod_gdf['geography'] = 'Canada'
ctrace_prod_gdf['reference_point'] = 'Crude ore'
ctrace_prod_gdf['value_tonnes'] = ctrace_prod_gdf['value'] # they are always in tonnes

In [65]:
# Add a commodity column with would be = Copper if unit column = 't of copper ore' and = 'Iron' if unit column = 't of iron ore'
ctrace_prod_gdf['commodity'] = ctrace_prod_gdf['unit'].apply(
    lambda x: 'Copper' if 'copper' in x.lower() else ('Iron' if 'iron' in x.lower() else None)
)

In [66]:
ctrace_prod_gdf

,prod_id,year,source_id,main_id,data_type,value,unit,geography,reference_point,value_tonnes,commodity
0,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Production,8.630000e+05,t of copper ore,Canada,Crude ore,8.630000e+05,Copper
1,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Production,9.850000e+05,t of copper ore,Canada,Crude ore,9.850000e+05,Copper
2,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Production,1.457500e+07,t of copper ore,Canada,Crude ore,1.457500e+07,Copper
3,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Production,4.060000e+05,t of copper ore,Canada,Crude ore,4.060000e+05,Copper
4,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Production,6.500000e+05,t of copper ore,Canada,Crude ore,6.500000e+05,Copper
5,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Production,8.810000e+07,t of copper ore,Canada,Crude ore,8.810000e+07,Copper
6,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Production,7.288600e+07,t of copper ore,Canada,Crude ore,7.288600e+07,Copper
7,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
8,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
9,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Production,1.526729e+06,t of copper ore,Canada,Crude ore,1.526729e+06,Copper
10,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Production,1.501481e+06,t of copper ore,Canada,Crude ore,1.501481e+06,Copper
11,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Production,5.279710e+05,t of copper ore,Canada,Crude ore,5.279710e+05,Copper
12,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
13,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
14,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Production,2.127800e+07,t of copper ore,Canada,Crude ore,2.127800e+07,Copper
15,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Production,5.948239e+06,t of copper ore,Canada,Crude ore,5.948239e+06,Copper
16,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Production,4.500000e+04,t of copper ore,Canada,Crude ore,4.500000e+04,Copper
17,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Production,2.993000e+06,t of copper ore,Canada,Crude ore,2.993000e+06,Copper
18,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Production,6.848790e+05,t of copper ore,Canada,Crude ore,6.848790e+05,Copper
19,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Production,6.887709e+06,t of copper ore,Canada,Crude ore,6.887709e+06,Copper
20,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Production,1.431680e+06,t of copper ore,Canada,Crude ore,1.431680e+06,Copper
21,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Production,6.820000e+05,t of copper ore,Canada,Crude ore,6.820000e+05,Copper
22,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Production,5.180000e+05,t of copper ore,Canada,Crude ore,5.180000e+05,Copper
23,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Production,0.000000e+00,t of copper ore,Canada,Crude ore,0.000000e+00,Copper
24,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Production,1.760000e+06,t of copper ore,Canada,Crude ore,1.760000e+06,Copper
25,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Production,1.350000e+06,t of copper ore,Canada,Crude ore,1.350000e+06,Copper
26,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Production,3.798000e+06,t of copper ore,Canada,Crude ore,3.798000e+06,Copper
27,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Production,1.578280e+07,t of iron ore,Canada,Crude ore,1.578280e+07,Iron
28,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Production,1.578280e+07,t of iron ore,Canada,Crude ore,1.578280e+07,Iron
29,1754055,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-6e9b2449,Capacity,4.624000e+06,tonnes,Canada,Crude ore,4.624000e+06,None
30,1754056,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f080c409,Capacity,3.554700e+07,tonnes,Canada,Crude ore,3.554700e+07,None
31,1754057,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-599152a0,Capacity,3.670000e+08,tonnes,Canada,Crude ore,3.670000e+08,None
32,1754058,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-52224e1e,Capacity,1.104100e+07,tonnes,Canada,Crude ore,1.104100e+07,None
33,1754060,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-48fe2205,Capacity,4.822000e+06,tonnes,Canada,Crude ore,4.822000e+06,None
34,1754061,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-6b4800fe,Capacity,6.450000e+08,tonnes,Canada,Crude ore,6.450000e+08,None
35,1754066,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-bf503b6b,Capacity,2.631000e+08,tonnes,Canada,Crude ore,2.631000e+08,None
36,1754067,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-30c1828c,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
37,1754071,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-e34feb4d,Capacity,1.073810e+08,tonnes,Canada,Crude ore,1.073810e+08,None
38,1754075,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-be5b3dc8,Capacity,1.357000e+07,tonnes,Canada,Crude ore,1.357000e+07,None
39,1754077,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-e51eda66,Capacity,1.988200e+07,tonnes,Canada,Crude ore,1.988200e+07,None
40,1754081,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-7001a391,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
41,1754082,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-c139de6d,Capacity,7.413000e+06,tonnes,Canada,Crude ore,7.413000e+06,None
42,1754083,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",YT-MAIN-752fbcae,Capacity,2.313000e+06,tonnes,Canada,Crude ore,2.313000e+06,None
43,1754084,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-ed23117f,Capacity,2.500250e+08,tonnes,Canada,Crude ore,2.500250e+08,None
44,1754085,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-3f490561,Capacity,4.902900e+07,tonnes,Canada,Crude ore,4.902900e+07,None
45,1754086,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-23155c25,Capacity,4.110000e+06,tonnes,Canada,Crude ore,4.110000e+06,None
46,1754087,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-aa76f6f2,Capacity,3.408700e+07,tonnes,Canada,Crude ore,3.408700e+07,None
47,1754096,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-a97821c0,Capacity,1.500000e+07,tonnes,Canada,Crude ore,1.500000e+07,None
48,1754097,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",BC-MAIN-8eb8be0d,Capacity,4.549000e+08,tonnes,Canada,Crude ore,4.549000e+08,None
49,1754102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-40ce0593,Capacity,1.690000e+07,tonnes,Canada,Crude ore,1.690000e+07,None
50,1754103,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",MB-MAIN-e0a6250e,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
51,1754104,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-28f3f0fc,Capacity,2.453000e+06,tonnes,Canada,Crude ore,2.453000e+06,None
52,1754105,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",QC-MAIN-b2148882,Capacity,8.787959e+07,tonnes,Canada,Crude ore,8.787959e+07,None
53,1754106,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-2d8801d6,Capacity,3.110000e+07,tonnes,Canada,Crude ore,3.110000e+07,None
54,25486533,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-f8313ebd,Capacity,2.500000e+06,tonnes,Canada,Crude ore,2.500000e+06,None
55,25486534,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",ON-MAIN-a3c56a83,Capacity,2.200000e+07,tonnes,Canada,Crude ore,2.200000e+07,None
56,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-b64bae7a,Capacity,4.789430e+08,tonnes,Canada,Crude ore,4.789430e+08,None
57,36395102,2023,"Jolleys, M. et al (2024). Mineral Extraction s...",NL-MAIN-18695c6d,Capacity,4.789430e+08,tonnes,Canada,Crude ore,4.789430e+08,None

### Concatenate all production data into a single table

In [67]:
# Concatenate production and ctrace data 
production_table = pd.concat([production_df, ctrace_prod_gdf], ignore_index=True)

In [68]:
production_table.columns

Index(['prod_id', 'year', 'geography', 'main_id', 'facility_group_id',
       'company_id', 'commodity', 'reference_point', 'material_type',
       'data_type', 'method', 'unit', 'value', 'comment', 'source_id',
       'value_tonnes'],
      dtype='object')

In [69]:
column_order = ['prod_id', 'year', 'geography', 
                'commodity', 'reference_point', 'material_type', 'data_type', 
                'unit', 'value', 'value_tonnes', 'comment', 
                'main_id', 'facility_group_id','company_id', 'source_id']

In [70]:
production_table = production_table[column_order]

In [71]:
production_table

,prod_id,year,geography,commodity,reference_point,material_type,data_type,unit,value,value_tonnes,comment,main_id,facility_group_id,company_id,source_id
0,PROD-4ea8ac9d-2023-1,2023,Canada,Copper,Usable ore,Concentrate,Production,t,7.702439e+03,7.702439e+03,NaN,NU-MAIN-4ea8ac9d,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
1,PROD-4ea8ac9d-2023-2,2023,Canada,Gold,Usable ore,Contained metal in concentrate,Production,oz,3.066485e+05,9.537841e+00,NaN,NU-MAIN-4ea8ac9d,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
2,PROD-4ea8ac9d-2023-3,2023,Canada,Ore,Crude ore,Ore processed,Production,t,2.658396e+06,2.658396e+06,NaN,NU-MAIN-4ea8ac9d,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
3,PROD-4ea8ac9d-2023-4,2023,Canada,Silver,Usable ore,Contained metal in concentrate,Production,koz,5.880000e+02,1.828886e+01,NaN,NU-MAIN-4ea8ac9d,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
4,PROD-4ea8ac9d-2023-5,2023,Canada,Zinc,Usable ore,Concentrate,Production,t,2.577960e+03,2.577960e+03,NaN,NU-MAIN-4ea8ac9d,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,1754106,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,3.110000e+07,3.110000e+07,NaN,NL-MAIN-2d8801d6,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
273,25486533,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,2.500000e+06,2.500000e+06,NaN,ON-MAIN-f8313ebd,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
274,25486534,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,2.200000e+07,2.200000e+07,NaN,ON-MAIN-a3c56a83,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
275,36395102,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,4.789430e+08,4.789430e+08,NaN,NL-MAIN-b64bae7a,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."
276,36395102,2023,Canada,None,Crude ore,NaN,Capacity,tonnes,4.789430e+08,4.789430e+08,NaN,NL-MAIN-18695c6d,NaN,NaN,"Jolleys, M. et al (2024). Mineral Extraction s..."

## Tech attributes table

In [ ]:
tech_attributes_df

In [ ]:
tech_attributes_df.rename(columns={'row_id': 'tech_attr_id'}, inplace=True)

In [ ]:
tech_attributes_table = tech_attributes_df[['tech_attr_id', 'year', 'commodity', 'reference_point', 'material_type', 'method', 'unit', 'value', 'comment', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

## Protected & Indigenous table

In [ ]:
protected_mapping = {
    "WDPA_PID": "protected_area_id",
    "NAME": "land_name",
    "DESIG": "land_type",
    "STATUS_YR": "date"
}

indigenous_mapping = {
    "indigenous_land_id": "protected_area_id",
    "Name": "land_name",
    "Category": "land_type",
    "Data_Date": "date"
}

In [ ]:
protected_clean = wpda_gdf_polygons.rename(columns=protected_mapping)[["protected_area_id", "land_name", "land_type", "distance_km", "geometry", "main_id", "source_id"]].copy()

In [ ]:
indigenous_clean = indigenous_can_gdf.rename(columns=indigenous_mapping)[["protected_area_id", "land_name", "land_type", "distance_km", "geometry", "main_id", "source_id"]].copy()

In [ ]:
target_crs = "EPSG:4326"
protected_clean = protected_clean.to_crs(target_crs)
indigenous_clean = indigenous_clean.to_crs(target_crs)

In [ ]:
protected_land_table = pd.concat([protected_clean, indigenous_clean], ignore_index=True)
protected_land_table = gpd.GeoDataFrame(protected_land_table, geometry="geometry", crs=wpda_gdf_polygons.crs)

In [ ]:
protected_land_table

In [ ]:
protected_land_table['protected_area_id'].value_counts()

## Land cover table

In [ ]:
land_cover_table = land_cover_gdf.copy()
land_cover_table['npv_biome_type'] = npv_gdf['biome_type']
land_cover_table['source_id'] = land_cover_table['source_id'].astype(str) + ';' + npv_gdf['source_id'].astype(str)

In [ ]:
from db_creation_function import assign_row_id

In [ ]:
land_cover_table = assign_row_id(land_cover_table,
                                 facility_id_col='main_id', 
                                 prefix='land_cover_id')

In [ ]:
land_cover_table.drop(columns=['name', 'geometry'], inplace=True)
land_cover_table.rename(columns={'row_id': 'land_cover_id'}, inplace=True)
land_cover_table = land_cover_table[['land_cover_id', 'year', 'modis_land_cover',
       'esa_land_cover', 'npv_biome_type', 'main_id', 'source_id']]

In [ ]:
land_cover_table

## Intensity table

In [ ]:
intensity_df.rename(columns={'row_id': 'intensity_id'}, inplace=True)

In [ ]:
intensity_table = intensity_df[['intensity_id', 'year', 'commodity', 'type', 'subtype', 'unit', 'value', 'comment', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

In [ ]:
intensity_table

## Reserves and resources table

In [ ]:
reserves_table = reserves_df.rename(columns={'row_id': 'reserves_id'})

In [ ]:
reserves_table

In [ ]:
reserves_table = reserves_table[['reserves_id', 'year', 'commodity', 'reserves_resources', 'reserves_resources_type', 'ore', 'ore_unit', 'grade', 'grade_unit', 'metal_content', 'metal_content_unit', 'recovery_rate', 'comment', 'main_id', 'facility_group_id', 'source_id']]

## Technosphere table

In [ ]:
technosphere_df.rename(columns={'row_id': 'technosphere_id'}, inplace=True)

In [ ]:
#energy_table = energy_df.rename(columns={'row_id': 'nrj_id'})
technosphere_table = technosphere_df[['technosphere_id', 'year', 'flow_type', 'subflow_type', 'unit', 'value', 'comment', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

In [ ]:
technosphere_table

In [ ]:
technosphere_table['unit'].unique()

## Waste table

In [37]:
waste_df.rename(columns={'row_id': 'waste_id'}, inplace=True)

In [39]:
waste_table = waste_df[['waste_id', 'year', 'flow_type', 'subflow_type', 'unit', 'value', 'comment', 'main_id', 'facility_group_id', 'company_id', 'source_id']]

In [43]:
waste_table

,waste_id,year,flow_type,subflow_type,unit,value,comment,main_id,facility_group_id,company_id,source_id
0,WASTE-1f126a43-2023-1,2023,waste,Total waste generated|Total non-hazardous wast...,t,1.958354e+07,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
1,WASTE-1f126a43-2023-2,2023,waste,Total waste generated|Total hazardous waste ge...,t,1.414500e+04,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
2,WASTE-1f126a43-2023-3,2023,waste,Total waste generated,t,1.959768e+07,NaN,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
3,WASTE-1f126a43-2023-4,2023,waste,Total waste rock mined,t,NaN,Not available for 2023,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
4,WASTE-1f126a43-2023-5,2023,waste,Total waste rock mined|Total potentially hazar...,t,NaN,Not available for 2023,ON-MAIN-1f126a43,NaN,CMP-6265c407,SRC_AgnicoEagleMinesLimited_2023-Sustainabilit...
...,...,...,...,...,...,...,...,...,...,...,...
179,WASTE-687b8c8d-2023-14,2023,waste,Waste directed to disposal|Hazardous waste,t,1.215134e+06,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
180,WASTE-687b8c8d-2023-15,2023,waste,Waste directed to disposal|Non-Hazardous waste,t,7.449006e+04,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
181,WASTE-687b8c8d-2023-16,2023,waste,Total tailings generated,t,2.878047e+06,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
182,WASTE-687b8c8d-2023-17,2023,waste,Tailings sent to surface,t,1.215097e+06,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023
183,WASTE-687b8c8d-2023-18,2023,waste,Sub-surface tailings,t,1.662950e+06,NaN,ON-MAIN-687b8c8d,NaN,CMP-3a4ccc7f,SRC_AlamosGoldInc_Data_2023

## Tailings table

In [ ]:
tailings_table = tailings_gdf.rename(columns={'row_id': 'tailing_id',
                             'current_tailings_storage': 'current_storage'})
tailings_table = tailings_table[['tailing_id', 'year', 'tsf_name', 'status', 'construction_year', 
                             'raise_type', 'current_maximum_height', 'current_storage', 'hazard_categorization', 
                             'classification_system', 'geometry', 'main_id', 'source_id']]

## Land occupation table

In [ ]:
# Change the Land-use values from m2 to km2
li_canada_gdf['area_km2'] = li_canada_gdf['Land_use'].apply(lambda x: x / 1e6 if pd.notna(x) else x)

In [ ]:
li_canada_gdf.rename(columns={'li_id': 'land_occupation_id'}, inplace=True)

In [ ]:
li_canada_gdf = li_canada_gdf[['land_occupation_id', 'area_km2', 'geometry', 'main_id', 'source_id']]

In [ ]:
tang_gdf = polygon_gdf.rename(columns={'tang_id': 'land_occupation_id'}, inplace=True)

In [ ]:
polygon_gdf = polygon_gdf.to_crs(li_canada_gdf.crs)

In [ ]:
# Add the li_canada_gdf to the polygon_gdf
land_occupation_table = pd.concat([polygon_gdf, li_canada_gdf], ignore_index=True)

In [ ]:
land_occupation_table

In [ ]:
land_occupation_table = land_occupation_table[['land_occupation_id', 'area_km2', 'geometry', 'distance_km', 'main_id', 'tailing_id', 'source_id']]

In [ ]:
# Drop duplicates caused by tailing id, so drop duplicates only on the 
land_occupation_table = land_occupation_table.drop_duplicates(subset=['land_occupation_id'])

In [ ]:
land_occupation_table

In [ ]:
land_occupation_table['compartment_id'] = 'compde27e9f6'

## By-product

In [ ]:
bth_table = bth_df.drop(columns=['facility_name'])

In [ ]:
bth_table

## Archetypes table

In [ ]:
archetypes_df.rename(columns={'row_id': 'archetype_id',
                              'mining_processing_type_nrcan': 'mining_method',
                              'mining_method_cleaned': 'mining_submethod',
                              'likely_ore_type': 'ore_type'
                              }, inplace=True)

In [ ]:
archetypes_df

In [ ]:
archetype_table = archetypes_df[['archetype_id', 'ore_type', 'mining_method', 'mining_submethod', 'mining_depth', 'main_id', 'facility_group_id', 'source_id']]

In [ ]:
archetype_table

## Water risk table

In [ ]:
water_risk_table = water_risk_gdf.rename(columns={'row_id': 'water_risk_id'})
water_risk_table = water_risk_table[['water_risk_id', 'indicator', 'value', 'year', 'scenario', 'value', 'main_id', 'source_id']]

In [ ]:
water_risk_table

## Climate categories table

In [ ]:
climate_category_table = climate_category_gdf.rename(columns={'row_id': 'climate_category_id'})
climate_category_table = climate_category_table[['climate_category_id', 'year', 'scenario', 'category', 'main_id', 'source_id']]

In [ ]:
climate_category_table

## Weather table

In [ ]:
weather_table = weather_gdf.rename(columns={'row_id': 'weather_id'})
weather_table = weather_table[['weather_id', 'year', 'variable', 'value', 'unit', 'scenario', 'main_id', 'source_id']]

In [ ]:
weather_table

## Conflict table

In [ ]:
conflict_table = conflict_gdf

In [ ]:
conflict_table = conflict_table[['ej_atlas_id', 'case_name', 'start_date', 'end_date', 
                             'conflict_description', 'conflict_details', 'population_affected',
                             'conflict_intensity', 'project_status', 'main_id', 'source_id']]

In [ ]:
conflict_table

## Population table

In [ ]:
population_table = population_gdf.rename(columns={'row_id': 'population_id'})
population_table = population_table[['population_id', 'year', 'buffer_size', 'total_population', 'main_id', 'source_id']]

In [ ]:
population_table

## Peatland table

In [ ]:
peatland_table = peatland_gdf[['peatland_presence', 'main_id', 'source_id']]

In [ ]:
peatland_table

## Prioritization area table

In [ ]:
prioritization_area_gdf

In [ ]:
prioritization_conservation_area_table = prioritization_area_gdf.rename(columns={
    'jung_priority_point': 'score_1_km',
    'jung_priority_mean_50km': 'mean_score_50_km',})
prioritization_conservation_area_table = prioritization_conservation_area_table[['score_1_km', 'mean_score_50_km', 'main_id', 'source_id']]

In [ ]:
prioritization_conservation_area_table

# Exports

## Exports tables to CSV

In [111]:
env_table.to_csv(r'database/CSV/environment_table.csv', index=False, encoding="utf-8-sig")
#technosphere_table.to_csv(r'database/csv/technosphere_table.csv', index=False, encoding="utf-8-sig")
#production_table.to_csv(r'database/CSV/production_table.csv', index=False, encoding="utf-8-sig")
#tech_attributes_df.to_csv(r'database/CSV/tech_attributes_table.csv', index=False, encoding="utf-8-sig")
#reserves_df.to_csv(r'database/CSV/reserves_table.csv', index=False, encoding="utf-8-sig")
#archetype_table.to_csv(r'database/CSV/archetypes_table.csv', index=False, encoding="utf-8-sig")
#intensity_table.to_csv(r'database/CSV/intensity_table.csv', index=False, encoding="utf-8-sig")
#waste_table.to_csv(r'database/CSV/waste_table.csv', index=False, encoding="utf-8-sig")

In [ ]:
# Export all the tables to CSV
main_gdf.to_csv(r'database/CSV/main_table.csv', index=False, encoding="utf-8-sig")
production_table.to_csv(r'database/CSV/production_table.csv', index=False, encoding="utf-8-sig")
env_table.to_csv(r'database/CSV/env_table.csv', index=False, encoding="utf-8-sig")
land_cover_table.to_csv(r'database/CSV/land_cover_table.csv', index=False, encoding="utf-8-sig")
#env_int_df.to_csv(r'database/CSV/env_int_table.csv', index=False, encoding="utf-8-sig")
reserves_df.to_csv(r'database/CSV/reserves_table.csv', index=False, encoding="utf-8-sig")
technosphere_df.to_csv(r'database/csv/technosphere_table.csv', index=False, encoding="utf-8-sig")
tailings_gdf.to_csv(r'database/CSV/tailings_table.csv', index=False, encoding="utf-8-sig")
polygon_gdf.to_csv(r'database/CSV/land_occupation_table.csv', index=False, encoding="utf-8-sig")
archetypes_df.to_csv(r'database/CSV/archetypes_table.csv', index=False, encoding="utf-8-sig")
water_risk_gdf.to_csv(r'database/CSV/water_risk_table.csv', index=False, encoding="utf-8-sig")
climate_category_gdf.to_csv(r'database/CSV/climate_category_table.csv', index=False, encoding="utf-8-sig")
weather_gdf.to_csv(r'database/CSV/weather_table.csv', index=False, encoding="utf-8-sig")
conflict_gdf.to_csv(r'database/CSV/conflict_table.csv', index=False, encoding="utf-8-sig")
population_gdf.to_csv(r'database/CSV/population_table.csv', index=False, encoding="utf-8-sig")
peatland_gdf.to_csv(r'database/CSV/peatland_table.csv', index=False, encoding="utf-8-sig")
prioritization_area_gdf.to_csv(r'database/CSV/prioritization_area_table.csv', index=False, encoding="utf-8-sig")
bth_df.to_csv(r'database/CSV/bth_table.csv', index=False, encoding="utf-8-sig")
protected_land_table.to_csv(r'database/CSV/protected_land_table.csv', index=False, encoding="utf-8-sig")

In [ ]:
# We remove the geometry column to avoid issues with large file size
#protected_land_table.drop(columns=['geometry'], inplace=True)
protected_land_table.to_csv(r'database/CSV/protected_land_table.csv', index=False, encoding="utf-8-sig")

## Export DB to SQLite

In [ ]:
from matching_functions import create_and_populate_database

In [ ]:
tables_dict = {
    "Main": main_gdf,
    
    "Sources": source_table, 
    "Substances": substance_table,
    "Compartments": compartment_table,
    
    "Reserves_resources": reserves_table,
    "Production": production_table,
    "Energy": energy_table,
    "Environmental_flows": env_table,
    "Environmental_intensity": env_int_table,
    "Archetypes": archetype_table,
    
    "Tailings": tailings_table,
    "Land_occupation": land_occupation_table,
    "By_products": bth_table,
    
    "Water_risk": water_risk_table,
    "Climate_category": climate_category_table,
    "Weather": weather_table,
    "Land_cover": land_cover_table,
    "Conflict": conflict_table,
    "Population": population_table,
    "Peatland": peatland_table,
    "Prioritization_conservation_areas": prioritization_conservation_area_table,
    "Protected_indigenous_lands": protected_land_table,
    
}

# Run the function
create_and_populate_database(
    db_path="database/metallican.sqlite",
    schema_path="database/schema.sql",
    tables_dict=tables_dict,
    keep_geometry_tables=["main", "tailings", "polygons"]
)